### ISSUE TITLE
ICE (segfault)

### ISSUE THREAD

**Issue by sezero** [bebbo/gcc#1]
Built the m68k cross-toolchain from your fork with --gcc=6 --bibutils=2.14 .
Trying to build uhexen2 source (https://sf.net/p/uhexen2/ or github mirror at 
https://github.com/svn2github/uhexen2.git) with this, gcc segfaults in our cl_demo.c:
```
cd uhexen2/engine/hexen2/
m68k-amigaos-gcc -c -I. -I../h2shared -I../../common -I../../oslibs/amigaos/include -Wall -O2 -DNDEBUG=1 -ffast-math -fomit-frame-pointer -noixemul -m68020-60 -o cl_demo.o cl_demo.c
*** Error in `/home/me/m68k/libexec/gcc/m68k-amigaos/6.3.1b/cc1': malloc(): memory corruption: 0x0000000003b896b0 ***
*** Error in `/home/me/m68k/libexec/gcc/m68k-amigaos/6.3.1b/cc1': malloc(): memory corruption: 0x0000000003b896b0 ***
*** Error in `/home/me/m68k/libexec/gcc/m68k-amigaos/6.3.1b/cc1': malloc(): memory corruption (fast): 0x0000000003ba96a0 ***
m68k-amigaos-gcc: internal compiler error: Segmentation fault (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.

```

Attached the preprocessed source here.
[cl_demo.i.zip](https://github.com/bebbo/gcc/files/1153041/cl_demo.i.zip)

**Comment by bebbo** [comment]
The attached precompiled source is a very good idea. Thanks!

Fix in progress.

**Comment by sezero** [comment]
Don't know whether this is host-os specific: For what it's worth, this issue happened to me
on my x86_64-linux (fedora 20).
