### ISSUE TITLE
-mregparm makes malloc() fail

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#10]
Even the simplest program fails to allocate memory:

```
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
    void *ptr = malloc(0x400);
    if (!ptr) {
        printf("Allocation failed!\n");
    }
}
```

In libnix malloc.c I can see:

https://github.com/bebbo/libnix/blob/master/sources/nix/stdlib/malloc.c

```
void __initmalloc(void)
{
  ...
}

void __exitmalloc(void)
{
...
}

ADD2EXIT(__exitmalloc,-50);
ADD2INIT(__initmalloc,-50);
```

Is it possible the effect that ADD2INIT/EXIT should have had is being ignored and thus, malloc just bails out?

**Comment by bebbo** [comment]
```
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
    void *ptr = malloc(0x400);
    if (!ptr) {
        printf("Allocation failed!\n");
    } else {
        printf("Allocated %p!\n", ptr);
    }
}
```
`m68k-amigaos-gcc -noixemul mall.c -Os -o mall`
copy to Amiga and run:
```
Allocated 0x405e1fb4!
```

**Comment by mheyer32** [comment]
Have you considered the usual suspects?
I'm compiling with

RUNTIME_CFLAGS= -noixemul -DUSENOIXEMUL -mregparm=4

CFLAGS = $(RUNTIME_CFLAGS) -v -fbbb=Vabcimeps -Ofast -fbaserel -fstrength-reduce -m68030 -m68881 -fomit-frame-pointer -Werror -Wimplicit -Wstrict-prototypes

**Comment by bebbo** [comment]
Oh - Uh: `mregparm`...

that needs plenty header patching to qualify all function prototypes with `__stdargs`

**Comment by bebbo** [comment]
clib2 headers were updated and all functions are now qualified with `__stdargs`.

please test

**Comment by mheyer32** [comment]
Now seeing a lot of this when compiling the toolchain:

include/stdlib.h:191:1: warning: '__stkparm__' attribute only applies to function types [-Wattributes]
 extern __stdargs unsigned long __slab_purge_threshold;

**Comment by mheyer32** [comment]
no, that doesn't fix it

"clib2 headers were updated and all functions are now qualified with __stdargs."

This particular issue is about -noixemul, did you test that?

**Comment by mheyer32** [comment]
Just an update. With the latest toolchain I tried  -mregparms in conjuction with -mcrt=clib2 on the Adoom build... it crashed pretty early on with an illegal instruction exception.

**Comment by bebbo** [comment]
ok - finally pushed the changes to ixemul.

don't forget to update properly

**Comment by mheyer32** [comment]
With the latest toolchain Adoom starts up and gets past the first malloc.
It still doesn't fully load into the main menu with -noixemul -mregparm=4.
It'll start, load some stuff and then crap out at:
```
P_Init: Init Playloop state.
Error: R_InitSprites: Sprite TROO : A : 1 has two lumps mapped to it
```

I'll close this issue and open a new one once I have something more concrete to report.

**Comment by bebbo** [comment]
cool
