### ISSUE TITLE
C++11 Support?

### ISSUE THREAD

**Issue by ksdhans** [bebbo/gcc#100]
How's the C++11 support in this compiler? Are things such as std::mutex and std::thread usable? 

NOTE: I was going to ask this on the English Amiga Board, but can't register an account there...

**Comment by bebbo** [comment]
there is a libthread.a but no one had the time yet to code the target specific std stuff.

**Comment by ksdhans** [comment]
That sounds promising. Perhaps the C++11 threading code from the AmigaOS 4.1 GCC port (adtools) could be adapted?

Is anyone working on adding the necessary code?

**Comment by bebbo** [comment]
> 
> 
> That sounds promising. Perhaps the C++11 threading code from the AmigaOS 4.1 GCC port (adtools) could be adapted?
> 
> Is anyone working on adding the necessary code?

not that I know - You're welcome to take care of it.

**Comment by ksdhans** [comment]
Hehe. I'm NOT in a position to be working on the standard library implementations themselves.

I'm asking because I want to know how feasible backporting some software to AmigaOS 3.1 would be. When it comes to code using C++11 threading/mutexes, the answer is clearly "not yet."

**Comment by bebbo** [comment]
you can build amiga-gcc with `THREADS=posix` to get a multithreaded version.
```
make clean
make all THREADS=posix
```
