### ISSUE TITLE
Dbcc bug

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#105]
The first example of strncopy fails to compile the while loop using dbra while the second version is okay. Something from the condition is influencing the subq as the highlight is showing it as part of the condition, which it's not.

https://franke.ms/cex/z/5BAQm7

**Comment by bebbo** [comment]
uhm - so what do you suggest? Write better C code?

**Comment by bebbo** [comment]
```
void strncopy3(char *dst,const char *src,short n)
   {
     if (!dst || !src)
       return;
     char c;
     for (n;n>=0;n--) {
       c=*src++;
       *dst++=c;
       if( c==0x0 ) break;
     }
   }

void strncopy4(char *dst,const char *src,short n)
   {
     char c;
     for (n;n>=0;n--) {
       c=*src++;
       *dst++=c;
       if( c==0x0 ) break;
     }
   }

void strncopy5(char *dst,const char *src,short n)
   {
     if (dst && src)
     for (n;n>=0;n--) {
       char c=*src++;
       *dst++=c;
       if( c==0x0 ) break;
     }
   }
```

**Comment by nonarkitten** [comment]
Don't be an asshole -- this was just meant to serve as an example where dbcc isn't getting emitted. I'm sure it happens elsewhere.

**Comment by bebbo** [comment]
Yes, it happens elsewhere. It's looking simple, but it isn't - it's way too complex.
