### ISSUE TITLE
Internal Compiler error when using -fselective-scheduling.

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/gcc#107]
Hello, If I do `m68k-amigaos-gcc-6.5.0b.exe -mhard-float -m68080 -Ofast -fselective-scheduling -c snd_mix.tst.c -o snd_mix.tst.o` on this file [snd_mix.tst.c.gz](https://github.com/bebbo/gcc/files/3388688/snd_mix.tst.c.gz), I get this error:
```
snd_mix.c: In function 'S_TransferPaintBuffer':
snd_mix.c:135:1: internal compiler error: in final_scan_insn, at final.c:2980
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

If I remove -fselective-scheduling, it compiles fine. 

GCC version is:
```
$ m68k-amigaos-gcc-6.5.0b.exe -v
Using built-in specs.
COLLECT_GCC=/AMIGA-~1/bin/m68k-amigaos-gcc-6.5.0b
COLLECT_LTO_WRAPPER=C:/Users/SAMUEL~1/Desktop/AMIGA-~1/libexec/gcc/m68k-amigaos/6.5.0b/lto-wrapper
Target: m68k-amigaos
Configured with: /c/msys64/home/test/amiga-gcc/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/c/msys64/home/test/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --enable-threads=posix --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: posix
gcc version 6.5.0b 190711211949 (GCC)
```

**Comment by Samuel-DEVULDER** [comment]
Same source compiles fine with the gcc version of cex: https://franke.ms/cex/z/Qp3Kv-

**Comment by bebbo** [comment]
> 
> 
> Same source compiles fine with the gcc version of cex: https://franke.ms/cex/z/Qp3Kv-

then your local version is outdated^^ atm cex is using the devel1 branch of gcc...
... these changes should be live soon.

**Comment by Samuel-DEVULDER** [comment]
Hum.. it is the version available from: https://franke.ms/download/setup-amiga-gcc.exe
with build-date: gcc version 6.5.0b 190711211949 (GCC), eg 2 days ago.

Outdated, possibly, but not that much ;)

**Comment by bebbo** [comment]
I hope to get the build stable again... then there is a new version tomorrow.

**Comment by bebbo** [comment]
please test

**Comment by Samuel-DEVULDER** [comment]
Is a new version ready?

**Comment by bebbo** [comment]
`gcc version 6.5.0b 190814133058 (GCC)` is available in the repo - you only have to build it.

**Comment by Samuel-DEVULDER** [comment]
ok. That's fine. Thanks.
