### ISSUE TITLE
Nonsense linker paths

### ISSUE THREAD

**Issue by chris-y** [bebbo/gcc#11]
I've built gcc6 based off of your patches , and I obviously understand there might be something different in the way I'm building it because of this but the old gcc4.3 built using the correct paths and the same options so I think gcc6 ought to too :)  I'm building as a cross-compiler if that makes a difference.

When gcc comes to linking anyting it tried to access the following path:
/opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/lib//opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/lib/ncrt0.o

Obviously this path is complete nonsense because the initial bit (I've since fixed the m68k-amigaos/m68k-unknown-amigaos difference in my patches) has been prepended to something else which would also work as a complete path.

It *should* probably be /opt/netsurf/m68k-unknown-amigaos/cross/m68k-(unknown-)amigaos/clib2/lib/ncrt0.o (that is to say, the first part of the path before it has appended the complete path again is correct, but missing the object filename) but I can't figure out how to fix the path, other than it is probably related to amiga_m68k_prefix_func() or the sdk_root specs.

**Comment by bebbo** [comment]
please provide the output if you add `-v -Xlinker --verbose`.

My first guess that the path used calling configure might be already bogus. So the full configure command line might be of interest too.

**Comment by chris-y** [comment]
This is what I get building something with those extra args:
`chris@debian-vm:~$ /opt/netsurf/m68k-unknown-amigaos/cross/bin/m68k-unknown-amigaos-gcc -o test -v -Xlinker --verbose test.c
Using built-in specs.
COLLECT_GCC=/opt/netsurf/m68k-unknown-amigaos/cross/bin/m68k-unknown-amigaos-gcc
COLLECT_LTO_WRAPPER=/opt/netsurf/m68k-unknown-amigaos/cross/libexec/gcc/m68k-unknown-amigaos/6.4.0/lto-wrapper
Target: m68k-unknown-amigaos
Configured with: /home/chris/netsurf/toolchains/m68k-unknown-amigaos/builddir/srcdir/gcc/configure --prefix=/opt/netsurf/m68k-unknown-amigaos/cross --target=m68k-unknown-amigaos --disable-threads --disable-nls --disable-c-mbchar --enable-languages=c --enable-checking=no --enable-c99 --with-cross-host --disable-multilib --without-x --enable-maintainer-mode --disable-shared --without-headers : (reconfigured) /home/chris/netsurf/toolchains/m68k-unknown-amigaos/builddir/srcdir/gcc/configure --prefix=/opt/netsurf/m68k-unknown-amigaos/cross --target=m68k-unknown-amigaos --disable-threads --disable-nls --disable-c-mbchar --enable-languages=c --enable-checking=no --enable-c99 --with-cross-host --disable-multilib --without-x --enable-maintainer-mode --disable-shared --without-headers
Thread model: single
gcc version 6.4.0 (GCC) 
COLLECT_GCC_OPTIONS='-o' 'test' '-v' '-mcpu=68000'
 /opt/netsurf/m68k-unknown-amigaos/cross/libexec/gcc/m68k-unknown-amigaos/6.4.0/cc1 -quiet -v -isystem /opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/include -DCLIB2 -D__CLIB2__ -D__CLIB2 test.c -quiet -dumpbase test.c -mcpu=68000 -auxbase test -version -o /tmp/cc9iiSFl.s
GNU C11 (GCC) version 6.4.0 (m68k-unknown-amigaos)
	compiled by GNU C version 6.3.0 20170516, GMP version 6.1.2, MPFR version 3.1.6, MPC version 1.0.2, isl version none
GGC heuristics: --param ggc-min-expand=77 --param ggc-min-heapsize=88493
ignoring nonexistent directory "/opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/include
 /opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/sys-include/../../include
 /opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/sys-include
 /opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/include
End of search list.
GNU C11 (GCC) version 6.4.0 (m68k-unknown-amigaos)
	compiled by GNU C version 6.3.0 20170516, GMP version 6.1.2, MPFR version 3.1.6, MPC version 1.0.2, isl version none
GGC heuristics: --param ggc-min-expand=77 --param ggc-min-heapsize=88493
Compiler executable checksum: 1563e3791a818c13022cfbfb588a4f0c
COLLECT_GCC_OPTIONS='-o' 'test' '-v' '-mcpu=68000'
 /opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/bin/as -m68000 -S -o /tmp/cc8qqyjg.o /tmp/cc9iiSFl.s
COMPILER_PATH=/opt/netsurf/m68k-unknown-amigaos/cross/libexec/gcc/m68k-unknown-amigaos/6.4.0/:/opt/netsurf/m68k-unknown-amigaos/cross/libexec/gcc/m68k-unknown-amigaos/6.4.0/:/opt/netsurf/m68k-unknown-amigaos/cross/libexec/gcc/m68k-unknown-amigaos/:/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/:/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/:/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/bin/
LIBRARY_PATH=/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/:/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/lib/
COLLECT_GCC_OPTIONS='-o' 'test' '-v' '-mcpu=68000'
 /opt/netsurf/m68k-unknown-amigaos/cross/libexec/gcc/m68k-unknown-amigaos/6.4.0/collect2 -L/opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/lib -o test /opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/lib//opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/lib/ncrt0.o -L/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0 -L/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/lib --verbose /tmp/cc8qqyjg.o -lc -lamiga -ldebug -lgcc -lc
GNU ld version 2.14 20030612 (adtools build 20080628)
  Supported emulations:
   amiga
   amiga_bss
using internal linker script:
==================================================
/* Default linker script, for normal executables */
OUTPUT_FORMAT("amiga")
OUTPUT_ARCH(m68k)
SEARCH_DIR("/opt/netsurf/m68k-unknown-amigaos/cross/m68k-unknown-amigaos/lib");
SECTIONS
{
  PROVIDE(___machtype = 0x0);
  . = 0x0;
  .text :
  {
    __stext = .;
    *(.text)
    ___datadata_relocs = .;
    __etext = .;
  }
  ___text_size = SIZEOF(.text);
  . = ALIGN(0x0);
  .data :
  {
    __sdata = .;
    CONSTRUCTORS
    *(.data)
    ___a4_init = 0x7ffe;
    __edata = .;
  }
  ___data_size = SIZEOF(.data);
  .bss :
  {
    __bss_start = .;
    *(.bss)
    *(COMMON)
    __end = .;
  }
  ___bss_size = SIZEOF(.bss);
  .data_chip :
  {
    *(.data_chip)
  }
  .bss_chip :
  {
    *(.bss_chip)
  }
}


==================================================
attempt to open /opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/lib//opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/lib/ncrt0.o failed
/opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/bin/ld: cannot open /opt/netsurf/m68k-unknown-amigaos/cross/m68k-amigaos/clib2/lib//opt/netsurf/m68k-unknown-amigaos/cross/lib/gcc/m68k-unknown-amigaos/6.4.0/../../../../m68k-unknown-amigaos/lib/ncrt0.o: No such file or directory
collect2: error: ld returned 1 exit status
chris@debian-vm:~$ 
`

Command used to call configure is:
`configure \
				--prefix=/opt/netsurf/m68k-unknown-amigaos/cross \
				--target=m68k-unknown-amigaos \
				--disable-threads \
				--disable-nls --disable-c-mbchar \
				--enable-languages=c --enable-checking=no \
				--enable-c99 --with-cross-host \
				--disable-multilib --without-x \
				--enable-maintainer-mode --disable-shared \
				--without-headers`

**Comment by bebbo** [comment]
Uhm, guess you are not building my fork. The gcc version of my fork always prints
```
gcc version 6.4.1b 20180121-120800 (GCC)
```
The version and date may change, but I always add a `b`.

The current git hash is 61f2c1679983cf9f9f53a779950a58ffc9d23067

**Comment by chris-y** [comment]
I applied your patches on top of base gcc 6.4.  I had to remove the version patch because the patching system didn't like it.  You can see the patches I used here: http://git.netsurf-browser.org/toolchains.git/tree/m68k-unknown-amigaos/recipes/patches/gcc/gcc6.p?h=chris/gcc6-os3

It's not directly off your fork as I need the toolchain I use to be reproducible, so have to use the release archives and apply patches.  It should however be functionally identical.  I can try building directly off the fork but that might take a bit of time to sort out.

**Comment by chris-y** [comment]
Yes, configure is called with an absolute path.

Odd, I'll try building it direct from your fork and see what I get.

**Comment by chris-y** [comment]
Built from your fork and problem resolved, sorry to waste your time.

Quick follow-up question: Is it possible to stop gcc-ranlib being built?  It's a plugin version of ranlib but it doesn't work here (probably because our binutils is old) and unfortunately libtool tried to use it.  I can just delete it.. but it's neater not to have it in the first place.

**Comment by bebbo** [comment]
Great to hear you solved it!

I don't have a gcc-ranlib problem. Why not also use my binutils fork? :-)

**Comment by chris-y** [comment]
Ah, maybe that's required!  I'll look at it, thanks!
