### ISSUE TITLE
Latest compiler changes break DOpus, DoomAttack, ScummVM

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#110]
DOpus will crash on startup with an illegal instruction

ScummVM won't start anymore, aborting in new() with std::bad_alloc 

DoomAttack hangs forever while compiling one of the files:
`m68k-amigaos-gcc -noixemul -msmall-code -g -ggdb -Werror -Wimplicit -Wstrict-prototypes -D__BIG_ENDIAN__ -DNORMALUNIX -DAMIGA -D__NO_NET_API -include "doomdef.h" -I./plugins/Include -I./ -DNDEBUG -Ofast -ffast-math -fomit-frame-pointer -m68060 -Dversion060 -c p_inter.c -o /home/matze/DoomAttack/gnudoom/build//060/p_inter.o`

![image](https://user-images.githubusercontent.com/33539855/61350306-00f33400-a81c-11e9-82fa-03f33ed402e2.png)

**Comment by bebbo** [comment]
my stack check fix is still not in the scummvm repo...

**Comment by mheyer32** [comment]
How is the stack check related?

**Comment by bebbo** [comment]
If I build scummvm from your repo, it always aborts complaing about the stack: The read value is not set in all Kickstart version. You have to calculate the size yourself to be compliant

**Comment by mheyer32** [comment]
Ok, now it makes sense. I checked the fix into master. Good luck!

**Comment by bebbo** [comment]
do you have a date where it worked for you?

e.g. DirectoryOpus is running until I close it. But same stuff happens with acc2e436ec6acaff4edb7203b81724210c6224e0 from 28. Jun...

**Comment by mheyer32** [comment]
I don't know whats going on, right now I can't reproduce a version that runs, even going back to a compiler version I believe successfully ran prior. Something must be off with my setup.

**Comment by mheyer32** [comment]
After completely nuking my prefix directory and rebuilding the toolchain, DOpus starts again but still has issues:
1) the device list in listers shows  garbage
2) double-clicking on icons in  lister-windows doesn't work.
(not expecting you to dive in here)

DoomAttack still hangs when building p_inter.o (this one might be better to attack first)

ScummVM still exits early, but leaves some errors in the log about a garbled palette file(?)

**Comment by mheyer32** [comment]
Today's compiler fixed the hang in compiling DoomAttack, so scratch that.

The ScummVM build crashes with an internal compiler error:
https://github.com/mheyer32/scummvm-amigaos3/tree/latest_scummvm_merge
(notice how the top commit in this brnach removes `-flto` from the build flags)
`./configure --host=m68k-amigaos --disable-all-engines --enable-engine=sci,lol --disable-mt32emu --enable-release --enable-optimizations  --disable-hq-scalers --with-amiga-prefix=/media/sf_Amiga/ScummVM --enable-c++11`
```
engines/kyra/sequence/sequences_lol.cpp: In member function 'int Kyra::LoLEngine::chooseCharacter()':
engines/kyra/sequence/sequences_lol.cpp:402:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile.common:123: recipe for target 'engines/kyra/sequence/sequences_lol.o' failed
```

DOpus  compiles & runs. The device list does not exhibit corruption, but double-clicking on icons in windows does not get registered.

**Comment by mheyer32** [comment]
Thanks, I confirm that the patch fixes the ScummVM build break.

There's still weirdness left, though.
If you build the version I linked to above, it'll produce an executable that starts, but can't run SCI games like Space Quest (The games will crash into the ScummVM internal debugger complaining about bad object IDs or slectors). This is an issue that got introduced quite some time ago, but I didn't have the time to really debug it a lot :-(

When reverting the topmost commit "Test: disable -flto, add -lpthread for bdeugging build" (effectively re-enabling -flto), the resulting executable will not be able to parse its XML files (the error.log will complain about various things that cannot be parsed).
The parsing involves string functions and functions with variable parameter lists ('...'). Maybe you can figure out why that happens.
Also notice how passing "--enable-debug" to ScummVM's configure line will break the build, because again some dependency to pthread creeps back in.

**Comment by mheyer32** [comment]
As of today the DOpus build breaks this way:

```
matze@osboxes:~/dopus5allamigas/source/Program$ make -f makefile.os3  misc.o
>>>>>Compiling misc.c

misc.c:287: confused by earlier errors, bailing out
makefile.os3:29: recipe for target 'misc.o' failed
make: *** [misc.o] Error 1
```

ScummVM builds & runs in debug mode, but fails start start SCI games in release mode. I.e.

`./configure --host=m68k-amigaos --disable-all-engines --enable-engine=scumm,scumm7-8,sci,lol --disable-mt32emu --enable-debug --disable-optimizations  --disable-hq-scalers --with-amiga-prefix=/media/sf_Amiga/ScummVM --enable-c++11`

works, while

`./configure --host=m68k-amigaos --disable-all-engines --enable-engine=scumm,scumm_7-8,sci,lol --disable-mt32emu --enable-release --enable-optimizations  --disable-hq-scalers --with-amiga-prefix=/media/sf_Amiga/ScummVM --enable-c++11`

does not

**Comment by bebbo** [comment]
what was last version that worked for you?

**Comment by mheyer32** [comment]
That is hard to say. ScummVM stopped working properly a while (months?) ago - SCI games (Space Quest, Kings Quest etc) would not start up anymore and instead break into the ScummVM internal console/debugger.

DOpus used to compile throughout your recent changes, but not the ones introduced on Wednesday/Thursday (can't pin it down exactly). But still, even when it compiled, Dopus exhibited strange behavior. Sometimes it would crash immediately on startup. Sometimes double-clicking on icons in lister windows had no effect. Sometimes it would work again... and only recently the DOpus internal text reader would read/show garbage (at first I thought ScummVM's ini file was corrupted and only later realized that the file is ok, but the text reader is broken :-) )

ADoom and DoomAttack proved to be rather resilient to recent compiler changes.

![image](https://user-images.githubusercontent.com/33539855/63177440-c4724e00-bffc-11e9-80a4-c4d7c20cd462.png)

![image](https://user-images.githubusercontent.com/33539855/63177528-f5eb1980-bffc-11e9-9417-68c9aa6d25f5.png)

**Comment by bebbo** [comment]
>  make -f makefile.os3  misc.o

it dislikes:
        `REG(a1, char ch))`

**Comment by bebbo** [comment]
once the error message is fixed, it prints:
```
misc.c:287:2: error: a1 register specified for 'ch' isn't suitable for data type
  REG(a1, char ch))
  ^~~
```

**Comment by mheyer32** [comment]
Thumbs up! I'll fix that. I would also need to check it there's more places like this.
Any way I could have seen that error message? Or had it been swallowed somehow?

**Comment by bebbo** [comment]
the error message was mal formatted... which raised that funny message

**Comment by bebbo** [comment]
see 0d7bc21e3ca9072515cfa92864251c5847ecc118

**Comment by bebbo** [comment]
and there is something stupid left, that's why scummvm is still failing...

**Comment by mheyer32** [comment]
DOpus compiles again (I uploaded the fix), but still exhibits strange behaviors

![image](https://user-images.githubusercontent.com/33539855/63217929-f0c4c200-c103-11e9-8ce6-601cb323e1c3.png)
(Lister Icons get cleared??)
![image](https://user-images.githubusercontent.com/33539855/63217934-105bea80-c104-11e9-8bee-2ab8bdfd0dea.png)
(Text reader producing garbage)

**Comment by mheyer32** [comment]
Is this what you're referring to:

```
    C++      engines/scumm/imuse_digi/dimuse_music.o
(insn 301 742 302 41 (set (reg:HI 1 d1 [233])
        (mem/u/c:HI (plus:SI (mult:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                            (const_int 44 [0x2c])) [140 %sfp+-4 S4 A16])
                    (const_int 2 [0x2]))
                (label_ref:SI 303)) [0  S2 A16])) engines/scumm/script_v5.cpp:2328 42 {*m68k.md:1047}
     (expr_list:REG_EQUIV (mem/u/c:HI (plus:SI (mult:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                            (const_int 44 [0x2c])) [140 %sfp+-4 S4 A16])
                    (const_int 2 [0x2]))
                (label_ref:SI 303)) [0  S2 A16])
        (insn_list:REG_LABEL_OPERAND 303 (expr_list:REG_EQUAL (mem/u/c:HI (plus:SI (ashift:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                                    (const_int 44 [0x2c])) [140 %sfp+-4 S4 A16])
                            (const_int 1 [0x1]))
                        (label_ref:SI 303)) [0  S2 A16])
                (nil)))))
engines/scumm/script_v5.cpp: In member function 'void Scumm::ScummEngine_v5::o5_verbOps()':
engines/scumm/script_v5.cpp:2432:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 301 742 302 41 (set (reg:HI 1 d1 [233])
        (mem/u/c:HI (plus:SI (mult:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                            (const_int 44 [0x2c])) [140 %sfp+-4 S4 A16])
                    (const_int 2 [0x2]))
                (label_ref:SI 303)) [0  S2 A16])) engines/scumm/script_v5.cpp:2328 42 {*m68k.md:1047}
     (expr_list:REG_EQUIV (mem/u/c:HI (plus:SI (mult:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                            (const_int 44 [0x2c])) [140 %sfp+-4 S4 A16])
                    (const_int 2 [0x2]))
                (label_ref:SI 303)) [0  S2 A16])
        (insn_list:REG_LABEL_OPERAND 303 (expr_list:REG_EQUAL (mem/u/c:HI (plus:SI (ashift:SI (mem/c:SI (plus:SI (reg/f:SI 15 sp)
                                    (const_int 44 [0x2c])) [140 %sfp+-4 S4 A16])
                            (const_int 1 [0x1]))
                        (label_ref:SI 303)) [0  S2 A16])
                (nil)))))
engines/scumm/script_v5.cpp:2432:1: internal compiler error: in extract_constrain_insn, at recog.c:2199
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile.common:123: recipe for target 'engines/scumm/script_v5.o' failed
```

**Comment by mheyer32** [comment]
```
matze@osboxes:~/scummvm-amigaos3$ make amigaos3dist 
    C++      engines/scumm/players/player_sid.o
engines/scumm/players/player_sid.cpp: In member function 'void Scumm::Player_SID::update()':
engines/scumm/players/player_sid.cpp:474:21: warning: array subscript is above array bounds [-Warray-bounds]
    attackReg[channel] = ptr1[y];
    ~~~~~~~~~~~~~~~~~^
engines/scumm/players/player_sid.cpp:476:22: warning: array subscript is above array bounds [-Warray-bounds]
    sustainReg[channel] = ptr1[y];
    ~~~~~~~~~~~~~~~~~~^
/tmp/ccpMI9NI.s: Assembler messages:
/tmp/ccpMI9NI.s:20137: Error: syntax error -- statement `move.w ([__ZN5ScummL19SONG_CHANNEL_OFFSETE,d0.l*4],a2.l*4),d1' ignored
Makefile.common:123: recipe for target 'engines/scumm/players/player_sid.o' failed
make: *** [engines/scumm/players/player_sid.o] Error 1

```

**Comment by bebbo** [comment]
which version? what options?

**Comment by mheyer32** [comment]
`./configure --host=m68k-amigaos --disable-all-engines --enable-engine=scumm,scumm_7-8,sci,lol --disable-mt32emu --enable-release --enable-optimizations  --disable-hq-scalers --with-amiga-prefix=/media/sf_Amiga/ScummVM --enable-c++11`

Happens with the updates you submitted to Top-of-Tree  gcc-6-branch you submitted an hour ago.

If you want to see it fail faster, take out -flto  (change the configure script)

**Comment by bebbo** [comment]
ok - that's better now - but scummvm isn't working

**Comment by mheyer32** [comment]
Today: 

```
    C++      graphics/managed_surface.o
m68k-amigaos-g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile.common:123: recipe for target 'graphics/managed_surface.o' failed
make: *** [graphics/managed_surface.o] Error 4
```
 
:-(

**Comment by mheyer32** [comment]
The latest compiler fixes brought the SCI games in ScummVM back to life (woohoo!). Also, it looks like the DOpus text reader does not produce garbage anymore.

There's still the issue in DOpus with the layouting of the listers going haywire (see screeshot above where the lister toolbar gets cleared out)

**Comment by bebbo** [comment]
sorry, I don't have the time to debug dopus too - scummvm is some fun at least, playint space quest again^^

**Comment by mheyer32** [comment]
Fair enough. This bug is already too fuzzy and the most pressing issues have been fixed. 
I'll close it and open another one, as soon as I have some more insight on whats going wrong with DOpus .
I'm fairly certain, though, that it is a compiler issue :-)

**Comment by bebbo** [comment]
> I'm fairly certain, though, that it is a compiler issue :-)

That's maybe true (there was also a bug in WinUAE...) - and it does alter the process to find the cause:

To find the cause, a way is needed to create a working version. This may be an older gcc version or specific gcc options. Then the journey may start again.

**Comment by mheyer32** [comment]
"That's maybe true (there was also a bug in WinUAE...) "

Can you elaborate? I'm using 4.2.1. Is that bug fixed in this version? Would be a shame if I was testing with the broken version all the time. Though, I can say that I still have a working binary of DOpus compiled with an earlier version of the compiler that works.

**Comment by bebbo** [comment]
That mentioned bug https://github.com/tonioni/WinUAE/issues/150 was fixed in 4.2.1.

Do you have a rough time stamp of that working dopus build?

**Comment by mheyer32** [comment]
30th of July is the date on the executable. 
It does not have layout issues in the listers, but the text reader is already broken in there (you fixed that particular issue just recently)

I'll bisect through the -fbbb options, when I have some time.

**Comment by bebbo** [comment]
> I'll bisect through the -fbbb options, when I have some time.

bisect is your friend - I also do this with *.o files from working/non-working versions to narrow...
