### ISSUE TITLE
Broken asm with -O1 and >68040

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/gcc#112]
Hello, have a look at this piece of code:
```
extern char **tab;

int f(int x) {
	return *tab[x]=='?';
}
````
With -O1 and -m68030 -fomit-frame pointer I got:
```
_f:
        move.l (4,sp),d0
        move.l ([_tab],d0.l*4),a0
        move.b (a0),d0
        cmp.b #63,d0
        seq d0
        neg.b d0
        and.l #255,d0
        rts
```
which is okay.

But with -m68040, -m68060 and -m68080 I got this which is broken:
```
_f:
        move.l (4,sp),a0
        add.l a0,a0                  <== here
        move.l ([_tab,a0],a0.l),a0   <= and there!
        cmp.b #63,(a0)
        seq d0
        neg.b d0
        and.l #255,d0
        rts
```
(see https://franke.ms/cex/z/RmCP2X)

**Comment by bebbo** [comment]
why broken? The code is still valid - and -O1 may be less optimal than -O2

**Comment by Samuel-DEVULDER** [comment]
It is broken because ([XXX,A0],A0) isn't the same as ([XXX],A0*2). The first one does  (*(XXX+A0) + A0) in place of (*XXX + A0*2) (assuming int A0; int **XXX;)

Why not use the same code as for 68030 ? or use A0.l*4 as index (provided this is a legal EA.)

**Comment by Samuel-DEVULDER** [comment]
Also notice that
```
cmp.b #63,(a0)
        seq d0
        neg.b d0
        and.l #255,d0
```
can be optimized as
```
       moveq #0,d0
        cmp.b #63,(a0)
        seq d0
        neg.b d0
```
on 030 (and others).

**Comment by bebbo** [comment]
> 
> 
> Also notice that
> 
> ```
> cmp.b #63,(a0)
>         seq d0
>         neg.b d0
>         and.l #255,d0
> ```
> 
> can be optimized as
> 
> ```
>        moveq #0,d0
>         cmp.b #63,(a0)
>         seq d0
>         neg.b d0
> ```
> 
> on 030 (and others).

what about
```
  moveq #0,d0
  cmp.b #63,(a0)
  sne d0
```
... asks the noob...

**Comment by Samuel-DEVULDER** [comment]
:) neg.b is not not.b  :) :) :)

Unfortunately C defines true as 1, not 255. Therefore there always a neg.b lying around such code.

**Comment by bebbo** [comment]
see 0ad8f678fb33cfa77b8fc3b35552baf8156825f2

**Comment by Samuel-DEVULDER** [comment]
I think this is wise choice. Thanks. CEX isn't updated yet I presume.

**Comment by bebbo** [comment]
Double indirect is on again - I can't live without it. And the generated code is correct now.

Please test

**Comment by Samuel-DEVULDER** [comment]
Testing https://franke.ms/cex/z/RmCP2X looks okay. 
```
_f:
        move.l _tab,a0
        move.l (4,sp),d0
        cmp.b #63,([a0,d0.l*4])
        seq d0
        extb.l d0
        neg.l d0
        rts
```
Thanks Bebbo!
