### ISSUE TITLE
Cannot compile source file with cpu over m68030

### ISSUE THREAD

**Issue by arczi84** [bebbo/gcc#114]
> $ make amigaos3dist -j4
> fatal: No names found, cannot describe anything.
>     C++      engines/scumm/gfx.o
> engines/scumm/gfx.cpp: In member function 'virtual bool Scumm::GdiV1::drawStrip(byte*, Scumm::VirtScreen*, int, int, int, int, int, const byte*)':
> engines/scumm/gfx.cpp:1944:1: error: insn does not satisfy its constraints:
>  }
>  ^
> (insn 428 860 861 14 (set (reg:SI 9 a1)
>         (plus:SI (plus:SI (reg:SI 9 a1)
>                 (mem/c:SI (plus:SI (reg/f:SI 15 sp)
>                         (const_int 52 [0x34])) [137 %sfp+-20 S4 A16]))
>             (reg:SI 13 a5 [orig:349 _602 ] [349]))) 466 {*lea}
>      (nil))
> engines/scumm/gfx.cpp:1944:1: internal compiler error: in extract_constrain_insn, at recog.c:2196
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://gcc.gnu.org/bugs.html> for instructions.
> make: *** [Makefile.common:124: engines/scumm/gfx.o] Error 1

Source code  https://github.com/mheyer32/scummvm-amigaos3

gcc version 6.5.0b 190720232624 (GCC)

**Comment by bebbo** [comment]
scummvm compiles again, but it's not working properly here. Any hints are welcome!

**Comment by mheyer32** [comment]
Still fails to compile for me:

```
    LINK     scummvm
(insn 42 41 75 6 (set (mem/f:SI (plus:SI (reg:SI 4 d4 [ D.11279 ])
                (const_int 4 [0x4])) [41 _22->_next+0 S4 A16])
        (reg:SI 5 d5 [orig:38 D.11279+4 ] [38])) ./common/list.h:238 39 {*movsi_m68k2}
     (nil))
common/coroutines.cpp: In member function 'closeEvent':
common/coroutines.cpp:703:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 42 41 75 6 (set (mem/f:SI (plus:SI (reg:SI 4 d4 [ D.11279 ])
                (const_int 4 [0x4])) [41 _22->_next+0 S4 A16])
        (reg:SI 5 d5 [orig:38 D.11279+4 ] [38])) ./common/list.h:238 39 {*movsi_m68k2}
     (nil))
common/coroutines.cpp:703:1: internal compiler error: in extract_constrain_insn, at recog.c:2199
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: m68k-amigaos-g++ returned 1 exit status
compilation terminated.
collect2: fatal error: lto-wrapper returned 1 exit status
compilation terminated.
Makefile.common:92: recipe for target 'scummvm' failed
make: *** [scummvm] Error 1

```
With ScummVM configured as:

`./configure --host=m68k-amigaos --disable-all-engines --enable-engine=scumm,scumm_7-8,sci,lol --disable-mt32emu --enable-debug --disable-optimizations  --disable-hq-scalers --with-amiga-prefix=/media/sf_Amiga/ScummVM --enable-c++11`

**Comment by mheyer32** [comment]
Something in the latest gcc patches has fixed the build issue. Was that intended? :-)

**Comment by bebbo** [comment]
... still trying to make it work proper...
... scummvm compiles but it's not ok.

**Comment by bebbo** [comment]
> 
> 
> Something in the latest gcc patches has fixed the build issue. Was that intended? :-)

the purpose of commits is to break more than it fixes...
