### ISSUE TITLE
Bad ABI with -mretfp0 when -O auto-substitutes floor() with floorf()

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/gcc#119]
Consider that C code (https://franke.ms/cex/z/ALQUY1):
```
extern __stdargs double floor (double); 
extern __stdargs float floorf (float);

extern float *pr_globals;
void PF_floor (void)
{
 (pr_globals[1]) = (float)floor((pr_globals[4]));
}

```
When compiled with: `-O -m68040 `, one gets:
```
#NO_APP
_PF_floor:
        move.l a5,-(sp)
        move.l sp,a5
        move.l a2,-(sp)
        move.l _pr_globals,a2
        move.l (16,a2),-(sp)
        jsr _floorf
        move.l d0,(4,a2) <======= (1)
        move.l (-4,a5),a2
        unlk a5
        rts
```

One can notice that floor(double) is replaced by floorf(float). Why not... this is optimization.

But when one adds -mretfp0 (https://franke.ms/cex/z/qdXm5y) one gets:
```
#NO_APP
_PF_floor:
        move.l a5,-(sp)
        move.l sp,a5
        move.l a2,-(sp)
        move.l _pr_globals,a2
        move.l (16,a2),-(sp)
        jsr _floorf
        fmove.s fp0,(4,a2) <====== (2)
        move.l (-4,a5),a2
        unlk a5
        rts
```

The line (2) is wrong since floorf is declared as __stdargs, hence returning value into d0 (and d1 for doubles).

If -O is removed, then floor() isn't substituted by floorf() and the __stdargs is honored. At first sight it looks like the substituion didn't consider the __stdargs. This might have impacts on other cases there auto substitution takes places.

**Comment by bebbo** [comment]
I think -mretfp0 is only safe if used together with -fno-builtin.

**Comment by Samuel-DEVULDER** [comment]
Oh! Good to know. with -fno-builtin the code is as expected. 

Thanx.  Shall I close this issue?

**Comment by bebbo** [comment]
> Oh! Good to know. with -fno-builtin the code is as expected.
> 
> Thanx. Shall I close this issue?

please hold the line... I'm testing a patch

**Comment by bebbo** [comment]
if the test passes the tests, it's live in ~ 1 hour from now

**Comment by bebbo** [comment]
you may preview it at https://franke.ms/cex/z/qdXm5y

**Comment by Samuel-DEVULDER** [comment]
Oh! It looks very promissing :)

**Comment by bebbo** [comment]
please test

**Comment by Samuel-DEVULDER** [comment]
I have built a new version of ami-gcc and compiled by "big" project with -mregfp0 without issue (the produced exe run fines). For me, I consider this issue fixed. Close?

**Comment by bebbo** [comment]
thanks for reporting and testing
