### ISSUE TITLE
-O0 turns inline functions into missing symbols

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#12]
Compiling the following code with -O0 will yield 

test_fixed.o(.text+0x38): undefined reference to `testFunction'
collect2: error: ld returned 1 exit status
Makefile:226: recipe for target 'test_fixed' failed
make: *** [test_fixed] Error 1

Compiling with optimizations turned on successfully links the code.

```
#include <stdio.h>

inline void testFunction(void)
{
    printf("Inlined!\n");
}

int main(void)
{
    testFunction();
}

```

**Comment by bebbo** [comment]
That behaviour is correct.

In your case `static inline` is mandatory.

**Comment by mheyer32** [comment]
Thanks! Probably a C idiosyncrasy. I mainly work on C++ :-)
