### ISSUE TITLE
DOpus5  issues

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#123]
I am still on the hunt for various issues in DOpus that crept into the compiler sometime this year.
I think this issue is not caused by any `-fbbb`  optimization, though it is dependent on -O. In particular `-Os` and `-O3` seem to be affected. The symptoms vary. With -Os the lister formatting is off, clearing regions of the lister that shouldn't. With some -O settings, sometimes the strings (containing filenames, dates, file size etc) in lister items are corrupted like shown in screenshots below.

I was able to catch an Enforcer hit and trace it back to the source and I think I found a compiler bug there.

Consider this code 
https://github.com/mheyer32/dopus5allamigas/blob/master/source/Program/lister_show.c#L256

```
	if (!(lister->more_flags&LISTERF_PROP_FONT))
	{
		// Convert x coordinates to characters
		draw_offset=(draw_offset+buffer->buf_HorizOffset)/lister->text_area.rast.TxWidth;
		draw_width=draw_width/lister->text_area.rast.TxWidth;
	}
```

Gets translated into below assembly:

```
	if (!(lister->more_flags&LISTERF_PROP_FONT))
   42150:	082a 0000 1291 	btst #0,4753(a2)
   42156:	662a           	bne.s 42182 <lister_display_dir+0x4fe>

		draw_offset=(draw_offset+buffer->buf_HorizOffset)/lister->text_area.rast.TxWidth;
   42158:	4280           	clr.l d0
   4215a:	302a 01f6      	move.w 502(a2),d0
   4215e:	322f 002e      	move.w 46(sp),d1
   42162:	48c1           	ext.l d1
   42164:	2041           	movea.l d1,a0       <<<<<<<<<<

   42166:	d1e8 03ce      	adda.l 974(a0),a0  <<<< we just sign-extended "draw_offset" and now use it as an address????

   4216a:	2208           	move.l a0,d1
   4216c:	4c40 1801      	divsl.l d0,d1,d1
   42170:	3f41 002e      	move.w d1,46(sp)
		draw_width=draw_width/lister->text_area.rast.TxWidth;
   42174:	322f 0034      	move.w 52(sp),d1
   42178:	48c1           	ext.l d1
   4217a:	4c40 1801      	divsl.l d0,d1,d1

   4217e:	3f41 0034      	move.w d1,52(sp)

```
To replicate my setup, change 
https://github.com/mheyer32/dopus5allamigas/blob/master/source/makefile.common#L11

```

ifeq ($(debug),no)
	OPTIMIZE := -O3 -fomit-frame-pointer
	DEBUGSYM := -g -ggdb
	DEBUG := -DNDEBUG
	#deferred evalution of $(TARGET)
	#STRIP = m68k-amigaos-strip  --remove-section=.comment $(TARGET)
	STRIP :=
#	LIBS += -ldebug
else
```

Build DOpus via
`make os3 release debug=no -j8
`

****
![image](https://user-images.githubusercontent.com/33539855/67105187-2413e380-f17d-11e9-94a3-4e8138aa5e13.png)
![image](https://user-images.githubusercontent.com/33539855/67105411-984e8700-f17d-11e9-92bb-1686120c95f5.png)

**Comment by mheyer32** [comment]
With -Os, the Enforcer hit above does not appear, but graphical corruption shows up.
It seems to affect mainly the text input fields. As if the top border gets not calculated correctly and thus, clearing the text field clears the whole window above it:

![image](https://user-images.githubusercontent.com/33539855/67107355-2c6e1d80-f181-11e9-978d-6fd6cecb0843.png)

**Comment by bebbo** [comment]
you forgot to add `-m68020`...
```
m68k-objdump -m68020 -d ...
```
yields
```
    4da:       082a 0000 1291  btst #0,4753(a2)
     4e0:       662e            bne.s 510 _lister_display_dir+0x510
     4e2:       4280            clr.l d0
     4e4:       302a 01f6       move.w 502(a2),d0
     4e8:       322f 0032       move.w 50(sp),d1
     4ec:       3041            movea.w d1,a0
     4ee:       286f 003e       movea.l 62(sp),a4
     4f2:       49f4 8925 03ce  lea ([974,a4],a0.l,0),a4
     4f8:       220c            move.l a4,d1
     4fa:       4c40 1801       divsl.l d0,d1,d1
```
which is identical to the source
```
	btst #0,(4753,a2)
	jne .L36
	clr.l d0
	move.w (502,a2),d0
	move.w (50,sp),d1
	move.w d1,a0
	move.l (62,sp),a4
	lea ([974,a4],a0.l),a4
	move.l a4,d1
	divs.l d0,d1
```

**Comment by mheyer32** [comment]
The way I produced the disassembly is via:
` m68k-amigaos-objdump -m68020-60 -S -d -C ./bin.os3/DirectoryOpus > DirectoryOpus.asm`

Is this incorrect? I did not get an error back from objdump hinting at a wrong parameter

**Comment by bebbo** [comment]
these options are ok and do produce the same output.

Anyway my code differs - I only compiled the one source file
```
m68k-amigaos-gcc Program/lister_show.c  -m68020-60 -fshort-enums -D__amigaos3__ -D__USE_SYSBASE -D__NO_NET_API -DUSE_64BIT -DCOMPDATE=18.10.2019 -DNDEBUG  -fomit-frame-pointer  -noixemul -I./../ -Iinit/../ -I/home/xy/amiga-stuff/dopus5allamigas/source -I/home/xy/amiga-stuff/dopus5allamigas/source/Include  -Wall -Wno-pointer-sign -Wno-attributes -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -c -O3 -o d3.o
```
or with -S to create a .s

**Comment by bebbo** [comment]
`gcc version 6.5.0b 191008152003 (GCC)`

**Comment by mheyer32** [comment]
same here: `gcc version 6.5.0b 191008152003 (GCC)`

Could LTO be involved?
I just noticed that I have  -flto removed from the OPTIONS for quicker turnaround times

`OPTIONS  := -m68020-60 -fshort-enums -D__amigaos3__ -D__USE_SYSBASE -D__NO_NET_API -DUSE_64BIT -DCOMPDATE=$(NEWDATE)`

Does the linking stage transform the code in any way, when no LTO is enabled?

**Comment by bebbo** [comment]
what is your asm code if you apply my command line?

there might be something wrong at linking time, but that's not related to `-flto`. Maybe some reloc offset is wrong...

**Comment by mheyer32** [comment]
```
m68k-amigaos-gcc Program/lister_show.c  -m68020-60 -fshort-enums -D__amigaos3__ -D__USE_SYSBASE -D__NO_NET_API -DUSE_64BIT -DCOMPDATE=18.10.2019 -DNDEBUG  -fomit-frame-pointer  -noixemul -I./../ -Iinit/../ -I/home/matze/dopus5allamigas/source -I/home/matze/dopus5allamigas/source/Include  -Wall -Wno-pointer-sign -Wno-attributes -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -c -O3 -o d3.o -g -ggdb

m68k-amigaos-objdump -m68020 -S -d -C ./d3.o > lister_show.asm
```

yields:

```

if (!(lister->more_flags&LISTERF_PROP_FONT))
     4cc:	082a 0000 1291 	btst #0,4753(a2)
     4d2:	662a           	bne.s 4fe <lister_display_dir+0x4fe>
		draw_offset=(draw_offset+buffer->buf_HorizOffset)/lister->text_area.rast.TxWidth;
     4d4:	4280           	clr.l d0
     4d6:	302a 01f6      	move.w 502(a2),d0
     4da:	322f 002e      	move.w 46(sp),d1
     4de:	48c1           	ext.l d1
     4e0:	2041           	movea.l d1,a0
     4e2:	d1e8 03ce      	adda.l 974(a0),a0
     4e6:	2208           	move.l a0,d1
     4e8:	4c40 1801      	divsl.l d0,d1,d1
     4ec:	3f41 002e      	move.w d1,46(sp)
		draw_width=draw_width/lister->text_area.rast.TxWidth;
     4f0:	322f 0034      	move.w 52(sp),d1
     4f4:	48c1           	ext.l d1
     4f6:	4c40 1801      	divsl.l d0,d1,d1
     4fa:	3f41 0034      	move.w d1,52(sp)

```

**Comment by bebbo** [comment]
does it change if you add `-fbbb=-` ?
how does that part look in assembly? `-S` instead of `-c` and `./d3.s` instead of `./d3.o`

**Comment by mheyer32** [comment]
Interstingly with -fbbb=- added to the commandline it becomes this:

```
	if (!(lister->more_flags&LISTERF_PROP_FONT))
     4e6:	082a 0000 1291 	btst #0,4753(a2)
     4ec:	662c           	bne.s 51a <lister_display_dir+0x51a>
		draw_offset=(draw_offset+buffer->buf_HorizOffset)/lister->text_area.rast.TxWidth;
     4ee:	4280           	clr.l d0
     4f0:	302a 01f6      	move.w 502(a2),d0
     4f4:	382f 002e      	move.w 46(sp),d4
     4f8:	48c4           	ext.l d4
     4fa:	2844           	movea.l d4,a4
     4fc:	49f4 c925 03ce 	lea ([974,a4],a4.l,0),a4       <<<<< still looks odd
     502:	220c           	move.l a4,d1
     504:	4c40 1801      	divsl.l d0,d1,d1
     508:	3f41 002e      	move.w d1,46(sp)
		draw_width=draw_width/lister->text_area.rast.TxWidth;
     50c:	322f 0034      	move.w 52(sp),d1
     510:	48c1           	ext.l d1
     512:	4c40 1801      	divsl.l d0,d1,d1
     516:	3f41 0034      	move.w d1,52(sp)
```

**Comment by mheyer32** [comment]
-S instead of -c (keeping -fbbb=-) produced this:
```
.L33:
	.loc 1 253 0
	.stabd	68,0,253
	add.w (428,a2),d7
	add.w (26,a5),d7
	move.w d7,(44,sp)
	.loc 1 256 0
	.stabd	68,0,256
	btst #0,(4753,a2)
	jne .L36
	.loc 1 259 0
	.stabd	68,0,259
	clr.l d0
	move.w (502,a2),d0
	move.w (46,sp),d4
	ext.l d4
	move.l d4,a4
	lea ([974,a4],a4.l),a4
	move.l a4,d1
	divs.l d0,d1
	move.w d1,(46,sp)
	.loc 1 260 0
	.stabd	68,0,260
	move.w (52,sp),d1
	ext.l d1
	divs.l d0,d1
	move.w d1,(52,sp)
```

**Comment by mheyer32** [comment]
When recompiling the toolchain, I tend to nuke the build first via:
`make clean clean-prefix -j8 PREFIX=/home/matze/amigatoolchain/amiga-gcc-out`
then rebuild
`make all all-sdk -j8 PREFIX=/home/matze/amigatoolchain/amiga-gcc-out`

Is there any way some old leftover throws in a monkey wrench?

**Comment by bebbo** [comment]
which os are you using? maybe it's a 32/64bit issue?

**Comment by bebbo** [comment]
there is something messed up in reload... the commit changes this - please have a look

**Comment by mheyer32** [comment]
I'm on a Ubuntu 16.04 64bit VM. Going to try out top of tree GCC now

**Comment by mheyer32** [comment]
The code produced in lister_show.c is now working, I don't see the enforcer hit with -O3 anymore.

-Os does not work yet, but that may be another issue that requires more debugging:

![image](https://user-images.githubusercontent.com/33539855/67150227-a7126800-f269-11e9-94a4-0c7e64a154e4.png)

**Comment by bebbo** [comment]
> 
> 
> I'm on a Ubuntu 16.04 64bit VM. Going to try out top of tree GCC now.
> 
> EDIT: Have you been able to repro the issue in meantime?

yes, I could reproduce the issue - I had already some changes I didn't consider relevant...
... which do mitigate this issue with -O3.
But I still have to find the real cause... for the bogus reload.

**Comment by mheyer32** [comment]
The lister corruption as shown above starts at -O2 (or -Os), regardless of -fbbb=-

**Comment by mheyer32** [comment]
Found one more issue:

https://github.com/mheyer32/dopus5allamigas/blob/master/source/Program/lister_show.c#L370

`Text(&lister->text_area.rast,lister->display_buf+offset,width);`

```
		Text(&lister->text_area.rast,lister->display_buf+offset,width);
     8ca:	2c79 0000 0000 	movea.l 0 <lister_display_dir>,a6
     8d0:	224c           	movea.l a4,a1
     8d2:	2a43           	movea.l d3,a5         <<<<<<<<
     8d4:	41f5 3000      	lea (0,a5,d3.w),a0    <<<<<<<<< Hu? isn't that supposed to calculate lister->display_buf+offset ?
     8d8:	3004           	move.w d4,d0
     8da:	48c0           	ext.l d0
     8dc:	4eae ffc4      	jsr -60(a6)
```

**Comment by bebbo** [comment]
if the build passes the tests...:
```
        move.l a3,a1
        move.l (58,sp),d0
        move.l d3,a5
        lea (a5,d0.w),a0
        move.w d4,d0
        ext.l d0
        jsr a6@(-0x3c:W)
```

**Comment by mheyer32** [comment]
The visual issues with DOpus are gone. The DOpus text reader works again. I don't get Enforcer hits. So for now, all is good :-) 

Thanks! Closing.
