### ISSUE TITLE
error when linking

### ISSUE THREAD

**Issue by arczi84** [bebbo/gcc#124]
/d/amiga-gcc2/bin/m68k-amigaos-ld: internal error /c/msys64/home/test/amiga-gcc/projects/binutils/ld/ldlang.c 6868

I get this after compiling NetSurf with gcc6 and linking, some libs are compiled with gcc 3.4.0 clib2.
Maybe that's why ?

gcc version 6.5.0b 191023121710 (GCC)

**Comment by bebbo** [comment]
I could also only guess...
... you might add a statement to /c/msys64/home/test/amiga-gcc/projects/binutils/ld/ldlang.c just in front of the ASSERT at line 6868:
```
  fprintf(stderr, "%s\n", entry->the_bfd->filename);
```

**Comment by arczi84** [comment]
I have commented line 6868 but error is same , hmmm.

**Comment by bebbo** [comment]
you should get some output, and the last printed file is the one causing this error.
Which one is it?

**Comment by arczi84** [comment]
I'll try again with your line. It's compiling 1h :S

**Comment by bebbo** [comment]
> 
> 
> I'll try again with your line. It's compiling 1h :S

after patching that file a `make binutils` is sufficient

**Comment by arczi84** [comment]
https://hatebin.com/llliikosjr

pon., 11 lis 2019 o 15:12 bebbo <notifications@github.com> napisał(a):

**Comment by arczi84** [comment]
Yes that's it, do you think it's safe to mix libnix and clib2 static librariers?

**Comment by bebbo** [comment]
as soon as a library uses stdio or other specific stuff, mixing does not work.

**Comment by arczi84** [comment]
It looks like __clib2__ is not defined when compiling with mcrt=clib2 ?
