### ISSUE TITLE
ScummVM error if fbbb is on.

### ISSUE THREAD

**Issue by arczi84** [bebbo/gcc#129]
item variable will be too high if fbbb is on -> error.

https://github.com/mheyer32/scummvm-amigaos3/blob/29b08bf2c4e34f8b7b9a621474ca5841a45f07a3/engines/agos/items.cpp#L385

Happens with Simon1 (OCS/Amiga) demo.

**Comment by bebbo** [comment]
assignments with `.b` ot `.w` must mark the destination register as used.

here the high word is trashed: 
```
 move.l a2,d0
 jeq .L875
 move.w (4,a2),d0
```

with the fix a different reg is used, or the `tst` is kept:
```
	tst.l a2
	jeq .L875
	move.w (4,a2),d0
```

**Comment by mheyer32** [comment]
@arczi84 you can help Bebbo by bisecting the individual -fbbb option that causes the issue.

m68k-amigaos-gcc --target prints all individual options:

```
  -fbbb=                      Enable Bebbo's optimizations.
                              +    enable all optimizations (default)
                              a    commute add move instructions
                              b    use register for base addresses
                              c    convert load const and compare into a sub
                              e    eliminate dead assignments + redundant loads
                              f    shrink stack frame
                              i    use post increment on addresses
                              l    remove single used lea if possible
                              n    pipeline instructions
                              m    merge add and move statements
                              p    propagate move assignment pairs out of loops
                              r    register renaming to maybe save registers
                              s    a strcpy optimization
                              z    final pass with simple substitutions
                              v    be verbose
                              V    be very verbose
                              x    dump insns
 Default: -fbbb=+ which yields -fbbb=abcefilmnprsz
```

So start with 
```
#mnprsz
-fbbb=abcefil 
```

if the issue goes away, you know that it lies with any of the  `mnprsz` options.  Replace it to `-fbbb=mnprsz` and continue.
Otherwise, split 'abcefil' into half and continue bisecting until the single offending optimization is isolated.

To speed your turnaround time up, I suggest removing `-flto` from the options :-)

**Comment by bebbo** [comment]
please test

**Comment by arczi84** [comment]
> @arczi84 you can help Bebbo by bisecting the individual -fbbb option that causes the issue.
> 
> m68k-amigaos-gcc --target prints all individual options:
> 
> ```
>   -fbbb=                      Enable Bebbo's optimizations.
>                               +    enable all optimizations (default)
>                               a    commute add move instructions
>                               b    use register for base addresses
>                               c    convert load const and compare into a sub
>                               e    eliminate dead assignments + redundant loads
>                               f    shrink stack frame
>                               i    use post increment on addresses
>                               l    remove single used lea if possible
>                               n    pipeline instructions
>                               m    merge add and move statements
>                               p    propagate move assignment pairs out of loops
>                               r    register renaming to maybe save registers
>                               s    a strcpy optimization
>                               z    final pass with simple substitutions
>                               v    be verbose
>                               V    be very verbose
>                               x    dump insns
>  Default: -fbbb=+ which yields -fbbb=abcefilmnprsz
> ```
> 
> So start with
> 
> ```
> #mnprsz
> -fbbb=abcefil 
> ```
> 
> if the issue goes away, you know that it lies with any of the `mnprsz` options. Replace it to `-fbbb=mnprsz` and continue.
> Otherwise, split 'abcefil' into half and continue bisecting until the single offending optimization is isolated.
> 

Thanks for reply, but I've already done that :P 
We spoke on discord. I've isolated this way all options and found that it was 'z' one.

> To speed your turnaround time up, I suggest removing `-flto` from the options :-)

Already removed because wasn't linking exe file for me.
Some build earlier it worked and haven't noticed longer compile time.

What wonders me is why when adding game instead of folder first file added.
Adding game again with "Edit path" button works good.

**Comment by arczi84** [comment]
@bebbo It is fixed now.
