### ISSUE TITLE
Weirdness when passing string arrays directly to FindToolType

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#131]
Consider this code:
https://github.com/mheyer32/scummvm-amigaos3/pull/4/commits/901a36386d6be94a51ac9a0b4e61de95dc150335

When the tooltype names like "AUDIO_THREAD_PRIORITY" are passed directly to FindToolType, it'll never return the tooltype to be found, as if the string pointer passed down points to some other garbage.

If however, the string gets copied first an then passed into FindToolType (like in above PR), it works?!
I have also tested strdup(), and it works around the issue the same way.

**Comment by bebbo** [comment]
The current macros are causing that issue

**Comment by bebbo** [comment]
Please post the gcc version, command line flags, etc.p.p. needed to reproduce

**Comment by mheyer32** [comment]
Thank you! That fixed it. Closing.
