### ISSUE TITLE
Toolchain internal error on raspberrypi

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#132]
No problem on x86_x64.
Could be 32-bit related?

[error.log](https://github.com/bebbo/gcc/files/5010329/error.log)

**Comment by bebbo** [comment]
Well that's a real gcc error, report it there

**Comment by bebbo** [comment]
Further ideas:
  Use a smaller number with -j

**Comment by alexalkis** [comment]
03:15:57 later you were right. (run it with -j1 :) )
