### ISSUE TITLE
Optimisation regression?

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#134]
I am pretty sure
```
char *mstrcpy(char *dst, char *src) {
    char *ret = dst;
    while((*dst++=*src++))
    {}
    return ret;
}
```

used to generate the ideal move.b (a1)+,(a0)+ but now breaks it to two instructions ( https://franke.ms/cex/z/J7ksts )

Have your rolled back that optimisation or did something else break?

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
Fixed.  Thanks!
