### ISSUE TITLE
Bug with global registers not being updated

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [bebbo/gcc#136]
Consider that small piece of code which uses [global register variables](https://gcc.gnu.org/onlinedocs/gcc/Global-Register-Variables.html):
```
register unsigned long pc asm("d7");
unsigned long foo() 
{
    return ++pc;
}
```
and compile with `-ffixed-d7 -O3` with gcc6.5.0b, then one gets [this ASM](http://franke.ms/cex/z/WGKo6P) which is wrong (d7 not updated):
```
_foo:
        moveq #1,d0
        add.l d7,d0
        rts
```
With -O0, there is a move.l d0,d7 before rts. The final move was probably removed -with -O3 as d7 is considered dead by the end of the function function though it isn't a local reg in that case.

With gcc10, the [ASM is ok](http://franke.ms/cex/z/7cdcaj) (though suboptimal but I know gcc10 is WIP and not available yet) and with gcc2.95.3 it is [ok & optimal](http://franke.ms/cex/z/YacqMd)
```
_foo:
        addql #1,d7
        movel d7,d0
        rts
        nop
```

**Comment by bebbo** [comment]
no feedback

**Comment by Samuel-DEVULDER** [comment]
Yeah, sorry for not telling.. I updated & recompiled on Nov 25th, and that version was fine wrt global regs. 

=> Properly fixed since last year indeed :)
