### ISSUE TITLE
Register A5 cannot be used as register function parameter

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#137]
This was a real headscratcher for me...

Please consider this repro case:
http://franke.ms/cex/z/PqevPv

See how a5 is not loaded with any data before calling the ASM function.

If one changes  `REG(a5, UBYTE *xlate)` to  `REG(a3, UBYTE *xlate)`, it'll work.

The issue showed up in ADoom, in particular when calling a function with lots of register parameters:

```
void c2p_6_020(REG(a2, UBYTE *fBUFFER), REG(a6, PLANEPTR *planes), REG(d0, ULONG signals1), REG(d1, ULONG signals2),
               REG(d4, ULONG signals3), REG(d2, ULONG pixels),  // width*height
               REG(d3, ULONG offset),                           // byte offset into plane
               REG(a1, UBYTE *xlate), REG(a5, struct Task *othertask), REG(a3, UBYTE *chipbuffer));  // 2*width*height
```

Here 'otherTask' would contain garbage, leading to the Blitter C2P code signaling a non-existent task, leading to the game to hang. When I changed the otherTask parameter to d5, the problem went away.

**Comment by bebbo** [comment]
this is a tough one - and I guess it's the reason why the inline macros are using d7 + `exg d7,a5` instead...

**Comment by bebbo** [comment]
My guess was right: In the core of gcc and it's dataflow analysis (df-scan.c) you find this code fragment:
```
      else if (!(TEST_HARD_REG_BIT (elim_reg_set, regno)
		 && (regno == FRAME_POINTER_REGNUM
		     || regno == ARG_POINTER_REGNUM)))
	DF_REF_FLAGS_SET (this_ref, DF_HARD_REG_LIVE);
```
which means that FRAME_POINTER_REGNUM is always considered a hard reg, even if it is not used.

feel free to tweak here and watch the side effects^^

**Comment by mheyer32** [comment]
Is there any chance you could make that behavior dependent on -fomit-framepointer? Also, would it be possible to error out in cases like the one I ran into? I had no indication on what was going on and it took me quite some time to identify the issue. 
I don’t feel competent enough to make a change in the code there. I don’t have the means to test if it doesn’t break anything.

**Comment by bebbo** [comment]
that affects so many locations... maybe someone could, but it's tedious... the simple approach of patching that one location did not work. It's the register assignment stage - known as reload (hell) - which drops that statement.

... you could try `asm("move.l %1,a5", ...)` in front of the call

**Comment by mheyer32** [comment]
Ok, I'll keep that in mind in future and be wary of A5

**Comment by bebbo** [comment]
give it a try^^

**Comment by mheyer32** [comment]
Thanks for your efforts!

Ok, I now see the warning! It is rather non-descript, though.
It doesn't convey if something went right or wrong. Whats worse, though, is that we now get a warning in the one case that might work, while we get no indication in the case when a5 assignment actually gets dropped due to -fno-omit-framepointer.
What I'd like to see is something like

"warning: a5 assignment allowed due to -fomit-framepointer" 
and for the opposite case
"error: a5 assignment interferes with framepointer"

This should make clear what issue (or non-issue) the compiler encountered. The error will make sure that code that is guaranteed to fail will not compile.
It would be great if there was a similar warning/error for a4 assignments with -fbaserel 

I'm not entirely sure about producing the "success warning" always, in case people use -Werror.
It would be great to be able to disable it on purpose via something like -Wno-framepointer-assignment"

**Comment by mheyer32** [comment]
"That nasty warning will hopefully make other people complain about it :-)"

But they will only see it with -fomit-frame-pointer, right?
Doesn't that miss the other case?

**Comment by bebbo** [comment]
if you poke a5 while it is in use, you are lost anyway, aren't you?

directly using registers belongs to the "don't try this at home" category.

**Comment by mheyer32** [comment]
I agree, working with registers directly is running with scissors.
I'm not asking you to fix it if its too delicate.
But having the compiler warn about potential issues is really of value, especially when moving old projects to GCC from other compilers. This will help people by preventing them chasing ghosts bugs.Mind you, in case of ADoom (and the other projects I'm regularly throwing at you) I'm not the original author - there might be usage of A4/A5 that is not immediately obvious.
