### ISSUE TITLE
Internal Compiler Error with ScummVM

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#139]
ScummVM doesn't compile with the SAGA engine.

Configure it like this:

`./configure --host=m68k-amigaos --disable-all-engines --disable-hq-scalers --enable-c++11 --disable-lua --disable-nuked-opl --disable-mt32emu --enable-release --enable-optimizations  --disable-iconv --with-amiga-prefix=/media/sf_Amiga/ScummVM --enable-engine=saga`

and  build via

`make -j8 amigaos3dist
`

results in this error:

```
engines/saga/console.cpp: In member function 'bool Saga::Console::cmdClearGlobalFlag(int, const char**)':
engines/saga/console.cpp:315:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 73 72 39 5 (set (reg:SI 8 a0)
        (plus:SI (reg:SI 8 a0)
            (mem/f:SI (plus:SI (reg:SI 1 d1)
                    (const_int 558 [0x22e])) [33 this_5(D)->_vm+0 S4 A16]))) engines/saga/console.cpp:309 134 {*addsi3_internal}
     (expr_list:REG_EQUIV (plus:SI (mem/f:SI (plus:SI (reg:SI 1 d1)
                    (const_int 558 [0x22e])) [33 this_5(D)->_vm+0 S4 A16])
            (const_int 90 [0x5a]))
        (nil)))
engines/saga/console.cpp:315:1: internal compiler error: in extract_constrain_insn, at recog.c:2199
```

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
Thank you! That was super quick! It compiles now.

But ultimately the game hangs. I suspect the issue to be somewhere else, though. Closing!
