### ISSUE TITLE
Improving asm generation

### ISSUE THREAD

**Issue by arczi84** [bebbo/gcc#140]
Hi, bebbo.
We are working on Sonic game port to Amiga and we noticed that generated asm code is really bad...
By simple tweaking asm we got 10fps more!
Here is comparison between original asm generated with O2,  m68080 and fbbb with our little tweak:

https://www.textcompare.org/index.html?id=601fb8ead316300017a2c11f

As you can see and.l is responsible here for major CPU slowdown. 
Do you think this could be tweaked?

**Comment by bebbo** [comment]
progress: https://franke.ms/cex/z/8xecqW

**Comment by arczi84** [comment]
very nice

**Comment by arczi84** [comment]
There is nothing wrong with using a DATA register as INDEX,
you can use either DATA or ADDRESS reg as INDEX,
both works just the same way.
-
But for LOOP counts its generally always best to use a DATA REGISTER
Only on DATA register you can use DBRA
Only on DATA register you can count down with "free" Flags creation,
if you use an ADDRESS register for the loop count then you need in the work loop 1 extra CMP or TST instruction
this is not good.
In this example
`subq.l #1,a0
        move.l a0,d4
        jne .L51`
Here 3 instructions are used for doing the LOOP operation
`subq for count down`
`move A0,D4` - to create flags  (using a tmp register )
`jne`  - for LOOP
--
this is 3 instructions,  while the same could have been done with 1 DBRA.

**Comment by arczi84** [comment]
--
add.l d4,d4
        add.l d4,d4
--
this code makes no sense for higher CPUs
a shift would be better

**Comment by bebbo** [comment]
I'd guess: all data registers are used inside the loop...

**Comment by arczi84** [comment]
I see you updated precompiled gcc.
LTO still doesn't work.

**Comment by bebbo** [comment]
![grafik](https://user-images.githubusercontent.com/16560863/107340756-6bcf2480-6abe-11eb-8ef8-16653c7eac12.png)
![grafik](https://user-images.githubusercontent.com/16560863/107340796-74275f80-6abe-11eb-9f67-61f2855d4cb6.png)

2 x ADD on 68040 is faster than a single shift

**Comment by bebbo** [comment]
err: it's shift:
![grafik](https://user-images.githubusercontent.com/16560863/107340983-bbadeb80-6abe-11eb-8ef8-5bbcd4356c3f.png)

**Comment by arczi84** [comment]
also lets look at this:

`clr.l d2`
`lea (a4,d2.l),a5`
`lea (9,a3,a5.l),a5`

what does this 3 line do?
D2 is cleared
this means
`lea (a4,d2.l),a5`
is just an idiot form for    `MOVEA.l  A4,A5`
and A5 gets overwritten in the next row
so its useless
`Lea (9,a3,a4.l),a5`
is all what he wanted

this ASM code as it - is silly
Was the related C code also silly?

about the LOOP

look here:

`move.w #100,a1`
`.L6:`
 `       move.l _xScrollOffset,(a3)+`
`        subq.l #1,a1`
`        move.l a1,d4`
`       jne .L6`

the compiler has D4 free and uses it as TMP register in the Loop
this code is very very bad

the Compiler should have done
`move.w #99,D4`
`LOOP`
`move.l whatever,(A3)+`
`dbra d4,LOOP`

**Comment by bebbo** [comment]
> the compiler has D4 free and uses it as TMP register in the Loop
> this code is very very bad
> 
> the Compiler should have done
> `move.w #99,D4`
> `LOOP`
> `move.l whatever,(A3)+`
> `dbra d4,LOOP`

d4 is used as scratch inside the loop:
```        move.b (2,a5),d4
        jeq .L23
        move.w (a2,d4.l*2),(4,a1)
´´´

or what code are you referring to?

The other issue is presumably create during jump optimization, where the expression is duplicated from above and d2 with some value inside. At the copied location d2 is set to zero.
Yes, that code looks silly - but it's not easy to treat.

**Comment by bebbo** [comment]
and the `clr.l d2` is necessary since d2 is used sometimes after the jump:
```
.L15:
	addq.l #1,d2
```

leaves the lea: the lea costs were to cheap, I'll increase these and reduce the shift costs.

**Comment by bebbo** [comment]
please review the latest result

**Comment by arczi84** [comment]
hmm, something is wrong, sonic doesn't behave normally in demo

**Comment by arczi84** [comment]
at leas with Ofast and 68080, 68040 and O2 is ok

**Comment by bebbo** [comment]
LTO is working in Linux.

Could you hunt down the issue by doing a binary search to find at least one source which causes the trouble and then create 4 different asm versions:
1. -fbbb=abcfilmnprsz  (this should work)
2. -fbbb=abcfilmnprsze
3. -fbbb=abcfilmnprsze0
4. -fbbb=abcfilmnprsz0

**Comment by bebbo** [comment]
flto is also working under cygwin...

**Comment by arczi84** [comment]
please don't make it using cygwin again ..
68040  O3:
gcc from 
12.09.2020 - 52.9 fps
today  - 50.6 fps

**Comment by bebbo** [comment]
cygwin was only informative about LTO research - if, then switch to WSL :-) - maybe I write a short guide...

guess I need a  Vampire to test that...

**Comment by arczi84** [comment]
-fbbb=abcfilmnprsz is OK

**Comment by arczi84** [comment]
what concerns me is the loop

`moveq #100,d1`
`.L6:`
  `       `**`
 `       subq.l #1,d1`
`        jne .L6`

this is with -m68000


real good would be

`moveq #100,d1`
`.L6:`
`         ***`
`        dbra.l d1.L6`


GGC 2,9 would also do this

so we see here a big degration using GCC 6.5

even worse is that with CPU higher than 68000

GCC 6.5. will stupidly use an Address pointer as size count register

this is very bad
and much slower
and also bigger code

GCC is totally broken

look at it:

`move.w #100,a1`
`.L6:`
 `       move.l _xScrollOffset,(a3)+`
  `      subq.l #1,a1`
   `     move.l a1,d2`
    `    jne .L6`

**Comment by arczi84** [comment]
I compared exe size with flto and without and they are same so it's not doing anything, on msys2 at least.

**Comment by bebbo** [comment]
on WSL I get:
  with lto: 607020
  without: 566488

**Comment by bebbo** [comment]
just a note for dbra:
* it works with word size only - combined with a `clr.w dx,  subq.l #1,dx, bge .L` you can extend it for long usage. But for 68080 the simple `subq #1,dx bne .L` is preferred, since the insns are fused.
* the constant must be reduced by one to use dba...

**Comment by bebbo** [comment]
please also try the option ` -fno-tree-loop-ivcanon`

**Comment by GunnarVB** [comment]
Hallo Bebbo,

maybe we shall review the LOOP topic real quick:
LOOPS are very often used and for sure its important that a compiler creates good code for them.

The C code for the loop in this example was a simple 1 liner:
The Loop count is constant. #100 iteration in this example.

for (int i = 0; i < PARALLAX_COUNT; ++i) hParallax.tilePos[i] = xScrollOffset;


The 68K family offers many options for coding such loop.

1) DBRA
2) SUBq.l  DN, BCC
3) SUBq.l  (mem),BCC
4) SUBq.l  An, tst.l An, BCC

1) DBRA is the fastest.
4) SUBq.L An is maybe the worst option. 
But GCC 6.5 does pick this for 68020/030/040/060
This is surprising. As its need more register, is much longer in Bytes, and is significantly slower.


Lets quickly look at clock and bytes to understand what drawback this has:

Lets look at 68020 timing

Option1)
                           CLK    BYTE 
   MOVEQ #,Dn        2        2
 LOOP
      DBRA                 6       4
                                ---    ---
                                 8      6
Needed instructions 2
Looptime          2 + N*6 clocks
Length              6 Byte
Register used   1
***********************************************************

Option 2)
                           CLK    BYTE 
   MOVEQ #,Dn        2        2
 LOOP
   subq.l    #1,Dn      2        2
   bcc                        6      2/4
                                ---    ---
                                10      6/8

Needed instructions  3
Looptime          2 + N*8 clocks
Length              6/8 Byte
Register used   1

This option is slower than using DBRA.
This option has same size as DBRA for tiny loop body, and for bigger loops is 2 Byte longer.

**********************************************************************
Option 3) counter on memory.
Has the advantage to not need any register.
So might have some rare usage.
But when registers are available a register based loop is better.


Option 4)
Now lets look at the AN variant which GCC 6.5 prefers

                             CLK BYTE
   MOVE.W  #,An       4       4
LOOP
    SUBQ.l #1,An        2       2
    MOVE.l     An,Dn   2       2     -- To create Flags
    BCC                       6       2/4
                                 ---      ---
                                 14     10/12

Instructions            4
Looptime               4 + N*10
Length                  12 Byte   (when using same distance option as in DBRA, for shorter LOOP 10 byte possible)  
Register usage       2


I think numbers always help to understand the discussion clearer.

Lets understand the Loop version that GCC  prefers to use:
- It needs more register
- it needs more instructions
- Its longer in Bytes
- And its significantly slower.
- It has no advantages at all.
Its clearly the worst possible choice.

Interestingly when compiling for CPU=68000 then GCC will use a better LOOP using DN and not AN.
Only when you compile for 020/030/040/060 then GCC prefers to use the worst possible LOOP.
Maybe you can us understand why GCC prefers to use the AN Loop for those CPUs?

Thanks

**Comment by bebbo** [comment]
please have a look now: http://franke.ms/cex/z/eEY4n7

**Comment by GunnarVB** [comment]
Hallo Bebbo,

its nice that you look into this.

I see that added a new version now
*************************************************************
        lea (400,a0),a3                                               4 4 
.L6:
        move.l _xScrollOffset,(a0)+
        cmp.l a3,a0                                                     2 2 
        jne .L6                                                             6 2/4
****************************************************


Needed instructions 3
Looptime 4 + N*8 clocks
Length    8/10 Byte
Register used 1

We can see that this version is not as good as using DBRA
and its also not as good as using "SUBq.L on DN"

Why does the Compiler not use Subq.L Dn for the Loop?
Subq.l is shorter in bytes and as fast or faster than this code.
The CMP is depending on the previous MOVE update therefore performance will be hurt on 68060.

The DBRA option is clearly the best
SUBQ.L #1,Dn  is second best.

GCC will pick subq.l DN on 68000,
Why does GCC do the same on 020+ ?

**Comment by arczi84** [comment]
With -fno-tree-loop-ivcanon  I get 60.9 fps so the best so far.

**Comment by arczi84** [comment]
Tested newest gcc with 080 , Ofast and Sonic not sick anymore.
Fps rate is better now but still September version is a bit faster.

**Comment by bebbo** [comment]
dbra is used now more often...

**Comment by bebbo** [comment]
```
.L19:
        dbra d2,.L26
        clr.w d2
        subq.l #1,d2
        jcc .L26
```

**Comment by GunnarVB** [comment]
Hallo Bebbo,

Excellent improvement!
Thanks a lot.

**Comment by arczi84** [comment]
61.6 fps, new record :)

**Comment by GunnarVB** [comment]
Hallo Bebbo,

****************************************************
        moveq #99,d3
.L6:
        move.l _xScrollOffset,(a0)+
        dbra d3,.L6
        clr.w d3
        subq.l #1,d3
        jcc .L6
*****************************************

This looks nice but would GCC be able to "SEE" if a constant fits in WORD (below 65536)
and then only just use the DBRA without the out loop?

**Comment by bebbo** [comment]
gcc can't do that - maybe I can hack that in...

**Comment by GunnarVB** [comment]
Is the fix to use DBRA enabled for all CPUs or only for 020?
It would benefit ALL 68K family members.

**Comment by bebbo** [comment]
you can try it already at https://franke.ms/cex/

**Comment by GunnarVB** [comment]
-m68040 -O2 -fomit-frame-pointer
= compile failed

**Comment by bebbo** [comment]
> 
> 
> -m68040 -O2 -fomit-frame-pointer
> = compile failed

Is that the kind of bug report details you'd expect?

**Comment by arczi84** [comment]
He ment that if you set
`-m68040 -O2 -fomit-frame-pointer`
on online compiler https://franke.ms/cex/ ,
compilation will fail.

**Comment by bebbo** [comment]
> 
> 
> He ment that if you set
> `-m68040 -O2 -fomit-frame-pointer`
> on online compiler https://franke.ms/cex/ ,
> compilation will fail.

you could provide a full link by using the compile explorer`s `share` button to copy the link...

... btw: a first wsl2 setup is online: https://franke.ms/amiga/wsl2.wiki

**Comment by GunnarVB** [comment]
>    -m68040 -O2 -fomit-frame-pointer
>   = compile failed
>
>Is that the kind of bug report details you'd expect?

Hi Stefan,
I followed the link you gave us to try the compiler, to see your changes/improvement.
i noticed that changing the CPU to another model resulted in no compile
The only message the online tool gave here was "compile failed"
I agree with you it would be nice if the tool would give more details per default.

**Comment by bebbo** [comment]
click here: 
![grafik](https://user-images.githubusercontent.com/16560863/107761167-3713d500-6d2b-11eb-9d41-c0e8f8a34cb3.png)

**Comment by arczi84** [comment]
> > He ment that if you set
> > `-m68040 -O2 -fomit-frame-pointer`
> > on online compiler https://franke.ms/cex/ ,
> > compilation will fail.
> 
> you could provide a full link by using the compile explorer`s `share` button to copy the link...
> 
> ... btw: a first wsl2 setup is online: https://franke.ms/amiga/wsl2.wiki

Sorry, didn't know about that. When I clicked your link, I got code inside, that we are discussing here...

**Comment by GunnarVB** [comment]
I have the feeling communicating over this webtool is maybe not the most optimal. Also this tool not likes all webbrowsers  (e.g. editing not works for me).  :(
I think this communication adds room for unnecessary misunderstanding
and it would be bad if the misunderstandings result in unneeded tension.
Would talking on Phone, or Chat make for sense to improve communication?

**Comment by bebbo** [comment]
> 
> 
> Hallo Bebbo,
> 
> ```
>     moveq #99,d3
> ```
> 
> .L6:
> move.l _xScrollOffset,(a0)+
> dbra d3,.L6
> clr.w d3
> subq.l #1,d3
> jcc .L6
> 
> This looks nice but would GCC be able to "SEE" if a constant fits in WORD (below 65536)
> and then only just use the DBRA without the out loop?

you could use a `short` variable instead of an `int` --> you'd get the pure `dbra`

**Comment by GunnarVB** [comment]
Hi Stefan

can you make us again a link for the online tool to see the program?


So that we can all share the same code and discuss?


Cheers
Gunnar

Quoting bebbo <notifications@github.com>:

**Comment by arczi84** [comment]
http://franke.ms/cex/z/qqPrzE

**Comment by GunnarVB** [comment]
I notice something else which looks not right:      
Lets look at this code please:
used flags" -m68040 -O2 -fomit-frame-pointer"

C-Code:
                        pixel=*gfxDataPtr++;
                            if (pixel > 0)
                                *frameBufferPtr = activePalette[*gfxDataPtr];
                            ++frameBufferPtr;


Created ASM:
        tst.b (3,a1)                   4 byte
        jeq .L24
        move.b (4,a1),d5         4 byte
        move.w (a3,d5.l*2),(6,a0)
.L24:

I think this ASM is not good as the "literal" translation of the C-Code would be. 
I think literal tranlation should have been 
Created ASM:
        move.b (a1)+,D5            --   2  2
        jeq .L24                   
        move.w (a3,d5.l*2),(6,a0)
.L24:

The code that GCC created is 4 bytes longer, 1 instruction longer, and several clocks slower.
Can this be fixed?
Can you help us understand why GCC prefered the worse code?

**Comment by GunnarVB** [comment]
Hi Stefan,

please ignore the above post.
I made a copy paster error.
I need to get used to the online tool. :)
The bug report above is not correct.


The correct report is this:

The created code looks like this:
.L21:
        move.b (1,a2),d4
        jeq .L22
        move.w (a1,d4.l*2),(2,a0)
.L22:
        move.b (2,a2),d4
        jeq .L23
        move.w (a1,d4.l*2),(4,a0)
.L23:
        move.b (3,a2),d4
        jeq .L24
        move.w (a1,d4.l*2),(6,a0)


.L24:
        move.b (4,a2),d4
        jeq .L25
        move.w (a1,d4.l*2),(8,a0)
        move.b (1,a2),d4
        move.b (2,a2),d4
        move.b (3,a2),d4
        move.b (4,a2),d4
        then ADD

GCC prefers to use (16bitoffset,Ptr) instead using (PTR)++,
This leads to slower and much longer code.
In our example we increase code by 2 Byte per usage (4*2 bytes plus the size for PTR ADD )
I think this means 12 byte more code and 1 extra  instruction in our case.

The (AN)++ address mode does not increase code size.
Can you help GCC to use it?

**Comment by bebbo** [comment]
> 
> 
> http://franke.ms/cex/z/qqPrzE

`typedef char byte;` creates way worse code than `typedef unsigned char byte;`

**Comment by GunnarVB** [comment]
Hi Bebbo, 

I have two more question:

1st) Can we help you in some way?
You mentioned that the GCC cost "database" is not correct.
That GCC does
MOVE.b (A0),D0
MOVE.b 1(A0),D1
MOVE.b 2(A0),D2
instead
MOVE.b (A0)+,D0
MOVE.b (A0)+,D1
MOVE.b (A0)+,D2
--
Seems to give you right.
As the 2nd version is shorter and better.

It there a way to help review this cost database for you and support you?



2nd) I wonder if there is a way to enable some tuned instruction for 68080 CPU.
For example when adding a CONSTANT to a LONG the 68K has the option do use.
ADDq.L   #8,Dn           -- for values below 8
ADDW.L  #16bit,Dn     -- for values up to 16bit
ADDi.L    #32bit, Dn    -- for LONG values


And for doing a COMPARE
CMPW.L  #16bit,Dn     -- for values up to 16bit
CMPi.L    #32bit, Dn    -- for LONG values

The "W.L"  instruction above are new with 68080.
They allow to make shorter code, and faster when saving an instruction.

Opcode for ADDIW is
ADDIW.L	0000 0110 11	EA	 | 16bit signed imm

Opcode for CMPIW is
CMPIW.L	0100 1110 00	EA	| 16bit signed imm

Could you enable them please?

**Comment by bebbo** [comment]
The costs for postincrement are actually the same as without offset. The challenge here is to analyze all branches to fix the insns and ensure the original value isn't used elsewhere.

For new opcodes the binutils assemble needs an enhancement first. Then it's possible to add what the assembler supports.

**Comment by GunnarVB** [comment]
> The costs for postincrement are actually the same as without offset.
> The challenge here is to analyze all branches to fix the insns and 
> ensure the original value isn't used elsewhere.

Not sure I fully understand.
For the same of argument lets say that 
(a0) = cost 2
 (a0)+ = cost 2
d16(a0) = cost 3

With such cost database values, would then GCC not automatically pick "lower" cost code?

**Comment by GunnarVB** [comment]
I fully understand that a compiler can not always create the "perfect" code.

But maybe we can help the compiler at least to create a reasonable compromise code?

I think an instruction has several costs.
a) cost in cycles
b) cost in instruction length - which has an effect on cache hit rate, and on instruction fetch 
as a CPU can not load infinite amount of bytes from Icache per cycle.
c) memory access. While a CPU might be able to do a Dcache access for low cost or even free. There is risk of cache miss and then high cost. So if there are 2 instruction producing the same result, then using an option without memory access is preferable.

Would a cost database like the following make some sense?

COST1 = cycles*10 
COST2 = instruction_length*2
COST3 = memory access *5

TOTAL COST = COST1+COST2+COST3

I believe that using an updated cost database for all instructions similar to the above would help GCC to create a "reasonable" selection of instruction.

Would it be possible to do this?

**Comment by bebbo** [comment]
gcc does not know full insns. It needs to know the cost for half insns but can distinguish between src an dst.

If the value 4 corresponds to 1 cycle you could e.g. define
  src register -> 2
  dst register -> 2
a move dx,dy would then yield the cost 4.

or you can define the cost of an operater with given parameters.
e.g. costs for AND = 0 on 68080 -> add yields same costs as move

This is for optimizing for speed. Optimizing for size currently uses the same costs for all insns, but the operand size would be a better criteria - someone could do that^^

to model memory access you'd have to define s state machine with pipelines, as I did for the 68080 floating point ops. Even more work :-)

**Comment by bebbo** [comment]
[m68k_68000_10_costs.zip](https://github.com/bebbo/gcc/files/5972624/m68k_68000_10_costs.zip)
have fun

**Comment by bebbo** [comment]
if you use `short` for counters you get this now:
http://franke.ms/cex/z/9je3qj

**Comment by bebbo** [comment]
close pending :-)

**Comment by GunnarVB** [comment]
Very nice improvements, Thank you and well done!

Regarding the CostTable you send me.
We want to help you improve it.
What is the best way forward?

**Comment by bebbo** [comment]
> 
> 
> Very nice improvements, Thank you and well done!
> 
> Regarding the CostTable you send me.
> We want to help you improve it.
> What is the best way forward?

the best would be a working cost function for each cpu ^^

also good: a table which lists the source and dest costs for each operation and size. An example:

`and.l d0,d1`:
source:  AND(d0, d1)
destination: d1

`move.w (4,a1),d2`
source: MEM(PLUS(a1, 4))
dest: d2

if destination costs are the same, the can be grouped.

costs for shift/rot/mul/div need a formula, but these should be quite ok already.

The cost for 1 cpu cycle is 4.
e.g. if the `move.l d0,d1` takes one cycle, it should result in a cost of 4. and maybe the costs could be split up as src cost = 2 and dst cost = 2...

**Comment by GunnarVB** [comment]
Hi Bebbo
> The cost for 1 cpu cycle is 4

Can we make this more finegrain?
Can we for example do the following:
Can we have 3 parameter
1) Cost of Cycle
2) Cost of instruction word
3) Cost of Memory Access.

Maybe define like this
Ccycle = 9
Cword = 2
Cmemory= 7

with such formular we get such result
MOVEQ  #1,D0              = 11
MOVE.L #23456,D0       = 15
MOVE.L -8(SP),D0         = 18

Could we do this. Or is it required that Cycle is always =4?

**Comment by bebbo** [comment]
> > The cost for 1 cpu cycle is 4
> 
> Can we make this more finegrain?

you can do many multiples of 4 as you like. you could also use a base cost of 4, but some locations in gcc still assume that the cost per cycle is 4... I recommend to scale all values by 4.

plus you never provide the cost for a full instruction, only the cost for the source or the destination - and it's hard to split 1 with integers properly...

> Can we for example do the following:
> Can we have 3 parameter
> 
>     1. Cost of Cycle

the cost of cycle is fixed and it is 4.

>     2. Cost of instruction word

for -Os it makes sense to provide a size base cost.

>     3. Cost of Memory Access.

this is done for each source or destination. If it's a MEM(...) then the expression inside is taken and the addressing costs are return based on the used addressing mode.

> 
> Maybe define like this
> Ccycle = 9
> Cword = 2
> Cmemory= 7

memory costs are maby const for 68080, but not for other cpus, right?

> with such formular we get such result
> MOVEQ #1,D0 = 11
> MOVE.L #23456,D0 = 15
> MOVE.L -8(SP),D0 = 18
> 
> Could we do this. Or is it required that Cycle is always =4?

as written above - if I rewrite the cost stuff, I'll use the value 4 as cost for 1 cycle. If the instruction needs 8 cycles on a 68000 it should yield 32.

**Comment by GunnarVB** [comment]
>    2. Cost of instruction word
for -Os it makes sense to provide a size base cost.

But instruction length always has also a cycle cost.
For 68000 each extra word cost 4 cycle
For 68020/030 each extra word cost 2 cycle

For 68040/68080 instructions length has less direct measurable cost.
But as longer the used instructions as higher the chances if consuming the icache and as higher the chances for caches misses = which cost then a lot for memory fetches.
Also each CPU has a Icache fetch /decoder limitation.
Its  2 Byte per 2 Cycle for 68020/68030 and 4 Byte per Cycle for 68060.
So as longer the instructions get as more cost are direct and indirect created.
 
I think its very important for the compiler to try to use the most shorted possible instruction for the job.

**Comment by bebbo** [comment]
I'm talking about the total cost of an instruction. all in. whatever. there is no extra cost for fetching or addressing, these costs are included. That's why for MEM some wierd calculation is used to determine the total cost:
: (ax),  (ax)+
: -(ax)
: (n,ax)
: (n,ax,dy), ||n|| < 8
: (dx)
: (n,ax,dy.w/l*1/2/4/8)
: [(ax)]
: [(dx)]
...

and that's the challenge to model all-in costs for half instructions (src, dest) that the result for a full instruction is as close as possible to the real costs.

plus higher CPUs have worst, best and cache szenarios... I'd use values which close to the expected values - whatever this means...

and for -Os only the instruction size matters.
