### ISSUE TITLE
-O2 creates wrong code

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#145]
I have another issue with optimization.
I am experimentig with libgmp.

When I compile with -O2 several testcases fail. Without optimization these testcases pass. 
I identified only one file responsible for the trouble.

The original commandline for compiling is
`/home/developer/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-gcc -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_sqr_basecase -noixemul -O2 -Wall --pedantic -c sqr_basecase.c -o sqr_basecase.o`

I created a preprocessed c-File with -E and then assembly files with
```
/home/developer/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-gcc  -noixemul -O2 -Wall  -c sqr_basecase_preprocessed.c  -Wa,-adhln -g >sqr_basecase_preprocessed_O2.s 

/home/developer/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-gcc  -noixemul     -Wall  -c sqr_basecase_preprocessed.c  -Wa,-adhln -g >sqr_basecase_preprocessed.s
```

I attached the original and preprocessed c-file and the assembly-files compiled with and without -O2.
Could you have a look at the *.s files, please? Do you see anything suspicious?

[O2_wrong_code.zip](https://github.com/bebbo/amiga-gcc/files/6049622/O2_wrong_code.zip)

**Comment by bebbo** [comment]
could you please provide more details?

* ./configure ...???
* CFLAGS=???
* LDFLAGS=???
* which tests PASS with what option
* and do FAIL with what option

**Comment by githubaf** [comment]
This is what I did to build the lib and to test it.
```
wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz
#install lzip if necessary
#sudo apt-get install lzip
lzip -d gmp-6.2.1.tar.lz
tar -xf gmp-6.2.1.tar
cd gmp-6.2.1

PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH  ./configure CFLAGS=" -noixemul -O2 -Wall --pedantic" --disable-shared --host=m68k-amigaos

PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make

# in tests it turned out that strtod is missing. Should be in libnix? 
# get it from
#http://www.jbox.dk/sanos/source/lib/strtod.c.html
# compile with -c (object only), for simplicity just add it to libgmp

~/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-gcc -O2 -noixemul -fomit-frame-pointer strtod.c -c
~/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-ar -r ./.libs/libgmp.a strtod.o


#We need locale.library, copy it from amiga to current dir


vim ./test-driver    # there is the call to each test. Add "vamos -V Libs:~/Desktop/SelcoGit/gmp_for_bebbo/gmp-6.2.1 -C20 -H disable -s 256 -m 128000 " to begin of line 107
# So it becomes: vamos -V Libs:~/Desktop/SelcoGit/gmp_for_bebbo/gmp-6.2.1 -C20 -H disable -s 256 -m 128000 "$@" >$log_file 2>&1

#Christian fixed a memory problem I reported for the lib, so you need a recent version of amitools.

# Now we are ready to run some tests. For this demonstration we run the tests in tests/mpf. With -O2 in the configure-run three tests fail, 25 pass. without -O2 in the configure-run all 28 tests pass.
cd tests/mpf
time PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make check   # takes about 9 minutes on my computer

#FAIL: t-conv
#FAIL: t-sqrt
#FAIL: t-sqrt_ui

#we can run a single test by calling
time PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make check TESTS=t-conv  # takes only a second to fail.

#the Problem can be solved if we compile the file "mpn/sqr_basecase.c" without optimization. 
#We achive this by adding #pragma GCC optimize ("O0") to line 320 and then build everything again.
# go to start directory
cd ~/Desktop/SelcoGit/gmp_for_bebbo/gmp-6.2.1
PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make clean
PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make
#Add strtod() again
~/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-gcc -O2 -noixemul -fomit-frame-pointer strtod.c -c
~/opt/m68k-amigaos_21Feb21/bin/m68k-amigaos-ar -r ./.libs/libgmp.a strtod.o


#And test again:
cd tests/mpf
time PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make check   # all 28 test cases pass! takes 12 minutes on my computer

#or just one test
time PATH=/home/developer/opt/m68k-amigaos_21Feb21/bin/:$PATH make check TESTS=t-conv  # takes 2 minutes on my computer

```

**Comment by bebbo** [comment]
for `strtod` add `-lm`

**Comment by bebbo** [comment]
and my vamos version has a builtin locale...

**Comment by bebbo** [comment]
thanks for the vamos params: `-C20 -H disable -s 256 -m 128000` is needed to run.

**Comment by bebbo** [comment]
I get only this output from t-conv
```
ERROR mpf_set_str failed
   str  = "0.@0"
   base = 0
Program aborted
```

**Comment by githubaf** [comment]
On vamos or on an Amiga with big stack an mem?
Do you have a newer amitools? (Commit on Feb 10, 2021 "Fixed Deallocate() for no mem chunk"   

I get no output from t-conv when the lib is compiled with the pragma GCC optimize ("O0") in mpn/sqr_basecase.c

When all is compiled with -O2 I get
```
vamos -V Libs:~/Desktop/SelcoGit/gmp_for_bebbo/gmp-6.2.1 -C20 -H disable -s 256 -m 128000 t-conv     
ERROR after 6 tests
base = 38
   x = 0.3929032248415814715573716149594341159721e-1518
   y = 0.3792251944868767352835794090163822189984e-1518
Program aborted
```

**Comment by githubaf** [comment]
Ah, on the Amiga I got the same output as you. There seem to be a locale conflict somewhere. The test is propably compiled for English.
I set the Amiga (naked WinUAE install) to USA, and Language English, than it gives me the following output:

![O2](https://user-images.githubusercontent.com/28429123/109352581-59edcf80-787b-11eb-9865-5e7d54c9ca8b.PNG)

If compiled with the pragma the test passes again with no output.

**Comment by bebbo** [comment]
The bug is insided gmp's header, where asm for 68000 is defined:

```
...
"	| End inlined umul_ppmm"					\
	      : "=&d" (xh), "=&d" (xl),					\
		"=d" (__umul_tmp1), "=&d" (__umul_tmp2)			\
	      : "%2" ((USItype)(a)), "d" ((USItype)(b)));		\ 
```

-->

```
...
"	| End inlined umul_ppmm"					\
	      : "=&d" (xh), "=&d" (xl),					\
		"=&d" (__umul_tmp1), "=&d" (__umul_tmp2)			\
	      : "%2" ((USItype)(a)), "d" ((USItype)(b)));		\ 
```

**Comment by bebbo** [comment]
```
PASS: t-sqrt_ui
PASS: t-sub
PASS: t-add
PASS: t-cmp_d
PASS: t-cmp_si
PASS: t-div
PASS: t-fits
PASS: t-sqrt
PASS: t-get_d_2exp
PASS: t-muldiv
PASS: t-get_si
PASS: t-get_ui
PASS: t-gsprec
PASS: t-int_p
PASS: t-inp_str
PASS: t-mul_ui
PASS: t-get_d
PASS: t-set
PASS: t-set_q
PASS: t-set_si
PASS: t-set_ui
PASS: t-trunc
PASS: t-pow_ui
PASS: t-ui_div
PASS: reuse
PASS: t-eq
PASS: t-conv
PASS: t-dm2exp
============================================================================
Testsuite summary for GNU MP 6.2.1
============================================================================
# TOTAL: 28
# PASS:  28
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by githubaf** [comment]
Great finding! Thanks for your support!
I will test and report your finding to the gmp-team if you don't mind.

One more question:
your wrote:
> for strtod add -lm

That seems not to be necessary for linking for linux. Why is it necessary for Amiga? My understanding was -lm is necessary for floating point math support?

**Comment by bebbo** [comment]
> 
> 
> Great finding! Thanks for your support!
> I will test and report your finding to the gmp-team if you don't mind.
> 
> One more question:
> your wrote:
> 
> > for strtod add -lm
> 
> That seems not to be necessary for linking for linux. Why is it necessary for Amiga? My understanding was -lm is necessary for floating point math support?

`strtod` needs double math...
the idea of libnix was to put all float/double math into `libm.a`, `strtod`needs it, ..., even `printf` can't print float/double unless `-lm` is specified.

**Comment by githubaf** [comment]
I see. Thanks.
I am currently testing again. The complete test takes very long, about 4 days here :-|

How did you solve the locale issue? Did you run the t-conv test on vamos or on an (emulated) Amiga?

**Comment by bebbo** [comment]
> I see. Thanks.
> I am currently testing again. The complete test takes very long, about 4 days here :-|

I did not wait that long - CTRL-C was my friend.
 
> How did you solve the locale issue? Did you run the t-conv test on vamos or on an (emulated) Amiga?

I taught libnix not to `exit(20)` if there is no valid Amiga locale and init the decimalpoint first. Now the vamos builtin locale.library is good enough. And I run t-conv on both.

I disabled the asm mult16x16 to hunt the bug and with the generic version it run well. So the problem had to be the asm.
Here I compared the generated asm: http://franke.ms/cex/z/oG53bK and you see that only one register is used instead of two, since the modification is not recognized.

```
/* here --> */             "=d" (__umul_tmp1),
```
to
```
/* here --> */             "=&d" (__umul_tmp1),
```

does the magic.

**Comment by githubaf** [comment]
I reported your finding to gmp-bugs@gmplib.org and referred also to your compiler explorer.
The guys there disagree and claim the asm code is correct and the & is not needed. They think it is a compiler error.

```
The current code looks correct to me.  Please explain why you think it is not correct.

Torbjörn
```

```
>  With bebbo's change the tests pass so I think the change is reasonable.

I disagree.  If I am right that the inline asm is correct, changing it
to avoid triggering a compiler bug is not a reasonable change.  But
perhaps I am wrong and the inline asm is buggy, but then somebody needs
to explain in what way it is buggy.
 
Torbjörn
```
and I quoted you again
```
>>I disabled the asm mult16x16 to hunt the bug and with the generic
>> version it run well. So the problem had to be the asm.
>>Here I compared the generated asm: http://franke.ms/cex/z/oG53bK and
>> you see that only one register is used instead of two, since the
>> modification is not recognized.
>>
>>/* here --> */             "=d" (__umul_tmp1),
>>
>>to
>>
>>/* here --> */             "=&d" (__umul_tmp1),
>>
>>does the magic.

To be clear, the meaning of this &, according to the docs, is to tell
gcc that the "output" register assigned to __umul_tmp1 can't overlap the
inputs. If I read it correctly, __umul_tmp1 is %2 in the asm template,
and the b input is %5. I've forgotten most I knew about 68k assembly,
but it looks to me like %5 is used twice, and %2 is used in between,
which could be a problem if they're assigned the same register. But not
sure how that would interact with "%2" ((USItype)(a)), which if I get it
right forces this input to be allocated in the same register as
__umul_tmp1 output.

The sqr_basecase function uses a couple of umul_ppmm(rp[11], lpl, ul, ul),
so my best guess is that we get all *three* of a, b, __umul_tmp1 allocated
in the same register.

If you could show the generated code (after gcc's register allocation)
*and* point out precisely where things go wrong, that would be helpful.

Regards,
/Niels
```

Is the statement of Nils correct? 
I am confused with the extended ASM. Could you tell me what the "%2" at the input parameters line means? I did not find that in the Extended-Asm.html document.

: "%2" ((USItype)(a)), "d" ((USItype)(b)));

**Comment by bebbo** [comment]
This is how open source works: nobody wants your improvents.

Sorry - I pass on this.
