### ISSUE TITLE
major performance degration compared to previous code

### ISSUE THREAD

**Issue by GunnarVB** [bebbo/gcc#147]
Hello,

Please allow me to report a performance slow down by several times for some code, when comparing to GCC 2.9

Example Code:
```
int ArrayFill(int *array, int len) {
	int i = 0;
	for(; i < len; ++i) {
		array[i] = 50;
	}
	return 1;
}
```

** ASM created by GCC 6.5  -mregparm -m68080 -O3 -fomit-frame-pointer  
```
_ArrayFill:
        tst.l d0
        jle .L6
        lea (a0,d0.l*4),a1
.L3:
        moveq bebbo/amiga-gcc#50,d0
        move.l d0,(a0)+
        cmp.l a0,a1
        jne .L3
.L6:
        moveq bebbo/amiga-gcc#1,d0
        rts
```
**
The performance problem is clearly visible.
We have 4 instruction in the workloop.
- The 1st instruction the MOVEQ is totally wrong in the loop.
  This instrucion should be outside the loop!
- the Loop body uses CMP An,An. 
  This is very bad idea.
  The loop creates 4 instrucion of which all 4 are fully depending.
  the MOVEQ updates D0, on which the 2nd instruction depends.
  the 2nd instruction updates A0, on which the 3rd instruction depends
  the CMP the 3rd instruction updates the flags on which the 4th instruction depends.
  Because of this dependency chain this code has to be very slow.

** LOOP BODY**
```
.L3:
        moveq #50,d0
        move.l d0,(a0)+
        cmp.l a0,a1
        jne .L3
```
**

Proposed Solution:
1) The MOVEQ needs be moved outside the Loop.
2) The LOOP should us a construct which counts down like
    `SUBQ.L #1,D1 ; BNE`
    Using a Loopcounter which counts down will remove the dependancy issue with the work pointer and will allow parallel execution.

**Comment by bebbo** [comment]
> ```
> SUBQ.L #1,D0
> BNE
> ```
> 
> Can we get the same back?
> This code is better as its not depending on the PTR and can be executed without dependancy

negative. Guess you have to open a real gcc issue for that - and no other platform seems to need that...

=> rewrite the loop

**Comment by GunnarVB** [comment]
> Guess you have to open a real gcc issue for that - and no other platform seems to need that...
What makes you think this?

Everybody will agree that creating an unneeded register dependency is hurting every platform.
This is just logical.

If you look at the code generated by GCC for PowerPC then you see that is will
not use a CMP on the PTR but will use PTR and Countdown register fully independent.

By using the "(A0)++" operation and the "CMP A0", the compiler 
creates a register dependency which the C high level code did not have!
Or to say it clearly: The created code got much worse to the C original.

Would it be possible for GCC to model the 68K pipeline and for GCC to just "see" the dependency?
Then GCC would see this is bad code.

Or would it be simpler for you to cheat and make the combo of  "SUBq.l #0,D0; BNE" a little cheaper than the "CMPA BNE "

**Comment by bebbo** [comment]
this is the loop body for x86:
```
.L3:
        movl    $50, (%rdi)
        addq    $4, %rdi
        cmpq    %rax, %rdi
        jne     .L3
.L2:
```

And the reason is, that gcc only introduces a count down tmp variable for const int limits.

**Comment by bebbo** [comment]
the code for arm:
```
.L3:
        str     w3, [x0, x2, lsl 2]
        add     x2, x2, 1
        cmp     w1, w2
        bgt     .L3
```

**Comment by GunnarVB** [comment]
Or would it be simpler for you to cheat and make the combo of "SUBq.l #0,D0; BNE" a little cheaper than the "CMPA BNE "

**Comment by bebbo** [comment]
> 
> 
> Or would it be simpler for you to cheat and make the combo of "SUBq.l #0,D0; BNE" a little cheaper than the "CMPA BNE "

won't work... sorry

**Comment by bebbo** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=22041

**Comment by bebbo** [comment]
I found an old gcc version (4.8.5) for powerpc which did it: https://godbolt.org/z/o9Knav

=> https://franke.ms/cex/z/93a7cb

the loop header can be improved... but the loop body?

**Comment by GunnarVB** [comment]
well done!

This is a big improvement!

**Comment by bebbo** [comment]
fixed
