### ISSUE TITLE
insn does not satisfy its constraints

### ISSUE THREAD

**Issue by AJenbo** [bebbo/gcc#149]
Hi, we started getting build errors for DevilutionX recently, It looks like it is an issue with GCC so reporting it here in the hope you can help :)

https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3341/workflows/aad35355-0551-41b9-8d58-ad886cf34898/jobs/18727

```
(insn 6082 8214 2846 326 (set (mem:QI (reg:SI 8 a0) [0 MEM[base: _2539, offset: 0B]+0 S1 A8])
        (ior:QI (mem:QI (reg:SI 9 a1) [0  S1 A8])
            (const_int -128 [0xffffffffffffff80]))) /root/repo/Source/drlg_l3.cpp:2213 247 {iorqi3}
     (nil))
/root/repo/Source/drlg_l3.cpp: In function 'void dvl::CreateL3Dungeon(dvl::DWORD, int)':
/root/repo/Source/drlg_l3.cpp:2650:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 6082 8214 2846 326 (set (mem:QI (reg:SI 8 a0) [0 MEM[base: _2539, offset: 0B]+0 S1 A8])
        (ior:QI (mem:QI (reg:SI 9 a1) [0  S1 A8])
            (const_int -128 [0xffffffffffffff80]))) /root/repo/Source/drlg_l3.cpp:2213 247 {iorqi3}
     (nil))
/root/repo/Source/drlg_l3.cpp:2650:1: internal compiler error: in extract_constrain_insn, at recog.c:2199
```

**Comment by MBeijer** [comment]
This is the `m68k-amigaos-gcc -v` information from the docker image they use:
```
docker.io/amigadev/crosstools:m68k-amigaos
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/m68k-amigaos/libexec/gcc/m68k-amigaos/6.5.0b/lto-wrapper
Target: m68k-amigaos
Configured with: /root/projects/gcc/configure --prefix=/opt/amiga --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/root/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared --enable-threads=no --with-stage1-ldflags='-dynamic-libgcc -dynamic-libstdc++' --with-boot-ldflags='-dynamic-libgcc -dynamic-libstdc++'
Thread model: single
gcc version 6.5.0b 210304090852 (GCC)
```

**Comment by bebbo** [comment]
maybe you could provide also the full command line how `m68k-amigaos-gcc` gets invoked...

**Comment by AJenbo** [comment]
Sure, how do I get that? I'm just a simple tool chain user, I don't know how all this is strung together on the low level.

**Comment by AJenbo** [comment]
Maybe you will find this useful:
https://github.com/diasurgical/devilutionX/blob/master/Packaging/amiga/Dockerfile
https://github.com/diasurgical/devilutionX/blob/master/Packaging/amiga/prep.sh

**Comment by bebbo** [comment]
> Sure, how do I get that? I'm just a simple tool chain user, I don't know how all this is strung together on the low level.

ask the project maintainers - not me.

I need a preprocessed file plus all command line options to reproduce the issue.

**Comment by AJenbo** [comment]
I'm the maintainer of DevilutionX. Are you referring to the maintainer of amigadev/crosstools:m68k-amigaos or something else?

**Comment by MBeijer** [comment]
The full parameter list is:
```
-m68040 -mhard-float -s -ffast-math -O3 -noixemul -D__BIG_ENDIAN__ -D__AMIGA__ -fpermissive
```

**Comment by bebbo** [comment]
> 
> 
> The full parameter list is:
> 
> ```
> -m68040 -mhard-float -s -ffast-math -O3 -noixemul -D__BIG_ENDIAN__ -D__AMIGA__ -fpermissive
> ```

thank you - no I only need the preprocessed file.

**Comment by AJenbo** [comment]
I'm guessing this is what you are after, but I'm new to debugging GCC so some pointers would be helpful.

[drlg_l3.cpp.zip](https://github.com/bebbo/gcc/files/6095717/drlg_l3.cpp.zip)

**Comment by MBeijer** [comment]
@AJenbo The docker-image should now be updated with latest, trigger the CI and test :)

**Comment by AJenbo** [comment]
Good timing considering that I'm working on BE issues today :) Let's see how it goes:
https://app.circleci.com/jobs/github/diasurgical/devilutionX/19255?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by MBeijer** [comment]
I will test the build after work. But I'd consider this issue closed. :+1:

**Comment by AJenbo** [comment]
Thanks :)
