### ISSUE TITLE
-mregparm  has issues

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#15]
Both, -mcrt=clib2 and -noixemul have crashing issues in combination with -mregparm=4.

I can't pin it down yet, but opening this issue for tracking.

**Comment by mheyer32** [comment]
In case of using clib2:

The crash happens in  here (amiga_video.c, amiga_getevents() )
```
    if (LowLevelBase != NULL) {
        DEBUGSTEP();
        event_t joyevent;
        ULONG joypos = ReadJoyPort(1);  <<<<<<<<<<<<
        DEBUGSTEP();
```

Ironically,  LowLevelBase is defined and initialized to NULL and should only be non-NULL if  -joypad was passed in as parameter. I don't do that. The call to ReadJoyPort looks legitimate:
```
    99da:	2c79 0000 4324 	moveal 4324 <_LowLevelBase>,%a6
    99e0:	7001           	moveq #1,%d0
    99e2:	4eae ffe2      	jsr %a6@(-30)
    99e6:	2400           	movel %d0,%d2
```
 
My suspicion is that some other code is overwriting LowLevelBase with a bogus value and  ReadJoyPort hops straight into nirvana.

**Comment by bebbo** [comment]
is https://github.com/mheyer32/ADoom current?

**Comment by mheyer32** [comment]
It is fairly recent, structurally I didn't change much locally (mainly adding more DEBUGSTEP() everywhere). Once you built the executable, place it next to a doom2.wad (doom.wad might work as well).
I suggest

stack 20000
adoom -nosfx    

(so it doesn't lock the audio.device when it crashes and you may get multiple runs before reboot)

In the very best case you'll be able to start it up, choose "New Level" in the main menu. 
The level will be loaded up and will be somewhat responding. Beware, the rendering will be all garbled
except for the enemy sprites... but I believe this might be an actual bug with the game code itself, not the compiler.

You will want to change the makefile to use clib2 instead of noixemul (and change it back if you want to investigate noixemul issues ;) ) 

```
// comment that out:
RUNTIME_CFLAGS = $(NOIXEMUL_CFLAGS)
RUNTIME_LDFLAGS = $(NOIXEMUL_LDFLAGS)

// comment that back in to use clib2
#RUNTIME_CFLAGS = $(CLIB_CFLAGS)
#RUNTIME_LDFLAGS = $(CLIB_LDFLAGS)
```

**Comment by mheyer32** [comment]
One more remark: the version on GitHub still has all the __regargs attributes _and_ register parameters for all functions that are either implemented in assembly or are being called by assembly functions. But your latest fixes should turn those into a no-op anyway.

**Comment by mheyer32** [comment]
Ok, I figured one thing out:
When specifying  -mregparms=4,   main(int argc, char *argv[]) expects its parameters in register d0 and a1.
BUT: the clib2 startup code is still calling it with the parameters on the stack.

I worked around this by adding __stdargs to my main() function declaration. But I believe this should be sort of automatic, no?! 

This solved my problem with the bogus call into ReadJoyPort().

But now its crashing somewhere else. Oh joy... some more digging :-)

**Comment by bebbo** [comment]
> I worked around this by adding __stdargs to my main() function declaration. But I believe this should be sort of automatic, no?!

I won't change your believe, but consider that someone might provide own startup code for mregparm...

better no automatic.

**Comment by bebbo** [comment]
>One more remark: the version on GitHub still has all the __regargs attributes and register parameters for all functions that are either implemented in assembly or are being called by assembly functions. But your latest fixes should turn those into a no-op anyway.

Right, __regargs should do no harm if there are register parameters.

**Comment by bebbo** [comment]
```
struct ExecBase *SysBase = (struct ExecBase *)4; 
```
really?
```
struct ExecBase *SysBase = *(struct ExecBase **)4; 
```

**Comment by bebbo** [comment]
now with -noixemul:
```
ADoom 1.4 (8.1.2011)
opening icon.library
success!
success 2!
success 3!
>>>> 0, main : 167
success 4!
success D_DoomMain!
success 5!
success 6!
success 8!
success 9!
success 10!
                         DOOM 2: Hell on Earth v1.10
success 11!
V_Init: allocate screens.
Resolution: 320 x 200
M_LoadDefaults: Load system defaults.
Z_Init: Init zone memory allocation daemon.
Memfree = 123248448, largest = 122174416
I_ZoneBase(): Allocated 6291456 bytes for zone management
W_Init: Init WADfiles.
 adding PROGDIR:doom2.wad
===========================================================================
                 Commercial product - do not distribute!
         Please report software piracy to the SPA: 1-800-388-PIR8
===========================================================================
>>>> 1, D_DoomMain : 1104
M_Init: Init miscellaneous info.
>>>> 2, D_DoomMain : 1106
>>>> 3, M_Init : 1508
>>>> 4, M_Init : 1524
>>>> 5, M_Init : 1531
>>>> 6, M_Init : 1540
>>>> 7, M_Init : 1555
>>>> 8, D_DoomMain : 1108
R_Init: Init DOOM refresh daemon - >>>> 9, R_InitTextures : 399
>>>> 10, R_InitTextures : 404
>>>> 11, R_InitTextures : 411
>>>> 12, R_InitTextures : 418
>>>> 13, R_InitTextures : 422
>>>> 14, R_InitTextures : 431
>>>> 15, R_InitTextures : 444
>>>> 16, R_InitTextures : 454
[.............................
R_InitData
R_InitPointToAngle
R_InitTables
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables
P_Init: Init Playloop state.
Error: R_InitSprites: Sprite TROO : A : 1 has two lumps mapped to it
```

**Comment by bebbo** [comment]
libnix memset is broken: **do not pass negativ values** until it's fixed

-1 -> 0xff

and sprites are initialized.

I'm reaching the start screen now but the game does not yet start after selecting a difficulty

**Comment by mheyer32** [comment]
Thanks!
Where do negative values get passed into memset? As value or as size?

Also, did you try with -mcrt=clib2 ? Did you see other problems there?

Re: SysBase:  yeah, that was a blunder I already had fixed locally. Mind you, this is the first time in 20 years I come back to the Amiga and the first time I try C on it :-) 
I wonder, though, why the linker didn't complain about defining the same symbol twice?

**Comment by bebbo** [comment]
The linker only complains if the same symbol is present in two or more included units.
The library provides it but it's already present, so the library's unit is simply not picked up and also the (correct) intialization is not picked up.

With `extern` the library unit is used plus its initialization.

**Comment by bebbo** [comment]
with clib2 it's "running" but the walls are not visible...
... does it run if compiling with SAS/C?

**Comment by mheyer32** [comment]
I never bothered with SAS/C.  But yes, this is as far as I ever got :-) I guess, there might be some signedness bugs in the render code somewhere, maybe the assembly routines are buggy - who knows.

My local version (compiled against -noixemul)  is crashing during startup in amiga_video.c, I_InitGraphics

```
    DEBUGSTEP();
    for (depth = 0; depth < video_depth; depth++) {
        DEBUGSTEP();
        if ((video_tmp_bm.Planes[depth] = (PLANEPTR)AllocRaster(SCREENWIDTH, 1)) == NULL) {
            I_Error("AllocRaster() for video_tmp_bm failed");
        }
    }

    DEBUGPRINT(("&video_temprp %p, video_window %p, video_window->RPort %p, size %d", 
    &video_temprp, video_window, video_window->RPort, sizeof(struct RastPort)));

   // CRASH  in this copy:
    video_temprp = *video_window->RPort;
```

The asssembly of the call looks totally innocent:

```
 4662 2150 2079 0000 		lea _video_temprp:W(a4),a2
 4662      0000 
 4663 2156 2F28 0004 		moveq #100,d0
 4664 215a 2244      		move.l _video_window,a0
 4665 215c 4E91      		move.l 50(a0),a1
 4666               		move.l a2,a0
 4667 215e 41F9 0000 		jsr _memcpy

```

**Comment by mheyer32** [comment]
... but the implementation of memcpy seems to look for the arguments on the stack:
```
0003bd50 <_memcpy>:
   3bd50:	2f0e           	movel %a6,%sp@-
   3bd52:	2f02           	movel %d2,%sp@-
   3bd54:	242f 000c      	movel %sp@(12),%d2      <<<<<<<<<<<<<<<< here
   3bd58:	2c79 0000 6990 	moveal 6990 <_SysBase>,%a6
   3bd5e:	206f 0010      	moveal %sp@(16),%a0  <<<<<<<<<<< here
   3bd62:	2242           	moveal %d2,%a1
   3bd64:	202f 0014      	movel %sp@(20),%d0          <<<<<<<<<<<<< here
   3bd68:	4eae fd90      	jsr %a6@(-624)
   3bd6c:	2002           	movel %d2,%d0
   3bd6e:	241f           	movel %sp@+,%d2
   3bd70:	2c5f           	moveal %sp@+,%a6
   3bd72:	4e75           	rts
```

(BTW: would it be possible to make memcpy an intrinsic and optimize out memcpy calls for small, constant sized copies?)

**Comment by mheyer32** [comment]
Is it possible that GCC's  idea of what the 'internal' memcpy looks like is different from what libnix declares/implements?

**Comment by mheyer32** [comment]
-mcrt=clib2 -mregparm=4  seems to have exactly the same problem

**Comment by bebbo** [comment]
Guess you did not did a clean build, since the libnix headers are now containing `__stdargs` for all lib functions.

```
.L370:
        lea _video_temprp:W(a4),a2
        pea 100.w
        move.l _video_window,a0
        move.l 50(a0),-(sp)
        move.l a2,-(sp)
        jsr _memcpy
```

... and I do not yet bother about intrinsic/builtin functions...

**Comment by mheyer32** [comment]
Confirmed! I think the rest of issues now actually lies with the game code.

I guess,
./toolchain-m68k --prefix=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos clean
is not as sqeaky clean as it should be. Just in case, I also blew away the complete /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos   directory and now I'm getting good results.

Any chance for built-in memcpy/memset? I find it pretty appalling to call through two different functions just to copy 100bytes from a to b :-)

I was looking at the gcc source, there's a lot of the built-in related stuff in gcc/buitlins.c[.h ], but I have no idea where to start. Does any of the other amiga gcc ports support builtins?

Closing.

**Comment by mheyer32** [comment]
Reopening. Weird as it sounds, but without touching the toolchain, the issue is back again.

```
    6c28:	7064           	moveq #100,%d0
    6c2a:	2079 0000 588c 	moveal 588c <_AslBase+0x1484>,%a0
    6c30:	2268 0032      	moveal %a0@(50),%a1
    6c34:	204a           	moveal %a2,%a0
    6c36:	4eb9 0003 ba98 	jsr 3ba98 <_memcpy>
```
Something erratic is going on. Most other places in the disassembly use stack parameters for memcpy, but this one seems to flip back and forth - and I have no idea why.

```
/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/bin/m68k-amigaos-gcc -v -noixemul -DUSENOIXEMU -mregparm=4 -fbaserel -m68030 -m68881 -O3 -fstrength-reduce -fomit-frame-pointer -Werror -Wimplicit -Wstrict-prototypes -include "doomdef.h" -DVERBOSE -D__BIG_ENDIAN__ -DNORMALUNIX -DAMIGA -Diabs=abs -c amiga_video.c -o amiga_video.o
Using built-in specs.
COLLECT_GCC=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/bin/m68k-amigaos-gcc
Target: m68k-amigaos
Configured with: /home/matze/amigatoolchain/gcc-6.2/amigaos-cross-toolchain/submodules/gcc-6/configure --prefix=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos --infodir=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/m68k-amigaos/info --mandir=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/share/man --prefix=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos --prefix=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --with-headers=/home/matze/amigatoolchain/gcc-6.2/amigaos-cross-toolchain/submodules/ixemul/include
Thread model: single
gcc version 6.4.1b 20180126-104713 (GCC) 
COLLECT_GCC_OPTIONS='-v' '-noixemul' '-D' 'USENOIXEMU' '-mregparm=4' '-fbaserel' '-mcpu=68030' '-m68881' '-O3' '-fomit-frame-pointer' '-Werror' '-Wimplicit' '-Wstrict-prototypes' '-include' 'doomdef.h' '-D' 'VERBOSE' '-D' '__BIG_ENDIAN__' '-D' 'NORMALUNIX' '-D' 'AMIGA' '-D' 'iabs=abs' '-c' '-o' 'amiga_video.o'
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/libexec/gcc/m68k-amigaos/6.4.1b/cc1 -quiet -v -imultilib libb -D__HAVE_68881__ -isystem /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/m68k-amigaos/libnix/include -Dlibnix -D__libnix__ -D__libnix -D USENOIXEMU -D VERBOSE -D __BIG_ENDIAN__ -D NORMALUNIX -D AMIGA -D iabs=abs -include doomdef.h amiga_video.c -quiet -dumpbase amiga_video.c -mregparm=4 -mcpu=68030 -m68881 -auxbase-strip amiga_video.o -O3 -Werror -Wimplicit -Wstrict-prototypes -version -fbaserel -fomit-frame-pointer -o /tmp/ccEfYlJH.s
GNU C11 (GCC) version 6.4.1b 20180126-104713 (m68k-amigaos)
	compiled by GNU C version 4.9.2, GMP version 6.0.0, MPFR version 3.1.2-p11, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
#include "..." search starts here:
#include <...> search starts here:
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/m68k-amigaos/libnix/include
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/include
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/sys-include/../../include
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/sys-include
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/include
End of search list.
GNU C11 (GCC) version 6.4.1b 20180126-104713 (m68k-amigaos)
	compiled by GNU C version 4.9.2, GMP version 6.0.0, MPFR version 3.1.2-p11, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: d47fd1bb5799eb9cd0d0538d9e59c17f
COLLECT_GCC_OPTIONS='-v' '-noixemul' '-D' 'USENOIXEMU' '-mregparm=4' '-fbaserel' '-mcpu=68030' '-m68881' '-O3' '-fomit-frame-pointer' '-Werror' '-Wimplicit' '-Wstrict-prototypes' '-include' 'doomdef.h' '-D' 'VERBOSE' '-D' '__BIG_ENDIAN__' '-D' 'NORMALUNIX' '-D' 'AMIGA' '-D' 'iabs=abs' '-c' '-o' 'amiga_video.o'
 /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/bin/as --traditional-format -m68030 -S -o amiga_video.o /tmp/ccEfYlJH.s
COMPILER_PATH=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/libexec/gcc/m68k-amigaos/6.4.1b/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/libexec/gcc/m68k-amigaos/6.4.1b/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/libexec/gcc/m68k-amigaos/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/bin/
LIBRARY_PATH=/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/libb/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/lib/libb/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/:/home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/lib/
COLLECT_GCC_OPTIONS='-v' '-noixemul' '-D' 'USENOIXEMU' '-mregparm=4' '-fbaserel' '-mcpu=68030' '-m68881' '-O3' '-fomit-frame-pointer' '-Werror' '-Wimplicit' '-Wstrict-prototypes' '-include' 'doomdef.h' '-D' 'VERBOSE' '-D' '__BIG_ENDIAN__' '-D' 'NORMALUNIX' '-D' 'AMIGA' '-D' 'iabs=abs' '-c' '-o' 'amiga_video.o'
```

**Comment by mheyer32** [comment]
This time reopening for real.

**Comment by bebbo** [comment]
please do a `git log -n 1` in the toolchain folder and in submodule libnix, also a `git status` does not hurt.
```
$ git log -n 1
commit 99095dd39b76d67e38adf2f964b4005cafe95383 (HEAD -> master, origin/master, origin/HEAD)
Author: bebbo <bebbo@bejy.net>
Date:   Sat Jan 27 22:21:06 2018 +0100

    update libnix

stefan@Thinky ~/a
$ pushd submodules/libnix
~/a/submodules/libnix ~/a /cygdrive/d/develop/workspaces/c1/test/pfs3aio

stefan@Thinky ~/a/submodules/libnix
$ git log -n 1
commit 7e7fb1be168cce62585a54ce4a7782bdd419e38f (HEAD -> master, origin/master, origin/HEAD)
Author: bebbo <bebbo@bejy.net>
Date:   Sat Jan 27 22:20:49 2018 +0100

    fix memset if a negative value is passed

stefan@Thinky ~/a/submodules/libnix
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
Then check your prefix libnix include folder: `ls -l /home/matze/amigatoolchain/gcc-6.2/m68k-amigaos/m68k-amigaos/libnix/include`

here is my output:
```
$ ls -l /opt/amiga/m68k-amigaos/libnix/include/
total 58
-rw-rw-r--+ 1 stefan Kein  795 Jan  4 19:28 bases.h
-rw-rw-r--+ 1 stefan Kein  344 Jan  4 19:28 debuglib.h
-rw-rw-r--+ 1 stefan Kein  716 Jan 20 20:12 dirent.h
drwxrwxr-x+ 1 stefan Kein    0 Jan 13 22:59 inline
-rw-rw-r--+ 1 stefan Kein 3736 Jan  4 19:28 libinit.h
-rw-rw-r--+ 1 stefan Kein  852 Jan  4 19:28 pool.h
-rw-rw-r--+ 1 stefan Kein  433 Jan 20 20:12 rand48.h
-rw-rw-r--+ 1 stefan Kein 1153 Jan  4 19:28 regparm.h
-rw-rw-r--+ 1 stefan Kein  844 Jan  4 19:28 select.h
-rw-rw-r--+ 1 stefan Kein 3279 Jan 20 20:13 socket.h
-rw-rw-r--+ 1 stefan Kein 2876 Jan  4 19:28 stabs.h
-rw-rw-r--+ 1 stefan Kein 8526 Jan 20 20:15 stdio.h
-rwxrwxr-x+ 1 stefan Kein 4284 Jan 19 15:13 string.h
-rw-rw-r--+ 1 stefan Kein 2104 Jan 21 11:50 strsup.h
```
then also check the content of string.h:
```
__stdargs void	*memcpy __P((void *, const void *, size_t)); 
```

**Comment by bebbo** [comment]
Update: if a struct is initialized there is already some builtin stuff there which decides to emit some moves or to call memcpy. And THAT memcpy don't care about the header...

All others do, so my test cases were testing the wrong thing.

Now I consider all builtin function calls as __stkparam

**Comment by bebbo** [comment]
I also found why there are no walls:

amiga_segs.s:
```
		move.l	_tantoangle(a4),a0
		move.l	(a0,d0.l*4),d1
		add.l	#ANG90,d1
		moveq	#ANGLETOFINESHIFT,d0
		asr.l	d0,d1
		move.l	_finesine(a4),a0
```
correct:
```
		lea	_tantoangle,a0
		move.l	(a0,d0.l*4),d1
		add.l	#ANG90,d1
		moveq	#ANGLETOFINESHIFT,d0
		asr.l	d0,d1
		lea	_finesine,a0
```

**Comment by bebbo** [comment]
there is still something trashing the memory, but I can start and play a while

**Comment by bebbo** [comment]
maybe the last issue is related to clipbot and cliptop in amiga_things.s

both are use with (a4) but are in an own section

```
		section	__MERGED,bss

			cnop	0,4
MAXSCREENWIDTH	equ	1600
clipbot:	ds.w	MAXSCREENWIDTH
cliptop:	ds.w	MAXSCREENWIDTH
```
initialized data in bss - wierd!

So I removed the (a4) for these variables - maybe it's better to move the variables into a c file or use the correct section type and name (.data, data)?

**Comment by bebbo** [comment]
using the correct section names for gcc all sections are merged:

code: .text
data: .data
far data: .data_far
chip data: .data_chip
bss: .bss
far bss: .bss_far
chip bss: .bss_chip


```
reading bin/ADoom
hunk 000003f3,      HUNK_HEADER,          0
5 sections, 0 - 4
sizes: 222268, 56620, 212028, 12(c), 110232
hunk 000003e9,        HUNK_CODE,     222268
hunk 000003ec,     HUNK_RELOC32,      14528
hunk 000003f0,      HUNK_SYMBOL,         20
HUNK_END
hunk 000003ea,        HUNK_DATA,      18696
hunk 000003ec,     HUNK_RELOC32,       2780
hunk 000003f0,      HUNK_SYMBOL,          8
HUNK_END
hunk 000003eb,         HUNK_BSS,     212028
hunk 000003f0,      HUNK_SYMBOL,         12
HUNK_END
hunk 000003eb,         HUNK_BSS,         12
HUNK_END
hunk 000003ea,        HUNK_DATA,     110232
hunk 000003ec,     HUNK_RELOC32,       2496
hunk 000003f0,      HUNK_SYMBOL,         12
HUNK_END
```

**Comment by mheyer32** [comment]
Awesomemost!

Some questions

1. Can has optimized builtin memcpy plz? While I can work around direct calls to memcpy and replace them with my own routine, I have no visibility and control over copying structs around (except not using that and instead explicitly have a function that does the copy).
2. Would it have been possible to make the linker warn about the section inconsistencies (like the same symbol living in different sections)? This would have been really hard for me to figure out... coming from 'modern' development, you just do not think about linker intricacies anymore :-) Also, do you have some sources that I can read about that stuff?
3. __MERGED seems to be an Amiga assembler thing... is there a way to support that? I'm trying to think forward... If people want to bring other older Amiga projects to GCC they would likely fall into the same traps is I did.

> So I removed the (a4) for these variables - maybe it's better to move the variables into a c file or use the correct section type and name (.data, data)?

Yeah, I had a problem like that before with two variables FixedMul and FixedDiv... but those were function pointers and caused hard crashes. The other variables were just messing up the rendering.
I solved that by moving the definition of these variables into the C code. But it would be of course great, if people had the choice to leave them in the assembly code. Seamless support for mixing C and assembly is really a must on the Amiga.

Anyways, awesome work \o/

**Comment by bebbo** [comment]
A1. The compiler inserts moves for small fixed sizes, for larger sizes _memcpy is called. So if you provide a better _memcpy it is used.
A2. It's ok to have as many sections as you like. The hunk naming differs from compiler to compiler and so a developer has to learn that. And I don't have current sources. I read and modified the source codes of the compiler, assembler and linker... and then defined the new sectio names as I wrote.
A3. I guess __MERGED is rather a PHXASS assembler thing. I never used PHXASS before. I used O.M.A. and it can't assemble these files. Ususally the linker merges all sections with the same name, so ensure that the attributes do match.

With the modified section names, addressing via a4 should be ok again.

And yes, the linker should check that the baserel offset refers to the default data section. Maybe I can add that improvement.

**Comment by bebbo** [comment]
and some optimizations are futile, e.g swap:

the normal code
```
short swapshort(unsigned short s) {
  return s<<8 | s >> 8;
}

unsigned swap(unsigned x) {
  return (((x) >> 24) | (((x) & 0xff0000) >> 8) | (((x) & 0xff00) << 8) | (((x) & 0xff) << 24));
}
```
results in optimal asm code: `m68k-amigaos-gcc -Os s.c -S -mregparm=2`
```
_swapshort:
        ror.w #8,d0
        rts
        .align  2
        .globl  _swap
_swap:
        ror.w #8,d0
        swap d0
        ror.w #8,d0
        rts
```

**Comment by mheyer32** [comment]
Closing.  This time for good :-)
