### ISSUE TITLE
Unnecessary register allocation

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#150]
http://franke.ms/cex/z/74oEvP

a5 is saved and restored from stack but not used.  probably a temporary that survived cleanup?

**Comment by bebbo** [comment]
since the stack pointer is used too much and tracking the stack pointer offset is not perfect, there is currently no way to remove superfluous push/pops - despite the register a5 was replaced by a0...

**Comment by alexalkis** [comment]
ok.
