### ISSUE TITLE
instruction costs on optimisation

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#151]
I noticed this
http://franke.ms/cex/z/qd8fnv

does lsl.l #4 on 68060, something weird in 68040 and just shift half-way through (2 instead of 4) and then 12 adds in 68000 & 68020
If I am reading the costs correctly on 68000
add.l is 6cycles (=96 cycles on 16 adds)
lsl.l is 8+2n (=16 cycles on n=4)

The optimiser chooses to do 
lsl.l #2,d0  (12 cycles)
and 12 add.l d0,d0 (72 cycles), total 84 cycles

I think on >=68020 the cpu got a barrel shifter and the shift cost is constant.

**Comment by bebbo** [comment]
this is solved in gcc-10.
won't backport the solution.

**Comment by alexalkis** [comment]
Oh, we are getting gcc-10?! Awesome! 👍
