### ISSUE TITLE
internal compiler error: in change_address_1, at emit-rtl.c:2129

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#154]
after today's git pull,  I get an internal compiler error. Preprocessed file attached, command line used:

m68k-amigaos-gcc -Os -fomit-frame-pointer -c problem.c
[problem.zip](https://github.com/bebbo/gcc/files/6344932/problem.zip)

**Comment by bebbo** [comment]
https://franke.ms/cex/z/456jMK
