### ISSUE TITLE
internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#157]
[problem.zip](https://github.com/bebbo/gcc/files/6525560/problem.zip)

Compile with:

m68k-amigaos-gcc -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BIG_ENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_LOCALE_H=1 -DHAVE_WCHAR_H=1 -DHAVE_STDARG=1 -DHAVE_SYS_TIME_H=1 -DHAVE_STRUCT_LCONV_DECIMAL_POINT=1 -DHAVE_STRUCT_LCONV_THOUSANDS_SEP=1 -DHAVE_ALLOCA_H=1 -DHAVE_VA_COPY=1 -DHAVE_SETLOCALE=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_SIGNAL=1 -DHAVE_SIGACTION=1 -DHAVE_LONG_LONG=1 -DHAVE_INTMAX_T=1 -DMPFR_HAVE_INTMAX_MAX=1 -DMPFR_PRINTF_MAXLM=\"j\" -DMPFR_HAVE_NORETURN=1 -DMPFR_HAVE_BUILTIN_UNREACHABLE=1 -DMPFR_HAVE_CONSTRUCTOR_ATTR=1 -DHAVE_ROUND=1 -DHAVE_TRUNC=1 -DHAVE_FLOOR=1 -DHAVE_CEIL=1 -DHAVE_NEARBYINT=1 -DHAVE_LDOUBLE_IEEE_EXT_BIG=1 -DMPFR_USE_STATIC_ASSERT=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_ATTRIBUTE_MODE=1 -DHAVE___GMPN_SBPI1_DIVAPPR_Q=1 -DMPFR_LONG_WITHIN_LIMB=1 -DHAVE_GETRUSAGE=1 -I. -I/home/alex/dev/acalc/libs/.build-dev/sources/mpfr-4.0.1/src -noixemul -fomit-frame-pointer -O3 -D_MPFR_H_HAVE_FILE -DMPFR_LCONV_DPTS=0 -I/home/alex/dev/acalc/libs/mitsos/include -L/home/alex/dev/acalc/libs/mitsos/lib -ffloat-store -MT vasprintf.lo -MD -MP -MF .deps/vasprintf.Tpo -c problem.c

Gives:
/home/alex/dev/acalc/libs/.build-dev/sources/mpfr-4.0.1/src/vasprintf.c: In function 'buffer_widen':
/home/alex/dev/acalc/libs/.build-dev/sources/mpfr-4.0.1/src/vasprintf.c:609:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.

**Comment by bebbo** [comment]
thank's for the preprocessed file. Once preprocess you can omitt all defines and include paths..

`m68k-amigaos-gcc -O3 -c problem.c`

is enough

**Comment by bebbo** [comment]
http://franke.ms/cex/z/PvTYxG

**Comment by alexalkis** [comment]
Fixed, thanks!
