### ISSUE TITLE
Seems to ignore sign in bit shifting

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#158]
http://franke.ms/cex/z/57PMvr

Ends up doing lsr instead of asr.  (Other compilers do asr)

**Comment by bebbo** [comment]
the lower word is not affected since it's a shift of 13.

**Comment by alexalkis** [comment]
You are right if I switch to 32 bit return value, it switches to asr
http://franke.ms/cex/z/jTG97P
