### ISSUE TITLE
Compiler insists on mulsi3() 

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#159]
I played witht compiler explorer on your page. Nice toy!

I tried the following code, multiplying to 16Bit values into an 32 Bit value:
```
// Optionas: -noixemul -Os -fomit-frame-pointer -m68000

unsigned int UMul16(unsigned short a, unsigned short b)
{
    return a*b;
}

int Mul16(short a, short b)
{
    return a*b;
}
```

2.95.3, 10.2.1.b and SAS/C 6.58 use just "mulu" and "muls" while gcc 6.5.0.b calls mulsi3(). Statring with -m68020 it uses mulu/muls, too. Is that known issue?

gcc-6.5.0-elf uses "mulu" and "muls".

**Comment by darrenfreeman** [comment]
I just hit this bug, and wanted to say thanks for reporting, and thanks for fixing.

**Comment by darrenfreeman** [comment]
This is actually not fixed for me, using gcc commit d1e2278a88257d31ddcd181f364715af8a58c610.

My assembly listing has only `___mulsi3`, and no `muls` instructions.

I am using the following compiler invocation: `m68k-amigaos-gcc -Wa,-adhln=code.s -g -fverbose-asm -mcrt=nix13 -std=c99 -O1 -fstrength-reduce -fomit-frame-pointer -mtune=68020-60 -c -o code.o code.c`

**Comment by bebbo** [comment]
`-O1` does not provide this optimization

**Comment by darrenfreeman** [comment]
Does that mean it's a new bug? Or am I doing something wrong?

**Comment by bebbo** [comment]
> BTW I'm using -O1 because any higher level results in a crash on startup. I don't know why.
> 
please open a new bug to hunt that startup crash down
