### ISSUE TITLE
g++ produced executable locks amiga

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#16]
```
#include <iostream>

int main() {
  std::cout << "Hello\n";
  return 0;

}

```

compiled with
m68k-amigaos-g++ -O3 -noixemul -o num foo.cpp

locks up amiga (a1200 in fs-uae)

**Comment by bebbo** [comment]
this is strange, uae freezes while debugging very valid code...
... need to test this on a real Amiga

**Comment by alexalkis** [comment]
Yeap, it works again. Fixed!
