### ISSUE TITLE
-O3 and -Ofast break ScummVM debug build

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#169]
Checkout ScummVM from https://github.com/mheyer32/scummvm-amigaos3.git

Configure as
`./configure --host=m68k-amigaos --disable-all-engines --disable-hq-scalers --enable-c++11 --disable-lua --disable-nuked-opl --disable-mt32emu --enable-debug --enable-optimizations  --enable-engine=scumml --disable-iconv --with-amiga-prefix=XXX
`
(note that we enable the debug build _and_ optimizations!)

Now when running the resulting executable and then starting a Monkey Island (I tested the PC VGA version only), you'll see that right at the start of the intro no people or monkeys will get rendered. Weirdly the game can be played to some extent but no characters will be rendered.

The line to manipulate the behavior is in the configure file:

```
			# Use -O3 on the Amiga for optimized builds.
			if test "$_optimizations" = yes; then
				_optimization_level="-O3"
			else
				append_var CXXFLAGS "-Og"
			fi
```
If the optimization level is set to O2, it will work. O3 and Ofast exhibit the bug. Maybe that can help you identify the offending optimization?

I tried `-fbbb=-` with no effect. The release build (`--enable-release`) will weirdly also work.

I have not been able to spend a lot of time on debugging yet, but I suspect some compiler issue which manifests in some of the code compiled for the engines/scumm code.

**Comment by bebbo** [comment]
```
Running ScummVM configure...
error: unrecognized engine: scumml
Try `./configure --help' for more information.
```

**Comment by bebbo** [comment]
using engine scumm:

```
In file included from backends/timer/amigaos3/amigaos3-timer.cpp:3:0:
backends/timer/amigaos3/amigaos3-timer.cpp: In static member function 'static void AmigaOS3TimerManager::TimerTask()':
backends/timer/amigaos3/amigaos3-timer.cpp:103:9: error: invalid use of member 'AmigaOS3TimerManager::_timerMP' in static member function
  assert(_timerMP);
```

**Comment by mheyer32** [comment]
Sorry for the typo! That assert can be removed. I forgot to push to GitHub. The issue should still be reproducible. To clarify: I tested with Monkey Island II

**Comment by bebbo** [comment]
flipping summ/costume.o makes the difference...

**Comment by bebbo** [comment]
`-fno-inline-functions` seems to make the difference

**Comment by mheyer32** [comment]
Preventing ClassicCostumeRenderer::mainRoutine from being inlined makes a difference:
```
__attribute__((noinline))  byte ClassicCostumeRenderer::mainRoutine(int xmoveCur, int ymoveCur) {
...
```

**Comment by mheyer32** [comment]
drawLimbs() should return 2, but returns 0.
drawLimbs() cannot return 0 when going through ClassicCostumeRenderer::mainRoutine(), though. mainRoutine can only return 1 or 2.
I think inlining mainRoutine messes up the return path/ return value somehow.

**Comment by bebbo** [comment]
the `mainRoutine` is able to `return 0;`

e.g.
```
	if (rect.top >= _out.h || rect.bottom <= 0)
		return 0;

	if (rect.left >= _out.w || rect.right <= 0)
		return 0;
```

**Comment by mheyer32** [comment]
Thanks for the inital triage, that helped tremendously!

The inlining is not the root cause per-se. It just shifts the code around a bit so that the code generation will be either ok or faulty.
The faulty code is the in the drawLimb() method, sending the code off to read data from the wrong address. This in turn will corrupt the costume bounding box und thus the following box validation will deem the limbs not visible and so they won't get drawn.

I think the root cause has to do with the optimization that produces addressing modes like this "move.b ([112,a2],d2.l,0),d0".
somehow the compiler may forget that he original statement of [a2+112] should have been stored in a register because it is needed later again.

See the code in drawLimb():
```
// this seems to be the offending line
	frameptr = baseptr + READ_LE_UINT16(_loaded._frameOffsets + limb * 2);
    2404:	286a 007c      	movea.l 124(a2),a4
    2408:	3034 0a00      	move.w (0,a4,d0.l*2),d0
    240c:	e058           	ror.w #8,d0
    240e:	3400           	move.w d0,d2  // this just computed the "READ_LE_UINT16(_loaded._frameOffsets + limb * 2);" part
                                                                // but did it forget to add baseptr and store the result somewhere?                                                                  
                                                               // it also overwrites previously computed d2  that is still needed down below
 is still needed below
	// Determine the offset to the costume data for the limb at position i
	code = _loaded._animCmds[i] & 0x7F;
    2410:	1032 2925 0070 	move.b ([112,a2],d2.l,0),d0 // d2 is the wrong one here
    2416:	0200 007f      	andi.b #127,d0
```

but later down in the code, frameptr's value is actually needed again, but a garbage value is used:
```
	_srcptr = baseptr + READ_LE_UINT16(frameptr + code * 2);
    2426:	747f           	moveq #127,d2
    2428:	c082           	and.l d2,d0
    242a:	d080           	add.l d0,d0
    242c:	3030 0800      	move.w (0,a0,d0.l),d0       //   a0 does not contain 'frameptr', but some random value!
    2430:	e058           	ror.w #8,d0
    2432:	0280 0000 ffff 	andi.l #65535,d0
    2438:	41f3 0800      	lea (0,a3,d0.l),a0
    243c:	2548 0046      	move.l a0,70(a2)
```

forcing a print into the code ala
`
frameptr = baseptr + READ_LE_UINT16(_loaded._frameOffsets + limb * 2);
debug("frameptr: %p", frameptr)
`
Will make it do the right thing.

**Comment by bebbo** [comment]
it also seems to run using  `-fno-peephole2`

**Comment by bebbo** [comment]
and I guess you found the spot where it happens:

without peephole2
```
	move.w d0,d1
	and.l #65535,d3
	move.b ([112,a2],d3.l),d0
	and.b #127,d0
	clr.l d3
	move.b d0,d3
	cmp.b #123,d0
	jeq .L482
	moveq #127,d4
	and.l d4,d0
	add.l d0,d0
	lea (a3,d1.l),a0
```
with peephole2
```
	clr.l d4
	move.w d0,d4
	move.b ([112,a2],d4.l),d0
	and.b #127,d0
	clr.l d3
	move.b d0,d3
	cmp.b #123,d0
	jeq .L482
	moveq #127,d4
	and.l d4,d0
	add.l d0,d0
	add.l d1,a0
```

**Comment by bebbo** [comment]
the assignment to d1 is no longer dropped:

```
	clr.l d1
	move.w d0,d1
	and.l #65535,d3
	move.b ([112,a2],d3.l),d0
```

**Comment by mheyer32** [comment]
Thank you, that fixed it!
