### ISSUE TITLE
-fbbb= output in m68k-amigaos-gcc --help=target bad formated

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#17]
The text of -fbbb part in m68k-amigaos-gcc --help=target output is unreadable because it is bad formated

Linux  4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

![capture](https://user-images.githubusercontent.com/28429123/35616239-f6d1fcee-0674-11e8-8d1d-5b099865db08.PNG)

**Comment by bebbo** [comment]
reduce the width of your terminal :-)

**Comment by githubaf** [comment]
You seem to depend on the terminal with, right? 80 works fine, but who ises so mall terminaly these days?

Wouldn't is be possible to add \n after each line instead of depending on the automatic line-wrap (i.e depending on the actual terminal width? Something like this:

//    "-fbbb=Enable Bebbo's optimizations.                +    enable all optimizations                      a    commute add move instructions                 b    use register for base addresses               c    convert load const and compare into a sub     e    eliminate dead assignments + redundant loads  f    shrink stack frame                            i    use post increment on addresses               m    merge add and move statements                 p    propagate move assignment pairs out of loops  r    register renaming to maybe save registers     s    a strcpy optimization                         v    be verbose                                    V    be very verbose                               x    dump insns                                                                         Default: -fbbb=+ which yields -fbbb=abcefimprs",
    "-fbbb=Enable Bebbo's optimizations.\n"
    "            +    enable all optimizations\n"
    "            a    commute add move instructions\n"
    "            b    use register for base addresses\n"
    "            c    convert load const and compare into a sub\n"
    "            e    eliminate dead assignments + redundant loads\n"
    "            f    shrink stack frame\n"
    "            i    use post increment on addresses\n"
    "            m    merge add and move statements\n"
    "            p    propagate move assignment pairs out of loops\n"
    "            r    register renaming to maybe save registers\n"
    "            s    a strcpy optimization\n"
    "            v    be verbose\n"
    "            V    be very verbose\n"
    "            x    dump insns\n"
    "            Default: -fbbb=+ which yields -fbbb=abcefimprs",

I would have tried that by myself, but what do I have to do to compile/install local changes?

**Comment by bebbo** [comment]
The problem is: there is some wierdo help formatting function and adding LFs does unfortunately not yield the desired effect. The current version is the best result I could achieve...

**Comment by bebbo** [comment]
>I would have tried that by myself, but what do I have to do to compile/install local changes?

You have to edit the file `amigaos.opt`, which contains the amiga command line switches.

**Comment by githubaf** [comment]
Hm,
it's still wrong.
Look ok when terminal is 80, 81 or 82 chars witdh, but distorted from 83 ...

**Comment by MBeijer** [comment]
for me it works now

**Comment by githubaf** [comment]
Yes, now it works and looks beautifilul!
(Tested sucessfully with latest toolchain commit from 28.2.)
