### ISSUE TITLE
32-bit multiplications emit ___mulsi3 with -m68020

### ISSUE THREAD

**Issue by BSzili** [bebbo/gcc#172]
After updating to the latest version of the compiler I noticed that 32-bit multiplications now emit a ___mulsi3 call when -m68020 is specified. Replacing it with -m68030 will turn it back to muls.l again. I made a short example using CE:
http://franke.ms/cex/z/WjfrKz

**Comment by bebbo** [comment]
please test

**Comment by BSzili** [comment]
Looks good now, thanks!
