### ISSUE TITLE
linking with -m68020-40 problem

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#173]
I also tried compiling/linking WCS with -m68020-40 and -m68020-60. Both show the rocks with random colors.
I tried to find an offening C-File but there is none. The difference is in the linking.

I compile all files with a commandline like this:

`m68k-amigaos-gcc -DFORCE_MUIMASTER_VMIN=10 -DAMIGA_GUI -I"/home/developer/Desktop/SelcoGit/3DNature/Amiga" -Os -Wall -c -fmessage-length=0 -funsigned-char -MMD -MP -MF"AGUI.d" -MT"AGUI.o" -o "AGUI.o" "../AGUI.c" -g -noixemul -m68020-40 -mhard-float -fomit-frame-pointer -fbaserel -DSTATIC_FCN=static -DSTATIC_VAR=static -ffast-math -mregparm`

and link finally with

`m68k-amigaos-gcc  -o "WCS"  ./vgl/boards.o ./vgl/clib.o ./vgl/color.o ./vgl/defpal.o ./vgl/dumb.o ./vgl/dumbbitblt.o ./vgl/dumbpoly.o ./vgl/dumbtext.o ./vgl/fontsmall.o ./vgl/pixmap.o ./vgl/wuline.o  ./esp/.metadata/.plugins/org.eclipse.cdt.make.core/specs.o  ./AGUI.o ./BitMaps.o ./Cloud.o ./CloudGUI.o ./ColorBlends.o ./Commands.o ./DEM.o ./DEMGUI.o ./DEMObject.o ./DLG.o ./DataBase.o ./DataOps.o ./DataOpsGUI.o ./DefaultParams.o ./DiagnosticGUI.o ./DispatchGUI.o ./EdDBaseGUI.o ./EdEcoGUI.o ./EdMoGUI.o ./EdPar.o ./EdSetExtrasGUI.o ./EdSetGUI.o ./EditGui.o ./EvenMoreGUI.o ./Foliage.o ./FoliageGUI.o ./Fractal.o ./GenericParams.o ./GenericTLGUI.o ./GlobeMap.o ./GlobeMapSupport.o ./GrammarTable.o ./HelpGUI.o ./HyperKhorner4M-1_gcc.o ./Images.o ./InteractiveDraw.o ./InteractiveUtils.o ./InteractiveView.o ./LWSupport.o ./LineSupport.o ./MUIFloatInt.o ./MakeFaces.o ./Map.o ./MapExtra.o ./MapGUI.o ./MapLineObject.o ./MapSupport.o ./MapTopo.o ./MapTopoObject.o ./MapUtil.o ./Memory.o ./Menu.o ./MoreGUI.o ./Params.o ./ParamsGUI.o ./PlotGUI.o ./RequesterGUI.o ./RexxSupport.o ./ScratchPad.o ./ScreenModeGUI.o ./Support.o ./TLSupportGUI.o ./TimeLinesGUI.o ./Tree.o ./Version.o ./VocabTable.o ./WCS.o ./Wave.o ./WaveGUI.o ./nncrunch.o ./nngridr.o ./sasc_functions.o   -lmui -lm -Wl,-Map=wcs.map,--trace -ldebug  -g -noixemul -m68020-40 -mhard-float -fomit-frame-pointer -fbaserel -DSTATIC_FCN=static -DSTATIC_VAR=static -ffast-math -mregparm`

The program works again ok if I change -m68020-40 to -m68040 in the linker call.
The linker-Mapfiles show that in case of -m68040 files from a libm881 directory are used, in case of -m68020-40 not.
Do I miss a linker option or is there a bug?

Please find attached the two linker map-files.
 
[link_bad.txt](https://github.com/bebbo/gcc/files/7602284/link_bad.txt)
[link_ok.txt](https://github.com/bebbo/gcc/files/7602286/link_ok.txt)

**Comment by bebbo** [comment]
first guess; try to rebuild the libs, if the problem persists: bisect the libs to find the bad lib, then bisect the files provided by that lib...

**Comment by githubaf** [comment]
I'm a bit confused about the correct behavior. Which libraries should be linked? 

I am also confused about the generated code. Should code compiled with -m68020-40 contain floating-point instructions or not?
The man page man ./build-Linux/gcc/gcc/doc/gcc.1 says:
```
      -m68020-40
           Generate output for a 68040, without using any of the new instructions.  This results in code that can run relatively
           efficiently on either a 68020/68881 or a 68030 or a 68040.  The generated code does use the 68881 instructions that are
           emulated on the 68040.

           The option is equivalent to -march=68020 -mtune=68020-40.

...
       -mhard-float
       -m68881
           Generate floating-point instructions.  This is the default for 68020 and above, and for ColdFire devices that have an FPU.
           It defines the macro "__HAVE_68881__" on M680x0 targets and "__mcffpu__" on ColdFire targets.


```
see 
http://franke.ms/cex/z/dM7aza

I guess, the behavior of using using floating-point instructions or not has changed in your compiler-version? Maybe only the manpage needs an update?

But back to topic: 
```
/home/developer/opt/m68k-amigaos_23Nov21/m68k-amigaos/libnix/lib/libb/libm020/libm.a    bad
/home/developer/opt/m68k-amigaos_23Nov21/m68k-amigaos/libnix/lib/libb/libm020/libm881/libm.a   good
```
So libm881 subdirectory is used in good-case.

When I link with 
`-ldebug -g -noixemul -m68020-40 -m68881 -fomit-frame-pointer -fbaserel -DSTATIC_FCN=static -DSTATIC_VAR=static -ffast-math -mregparm`
`instead of -ldebug -g -noixemul -m68020-40 -mhard-float -fomit-frame-pointer -fbaserel -DSTATIC_FCN=static -DSTATIC_VAR=static -ffast-math -mregparm`
i.e. replace -mhard-float by -m68881, WCS works ok again. 

From the manpage I thought -m68881 and -mhard-float are synonyms? This seems not to be true for linking?

**Comment by bebbo** [comment]
> i.e. replace -mhard-float by -m68881, WCS works ok again.
> From the manpage I thought -m68881 and -mhard-float are synonyms? This seems not to be true for linking?

the `mhard-float` was not mentioned in the CPP and LINK specs.

**Comment by bebbo** [comment]
the 2nd issue is a duplicate of #172

**Comment by bebbo** [comment]
And the last issue: if you pickup the wrong lib, then the return values are in d0/d1 and not in fp0.
=> won't work

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
Works as expected now for 68020-40 and 68020-60.
Thank you!
