### ISSUE TITLE
Some "math", "sinus" or "fpu" problem. Maybe bug in "-m68060" or "-ffast-math".

### ISSUE THREAD

**Issue by mateusz83** [bebbo/gcc#178]
Hello,
So far I was using Windows setup.exe version from 22 March 2021.
A few days ago I switched to Windows/WSL-Ubuntu and get the most recent
grom github repository ans "make all" (not ndk 3.2)

On Windows I was using these compiler flags for a long time without issues:
`-Wall -noixemul -O3 -m68060 -mtune=68060 -mhard-float -fomit-frame-pointer -lm`           

After switching to Linux recent version I noticed that up/down movement in my FPS engine
is no longer smooth sin() result. Instead It feels like sin() output is cut or rounded so the movement is no longer smooth
but very jaggy. Please see the example video:
https://www.youtube.com/watch?v=5YxbBHIyQlQ

The code is very simple:
```
#define RC_PLAYER_Z_SPEED           9   
#define RC_PLAYER_Z_MAX             8.0f

float RC_player_z, RC_player_z_accumulation;

{
RC_player_z_accumulation += RC_PLAYER_Z_SPEED * delta_time;
RC_player_z = sinf(RC_player_z_accumulation) * RC_PLAYER_Z_MAX;
}
```

I tried to test different flags, and finally noticed that after adding "-ffast-math" the movement is very smooth again !
`-Wall -noixemul -m68060 -mtune=68060 -mhard-float -ffast-math -O3 -fomit-frame-pointer     `

Unfortunately in my case -ffast-math makes my appliaction not stable and it crashes after while - so I can't use it.

Thank You
in advance.

**Comment by bebbo** [comment]
you have to recompile all once the fix is live.
But your program crashes reliably here:
```
    // Free multi screen buffers.
    if (FRM_mbuf_screen_buffer[0]) FreeScreenBuffer(FRM_screen, FRM_mbuf_screen_buffer[0]);
```
maybe it writes outside the buffer?

**Comment by mateusz83** [comment]
Hi, thank you very much for help.
Should I get it from: `https://franke.ms/download/amiga-gcc.tgz `?
or by `git clone https://github.com/bebbo/amiga-gcc` ?

I tried by` git clone `and` make all `but there was still jagged. Then I download the daily prebuild from link and 
un-tar on linux/wsl - but I get this mesage during compilation: `/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory`

**Comment by bebbo** [comment]
> Hi, thank you very much for help. Should I get it from: `https://franke.ms/download/amiga-gcc.tgz `? 

this get's an update every night

> or by `git clone https://github.com/bebbo/amiga-gcc` ?

and this is usually up to date one hour (building and testing takes its time) after a push to the devel1 branch. 

> I tried by`git clone`and`make all`but there was still jagged. Then I download the daily prebuild from link and un-tar on linux/wsl - but I get this mesage during compilation: `/opt/amiga/libexec/gcc/m68k-amigaos/6.5.0b/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory`

you have missing dependencies, check the https://github.com/bebbo/amiga-gcc/blob/master/README.md and install what's needed to build - that's sufficient to run.

**Comment by mateusz83** [comment]
Hello,
So I tried today again with fresh reinstalled wsl/ubuntu on Windows.

1. I downloaded from `git hub` and `make all`. The sinus is smooth also with '-ffast-math' and without it. I don't know why but that line of code RC_player_z = sinf(RC_player_z_accumulation) * RC_PLAYER_Z_MAX make crash after a two seconds in both cases. Maybe its some bug in my code. When I comment that line I had no crash. I also use sinf() and cosf() in diferent place that works.

2. I also tried with downloading prebuild from *.tgz archive.. but in this case I still I got that problem with` libmpfr.so.4` during compilation. I can't download that package: libmpfr.so.4.

Anyway I try to do something with that line of code.. if no I will just switch back to the 22 march version..

Thanks for help!
Mateusz

**Comment by bebbo** [comment]
that's my built version - with the uncommented line, I mentioned above.
[frm060_128.zip](https://github.com/bebbo/gcc/files/7833798/frm060_128.zip)

It crashes here, if you leave the room and hit the border.

**Comment by bebbo** [comment]
rty this to have movement wíthout using sinf:
```
//        RC_player_z = sinf(RC_player_z_accumulation) * RC_PLAYER_Z_MAX;
		static int index;
		static float f[] = { -1.0, -0.7, -0.3, -0.1, 0.1, 0.3, 0.7, 1.0};
		RC_player_z = f[7 & ++index] * RC_PLAYER_Z_MAX;		
```

**Comment by mateusz83** [comment]
> 

Thanks so much for help!
I like the idea with array instead of sinf()

**Comment by bebbo** [comment]
to verify that your code draws only inside:
- use a drawing rectangle that's smaller than the real screen
- fill the frame initially with a color
- if the frame gets modified, find the cause and fix it.

**Comment by mateusz83** [comment]
Thats a very good trick, I will try that today..
