### ISSUE TITLE
Optimiser behaves funny on <=68030

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#179]
Optimizer trips on this for everything up to 68030.  (68040 also looks funny)

http://franke.ms/cex/z/z66s76

**Comment by bebbo** [comment]
there was no optimizer yet.

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
Works. Thanks for the fix!

**Comment by alexalkis** [comment]
Umm, and this one
http://franke.ms/cex/z/T85GW9

Does 3 multiplies on 68000 and 2 mutliplies in everything else....

**Comment by bebbo** [comment]
> Umm, and this one http://franke.ms/cex/z/T85GW9
> 
> Does 3 multiplies on 68000 and 2 mutliplies in everything else....

the compiler sees only function calls and does no longer know what it's for...
