### ISSUE TITLE
register renaming + dead assignment elimination seems broken

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#18]
When compiling Adoom with -O2 or above, triggering the first secret door in the first level, a crash happens.
I was able to track it down to a function call inside

```
p_doors.c
int EV_DoDoor(line_t* line, vldoor_e type)
{
}
```

in this function you'll notice multiple sequences of this kind:

```
   1e77e:	7001           	moveq #1,%d0
   1e780:	2740 001c      	movel %d0,%a3@(28)
   1e784:	2049           	moveal %a1,%a0
   1e786:	2f49 0028      	movel %a1,%sp@(40)
   1e78a:	2a46           	moveal %d6,%a5
   1e78c:	4e95           	jsr %a5@

```

But looking around, there seems to be no place where d6 is actually assigned. So the jump ends up in nirvana. I believe that the optimizer tried to store a function address into d6 outside the loop.

When enabling verbose -fbbb output, I can see "eliminate dead assign to d6"  which seems to be highly suspicious.
```

:bbb: in 'EV_DoDoor'
:bbb: ENTER
**:bbb: (e) 12: eliminate dead assign to d6**
:bbb: (r) opt_reg_rename a1 -> a0 (3 locs, start at 40)
40 41 43 
:bbb: (r) opt_reg_rename a1 -> a0 (2 locs, start at 83)
83 84 
:bbb: (r) opt_reg_rename a1 -> a0 (2 locs, start at 125)
125 126 
:bbb: inline weight =  119	EV_DoDoor
```

**Comment by mheyer32** [comment]
Btw, you can compile or get assembly code for this particular file via
make p_doors.o
make p_doors.s

**Comment by mheyer32** [comment]
I did some more testing, actually, it looks like the issue is the combination of
-fbbb=er

When these two options are removed, no crash is observed.

**Comment by bebbo** [comment]
it looks like that the jump table for
```
	jmp %pc@(2,d0:w)
```
is not analyzed correctly

**Comment by mheyer32** [comment]
Tested. Works!

Closing.

Awesome: file a bug, go to bed, wake up and have the bug fixed :-D
