### ISSUE TITLE
Question: 68881 without extended

### ISSUE THREAD

**Issue by michalsc** [bebbo/gcc#183]
Hello!

This is actually neither bug report nor feature request. Rather a question if such feature request would be interesting to you or anyone else. Feel free to wontfix-it if you find the idea rubbish :)

On m68k emulators and JIT translators (such as e.g. my Emu68 project) the cost of loading/storing of floating point numbers in extended format may be awfully expensive for architectures such as AArch64 or PPC, where the built-in fpu supports only single and double formats. Would it eventually make sense to expand gcc with a 68881-double architecture, where costs of all extended loads and stores are set to be extremely huge? Such thing would hopefully force gcc to use fmove.d instead of e.g. fmovem.x for saving/restoring registers.

For comparison: double store/load translated from m68k to aarch64 takes **one** single ARM instruction, whereas extended load/store translates to 14 instructions.

**Comment by bebbo** [comment]
please test!

**Comment by michalsc** [comment]
Nice option name :) main branch?

**Comment by bebbo** [comment]
`devel1` branch now - main branch soon if the build system does not complain.

live here: http://franke.ms/cex/z/rf191T

**Comment by michalsc** [comment]
I have also checked IT with my portions of code and it all does look good. Good work! Thanks!

**Comment by Midar** [comment]
I don't think that's a good name for a flag. How about `-mavoid-extended-fp` or `-mextended-fp-is-expensive`?

**Comment by bebbo** [comment]
> I don't think that's a good name for a flag. How about `-mavoid-extended-fp` or `-mextended-fp-is-expensive`?

I don't think that's a good name either...
... there is time to change the name if it gets merged into the main repo :-)
