### ISSUE TITLE
graphics.library is been pulled for (seemingly) no reason 

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#184]
[graphlib.zip](https://github.com/bebbo/gcc/files/9119678/graphlib.zip)

So, if you do
```
m68k-amigaos-gcc -mcrt=nix13 -s -Os -o ami13 -Wall cg.c decl.c expr.c gen.c main.c misc.c opt.c scan.c stmt.c sym.c tree.c types.c
m68k-amigaos-gcc -noixemul -s -Os -o ami20 -Wall cg.c decl.c expr.c gen.c main.c misc.c opt.c scan.c stmt.c sym.c tree.c types.c
m68k-amigaos-gcc -mcrt=nix13 -s -Os -o hello hello.c
```

and you run the executables through vamos, you get:
```
alex[0]@ubvm bug$ vamos hello
Hello world
alex[0]@ubvm bug$ vamos ami13
graphics.library failed to load
alex[20]@ubvm bug$ vamos ami20
graphics.library failed to load
```
Something triggers the inclusion of graphics.library which is not needed.

**Comment by bebbo** [comment]
please try to find such things yourself.
Hints:
 - Don't use `-s`
 - use `-Wl,-M=outfile.map` to create a map file
 - use `m68k-amigaos-objdump -Dr outfile` to search for the symbols 

In your case it's 
```

**Comment by bebbo** [comment]
tip of the day: Don't use variables and functions starting with an uppercase to avoid overlap with AmigaOS stuff.

**Comment by alexalkis** [comment]
It's instantiated in main.

```
#include "defs.h"
#define extern_
#include "data.h"
#undef extern_
#include "decl.h"
#include <errno.h>
#include <unistd.h>
```

**Comment by bebbo** [comment]
> It's instantiated in main.
> 
> ```
> #include "defs.h"
> #define extern_
> #include "data.h"
> #undef extern_
> #include "decl.h"
> #include <errno.h>
> #include <unistd.h>
> ```

No, it isn't. You need some initialization.
Only declared:
```
int x;
```
Instantiated:
```
int x = 0;
```

**Comment by alexalkis** [comment]
I thought globals are instantianted if declared, but I guess that conflicts with the global library trick that the amiga toolchains needs, huh?

**Comment by bebbo** [comment]
Not initialized variables end up as common symbols. If a common symbol is not resolved it ends up in bss.
In this case it gets resolved since `_Text` is defined in `libamiga.a` which then requests `GfxBase`.

**Comment by alexalkis** [comment]
Ok, thanks and sorry for the trouble :)
