### ISSUE TITLE
operands mismatch for bfextu

### ISSUE THREAD

**Issue by BSzili** [bebbo/gcc#187]
I found an issue where the compiler generates a bitfield instruction that doesn't seem to work. I get this error:
> opmm.s: Assembler messages:
> opmm.s:70: Error: operands mismatch -- statement `bfextu (a0)+{#14:#3},d1' ignored

Maybe the post increment is causing this? I uploaded the test case here, the problem happens in the LinkSprite function:
http://franke.ms/cex/z/qP3zhs

**Comment by bebbo** [comment]
thanks for reporting. It's fixed - please test

**Comment by BSzili** [comment]
The problem is now gone, thanks!
