### ISSUE TITLE
Possible integer remainder bug in GCC 68k backend

### ISSUE THREAD

**Issue by matthey7** [bebbo/gcc#19]
The official Amiga 68k Netsurf appears to have a corner case bug when using '%' (remainder). Chris Young is using the bebbo 68k compiler install with all -fbbb optimization options turned off for now. The problematic code comes from http://git.netsurf-browser.org/netsurf.git/tree/utils/hashtable.c in the function hash_get(). The following C line appear to be the problem.

c = h % ht->nchains;

The assembler generated for the 68020 seems to be missing a remainder.

    ...
    move.b d2,d1
    extb.l d1
    eor.l d0,d1
    move.b (a0),d2
    bne.s backward
    move.l a0,d2
    sub.l a2,a2
    move.l d1,d1  ; effectively a NOP which a compiler should never generate
    divu.l (a1),d1  ; divu.l is a division giving quotient with no remainder but "c = h % ht->nchains;" C source calls for a remainder
    move.l (4,a1),a0
    move.l (a0,d1.l*4),a3  ; <- hit is read from here with wrong calculated address for the for loop array
    tst.l a3
    beq.s forward
    ... 

It looks like the compiler tried to generate a divul.l (a1),d1:d1 instruction which gives a remainder and quotient but this is a special case of the instruction (Dr=Dq) which becomes a divu.l (a1),d1. It appears the problem is a corner case as other tests with '%' produced correct code. Compiling Netsurf for the 68000 which uses the Amiga utility.library fixes the problem of missing text in Netsurf. It would be appreciated if the GCC 68k backend code was reviewed for problems with '%', especially when a divul.l should be generated and this instruction's registers could conflict (like Dr=Dq). Thank you.

**Comment by bebbo** [comment]
fix is live - please test

**Comment by chris-y** [comment]
That seems to have fixed it, thanks.

**Comment by matthey7** [comment]
Great! Thanks for the support bebbo. I hope after some more testing that the fix makes it upstream to the main GCC development as it looks like it was their bug and not yours. Issue closed.

**Comment by bebbo** [comment]
ah no - that was my bug

**Comment by matthey7** [comment]
Ok. No problem as long as you fix your bugs. I'm liking the honesty and transparency anyway.
