### ISSUE TITLE
Status on new version of GCC for Amiga?

### ISSUE THREAD

**Issue by AJenbo** [bebbo/gcc#193]
First of all thanks for all the grate work you have done in making GCC work for Amiga. It's been a lot of fun to use it for porting Diablo over.

I'm writing here since I'm a bit unsure of how else to contact you ... let me know if you would prefer some other channel.

I have heard that you are woking on bringing up a newer version of GCC for Amiga. Is there a way for me to track the progress on this? Maybe even try it out? GCC 6.5 is getting a bit old for us since it doesn't have ful C++17 support, so we are looking at bumping our minimum compiler up to GCC 8 for future versions. But we also do not want to drop Amiga support :)

**Comment by bebbo** [comment]
There is the branch `amiga10` which is able to build the toolchain and some programs may even run. But it's still a very early state. Also not all changes and fixes are backported.

But since you asked: it's available now for the public.

There is also an `amiga11` branch, with real ccmode and lra support, which is not  published yet...

> Is there a way for me to track the progress on this?
No idea, if I have the time and mood, I do something for the good old Amiga. But there is no plan for this or that.

**Comment by MBeijer** [comment]
skipping clib2 got me to a point where the toolchain was built at least, but i'm getting errors further down the line when I'm testing the toolchain and compiling zlib:
```
(insn 1229 651 1230 (set (reg:SI 1 d1 [orig:169 len ] [169])
        (lshiftrt:SI (reg:SI 1 d1 [orig:169 len ] [169])
            (const_int 0 [0]))) "/work/dependencies/zlib/deflate.c":1858:13 323 {lshrsi3}
     (nil))
/work/dependencies/zlib/deflate.c: In function 'deflate_stored':
/work/dependencies/zlib/deflate.c:1868:1: error: insn does not satisfy its constraints:
 1868 | }
      | ^
(insn 1229 651 1230 (set (reg:SI 1 d1 [orig:169 len ] [169])
        (lshiftrt:SI (reg:SI 1 d1 [orig:169 len ] [169])
            (const_int 0 [0]))) "/work/dependencies/zlib/deflate.c":1858:13 323 {lshrsi3}
     (nil))
during RTL pass: final
/work/dependencies/zlib/deflate.c:1868:1: internal compiler error: in final_scan_insn_1, at final.c:3036
unrecognized DWARF version in .debug_info at 6
(insn 1229 651 1230 (set (reg:SI 1 d1 [orig:169 len ] [169])
        (lshiftrt:SI (reg:SI 1 d1 [orig:169 len ] [169])
            (const_int 0 [0]))) "/work/dependencies/zlib/deflate.c":1858:13 323 {lshrsi3}
     (nil))
/work/dependencies/zlib/deflate.c: In function 'deflate_stored':
/work/dependencies/zlib/deflate.c:1868:1: error: insn does not satisfy its constraints:
 1868 | }
      | ^
(insn 1229 651 1230 (set (reg:SI 1 d1 [orig:169 len ] [169])
        (lshiftrt:SI (reg:SI 1 d1 [orig:169 len ] [169])
            (const_int 0 [0]))) "/work/dependencies/zlib/deflate.c":1858:13 323 {lshrsi3}
     (nil))
during RTL pass: final
/work/dependencies/zlib/deflate.c:1868:1: internal compiler error: in final_scan_insn_1, at final.c:3036
``` 

this is where zlib is compiled: https://github.com/AmigaPorts/docker-amiga-gcc/blob/master/platforms/m68k-amigaos-gcc10/prep.sh

**Comment by bebbo** [comment]
The branch amiga13.1 seems to be ok now.

**Comment by MBeijer** [comment]
Yeah, this issue can be closed. :)
