### ISSUE TITLE
Question: libatomic missing from amiga-gcc 13.1.1?

### ISSUE THREAD

**Issue by isoriano1968** [bebbo/gcc#203]
Hi,

was doing some tests with cross-compilation using the recently build toolchain and received a meson error on libatomic missing:

Compiler stdout:
 install: /opt/amiga/lib/gcc/m68k-amigaos/13.1.1/
programs: =/opt/amiga/libexec/gcc/m68k-amigaos/13.1.1/:/opt/amiga/libexec/gcc/:/opt/amiga/lib/gcc/m68k-amigaos/13.1.1/../../../../m68k-amigaos/bin/m68k-amigaos/13.1.1/:/opt/amiga/lib/gcc/m68k-amigaos/13.1.1/../../../../m68k-amigaos/bin/
libraries: =/opt/amiga/lib/gcc/m68k-amigaos/13.1.1/:/opt/amiga/lib/gcc/:/opt/amiga/lib/gcc/m68k-amigaos/13.1.1/../../../../m68k-amigaos/lib/m68k-amigaos/13.1.1/:/opt/amiga/lib/gcc/m68k-amigaos/13.1.1/../../../../m68k-amigaos/lib/

Compiler stderr:
 
../meson.build:1173:4: ERROR: C shared or static library 'atomic' not found

Isn't it usually part of gcc? Because you can find it within projects/gcc/libatomic .. so it does not get build by default?

Thanks for clarifying.

**Comment by bebbo** [comment]
run at least `make clean-gcc update-gcc`
then make your goals and libatomic will be there

**Comment by isoriano1968** [comment]
Muchas gracias. 

libatomic now found. As we do not have glibc for AmigaOS he is now complaing on libdl ... will try to find the souce and compile myself.

**Comment by bebbo** [comment]
check this one: https://github.com/BSzili/libdl-hunk

**Comment by isoriano1968** [comment]
And thanks again!

**Comment by isoriano1968** [comment]
I honestly don't want to become a pain in .. sorry .. but

librt is the next one missing, this question thread is becoming a multiple questions thread ... sorry for that.

**Comment by isoriano1968** [comment]
Sorry, just for my understanding of libc the rt functions ar usually part of it, right? I was having a look via m68k-amigaos-nm into libc.a but it looks like it is not part of it. I know that on Solaris we usually use a stub for librt .. would something like this would be possible for amiga-gcc and haing a librt.a?

Thanks
