### ISSUE TITLE
add first support for `clr.q` with 68080

### ISSUE THREAD

**Issue by bebbo** [bebbo/gcc#218]
see https://github.com/bebbo/binutils-gdb/issues/38

see http://franke.ms/cex/z/8hcs6h

**Comment by bebbo** [comment]
@GunnarVB

**Comment by bebbo** [comment]
added peephole to combine
```
        clr.l (40,a0)
        clr.l (44,a0)
```
into
```
        clr.q (40,a0)
```

added peephole for post increments too

**Comment by bebbo** [comment]
please test

**Comment by GunnarVB** [comment]
Excellent!!
This works and compiled now!

Only I see one   "clr.q a0"
CLR on 68k generally not supports An
Can this be done by GCC as SUBA ?

**Comment by bebbo** [comment]
there is no `suba.q` in the binutils asm.

**Comment by bebbo** [comment]
also note that `.q` is not the best extension, since gas would treat `move.q` as `moveq`

**Comment by GunnarVB** [comment]
Hello Bebbo,

About the 68K family.

There is a difference between Address registers and Data Registers and memory.

The Address registers have their own unit which (EA unit) which owns the register and which operates on them.
The EA unit does always do a full An register update.
This means "move.w #0,An" will not set the low word as a Move to DN would do but it will set the whole register to zero.

The 68080 CPU has a 32bit memory space.
Addresses are always 32bit.
Data register are 64bit and can be accessed:
 as byte, word, long, and 64bit.

And memory can be moved,read, written, cleared as 
Byte,Word,Long,Quad,16byte

So for clearing memory , or setting structures to zero this optimization of doing CLR.Q (mem) will be a real performance improvement.
So thanks for enabling this.

I bit confused that the game i compile 1 time in total create an
CLR.Q An
Is this a mistake?
