### ISSUE TITLE
move.l -> moveq + lsl

### ISSUE THREAD

**Issue by erique** [bebbo/gcc#232]
Have you considered the `-Os` optimization changing `move.l #V,dN` to `moveq.l #V>>n,dN + lsl.w #n,dN`, for values where V>>n would fit into 7 bits?

http://franke.ms/cex/z/KeWToj

could instead be represented as
```
  moveq #66,d0
  lsl.w #3,d0
```

(similar to 68080 moviw.l, but with restrictions)

**Comment by bebbo** [comment]
> Have you considered the `-Os` optimization changing `move.l #V,dN` to `moveq.l #V>>n,dN + lsl.w #n,dN`, for values where V>>n would fit into 7 bits?
> 
> http://franke.ms/cex/z/KeWToj
> 
> could instead be represented as
> 
> ```
>   moveq #66,d0
>   lsl.w #3,d0
> ```
> 
> (similar to 68080 moviw.l, but with restrictions)

there is no plan to add this feature.
