### ISSUE TITLE
gcc (amigagcc6) fails to build in one machine

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#238]
This is weird.  Toolchain builds on my main pc and raspberry pi.  Fails on laptop.
Hmm, laptop is the only one upgraded to ubuntu 24.04...

[log.zip](https://github.com/user-attachments/files/17266925/log.zip)

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

```

**Comment by bebbo** [comment]
with that Ubuntu update you reached the point where osx users are since a while...

**Comment by alexalkis** [comment]
Cool, now build in ubuntu 22.04 and 24.04.  Thanks!
