### ISSUE TITLE
gcc 13.2 globals not consistently referenced relative to a4 with -fbaserel and -Os

### ISSUE THREAD

**Issue by cdhooper** [bebbo/gcc#239]
I recently started using gcc 13.2.0 now that libnix4 doesn't seem to link with gcc-6.5 and have run into a problem using -fbaserel and -Os. When code compares variables, the generated code using tst or cmp end up using an absolute address for the reference rather than a4-relative. I am trying to implement code which is ROMable, and this absolutely breaks that since values in a data hunk in ROM can not be updated. This problem does not appear to occur in gcc-6.5.0b.

I reduced the test code to a minimum set which reproduces the issue:
[](http://franke.ms/cex/z/Msxqcj)

You can see that the initial reference to both SysBase and DOSBase are a4-relative, but the later reference to each is not a4-relative (with gcc-13.1.0a). 

The issue is not limited to these. I have globals which are unsigned int and uint8_t which also present with the same problem when they are compared against NULL or each other.

**Comment by bebbo** [comment]
> You can see that the initial reference to both SysBase and DOSBase are a4-relative, but the later reference to each is not a4-relative (with gcc-13.1.0a).

where?

**Comment by bebbo** [comment]
> libnix4 doesn't seem to link with gcc-6.5

could you provide an example?

**Comment by cdhooper** [comment]
Oh, I am very sorry. I forgot to include the link:

http://franke.ms/cex/z/Msxqcj

**Comment by cdhooper** [comment]
I did a fresh clone of the amiga-gcc repo and I am not able to reproduce the issue with building libnix4 there. It must have been something that was not wiped out when I switched compilers. Apologies for mentioning a non-issue with libnix4.

**Comment by bebbo** [comment]
thanks for reporting. I updated the branches 

- https://github.com/bebbo/gcc/tree/amiga13.1
- https://github.com/bebbo/gcc/tree/amiga13.2
- https://github.com/bebbo/gcc/tree/amiga13.3

**Comment by cdhooper** [comment]
I've confirmed that with the patch to 13.2, all global references in my compiled object are now a4-relative. Thank you for this very quick fix.
