### ISSUE TITLE
m68k-amigaos-objdump does not recognize extb.l

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#24]
`extb.l d0`  seems to come out as` lea d0,a4`

**Comment by bebbo** [comment]
uhm, this is a binutil issue - not a gcc one.

the recent binutils are a tad better:
```
GNU objdump (GNU Binutils) 2.29.51.20171029
...
00000000 <.text>:
   0:   49c0            .short 0x49c0
```

**Comment by bebbo** [comment]
you have to specify the cpu:
`m68k-amigaos-objdump.exe -d extb.o -m68040`

```
extb.o:     file format amiga

Disassembly of section .text:

00000000<.text>:
   0:   49c0            extb.l d0
        ...
```

**Comment by mheyer32** [comment]
oh, I didn't know that. Sorry for the trouble! Closing.

**Comment by bebbo** [comment]
didn't know that either, but debugging showed me that check for the cpu ^^
