### ISSUE TITLE
Perfomance regression (vs gcc-3.4.0)

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#26]
[nanojpeg.zip](https://github.com/bebbo/gcc/files/1754708/nanojpeg.zip)

Use this to compile:
m68k-amigaos-gcc -Wall -O3 -D_NJ_EXAMPLE_PROGRAM -noixemul -o nanojpegb nanojpeg.c 
(nanojpega is from gcc-3.4.0)
run it like: 
nanojpegb SusannaHoffsAustralia2008.jpg b.ppm

I get (emulated a1200)
gcc-3.4.0 - 34.58 secs
gcc6 - 38.28 secs
gcc6 (with -fbbb=-) 38.64 secs

(original c source, untouched from here: http://svn.emphy.de/nanojpeg/trunk/nanojpeg/nanojpeg.c )

PS: I used 'csh' shell to get the timings

**Comment by bebbo** [comment]
Hm, I get ~25s for all versions, WinUAE 68020, jit-disabled, cycle-exact

**Comment by alexalkis** [comment]
3mins10secs (gcc-3.4.0) vs 3mins22secs (gcc6) on A500+ with 8mb fast ram.
*shrug*

**Comment by bebbo** [comment]
could you test both with also `-msmall-code`

**Comment by alexalkis** [comment]
34.32 vs 37.92 (back on a1200 again)

**Comment by bebbo** [comment]
what about `-ftree-loop-vectorize`?

**Comment by alexalkis** [comment]
kept the -msmall-code also
34.42 vs 37.74

**Comment by bebbo** [comment]
I get way larger times on my emulated 68000: 6:49 vs 7:13

The code is looking ok to me, but I found one difference:

The gcc-6 compiler utilizes `mulu` instructions, which are not present in the other file.

**Comment by bebbo** [comment]
tweaking the costs yields different results...
... it looks like that the 68k cost model is not correct.

**Comment by bebbo** [comment]
would you please test this file on your system?
[nanojpegf.zip](https://github.com/bebbo/gcc/files/1756596/nanojpegf.zip)

**Comment by alexalkis** [comment]
34.42 vs 37.06

**Comment by alexalkis** [comment]
I think we kind of need to run it on real hardware.  I'll try packaging everything and post on EAB tomorrow.

**Comment by bebbo** [comment]
Ok, the main difference:
- gcc-3.4.0 is inlining everything into `njDecode` even if inline is not specified.
- gcc-6.4.1b behaves different.

add inline to njShowBits:
```static inline int njShowBits(int bits)```
- no change in performance with gcc-3.4.0
- some change in performance with gcc-6.4.1b

**Comment by bebbo** [comment]
no feedback - closing this.

My values:
- 3mins10secs (gcc-3.4.0)
- 2mins42secs (gcc6)
