### ISSUE TITLE
__saveds should save/restore a4

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#27]
In ADoom, there's an input handler function, amiga_video.c video_inputhandler().
This function is a callback that gets called from the OS at an unspecified time.
Since a4 might be in any state at that time, we need to restore the base-pointer into a4, thus qualify the function with __saveds.

The bug is, though, that the function prologue and exit are supposed to save and restore the previous a4. But they don't:

```
 9979 3bac 2F43 0044 	_video_inputhandler:
 9980               		.stabd	46,0,0
 9981               		.stabd	68,0,1645
 9982 3bb0 0802 0003 	.LFBB16:
 9983 3bb4 6700 05FC 		lea (-16,sp),sp
 9984               		fmovem #3,-(sp)
 9985               		movem.l a6/a5/a3/a2/a1/a0/d2/d1/d0,-(sp)    <<<<<<<<<<<< needs to save a4
 9986 3bb8 76FF      	#APP
 9987 3bba 2F43 0048 	| 1644 "amiga_video.c" 1
 9988               			lea ___a4_init,a4
 9989               	#NO_APP
 9990 3bbe 0802 001C 		move.l a0,a2
 9991 3bc2 6600 04BC 		.stabd	68,0,1649
 9992 3bc6 45F9 0000 		move.l a0,d0
 9992      0000 
 9993               		jeq .L738
 9994 3bcc 41EF 003C 		.stabd	68,0,1658
 9995 3bd0 4E92      		lea _xlate_key,a0
 9996               		move.l a0,d2
 9997 3bd2 2942 0020 		.stabd	68,0,1659
 9998               		lea (60,sp),a6
 9999               		lea _D_PostEvent,a5
 10000               		.stabd	68,0,1662
 10001 3bd6 4A6C 03B6 		lea _mouseevent.10261:W(a4),a3
 10002 3bda 6600 01EC 	.L736:
 10003 3bde 4A6C 03B4 		.stabd	68,0,1650
 10004 3be2 6700 0106 		move.b 4(a2),d0
 10005               		cmp.b #1,d0
 10006               		jeq .L742
 10007 3be6 4EB9 0000 		.stabd	68,0,1661
 10007      0000 
 10008 3bec 2400      		tst.w _video_is_using_mouse:W(a4)
 10009               		jeq .L724
 10010               		cmp.b #2,d0
 10011 3bee 222C 03B8 		jeq .L743
 10012 3bf2 B282      	.L724:
 10013 3bf4 6700 00F4 		.stabd	68,0,1689
 10014               		move.l (a2),a2
 10015 3bf8 7003      		.stabd	68,0,1649
 10016 3bfa 2F40 003C 		move.l a2,d0
 10017               		jne .L736
 10018 3bfe 42AF 0048 	.L738:
 10019 3c02 42AF 0044 		.stabd	68,0,1692
 10020               		clr.l d0
 10021 3c06 0802 0004 		movem.l (sp)+,d0/d1/d2/a0/a1/a2/a3/a5/a6 >>>>>>>>>> needs to restore a4
 10022 3c0a 6600 050A 		fmovem (sp)+,#192
 10023               		lea (16,sp),sp
 10024 3c0e 42AF 0040 		rte
```

(Note that the function itself is attributes with __interrupt at the moment... I don't know if that's appropriate)

**Comment by mheyer32** [comment]
Hi bebbo, I left a comment on the patch itself.

**Comment by bebbo** [comment]
I know - I agree that there might be a superfluous a4 push/pop now, but since -fbaserel programs usually use __saveds too, I could live with it.

**Comment by bebbo** [comment]
but that push/pop is optimized away:
```
__far int x;
__interrupt void i() {
  ++x;
}
```
`m68k-amigaos-gcc -fbaserel -fomit-frame-pointer -S i.c -Os`
yields:
```
_i:
        addq.l #1,_x
        rte
```

**Comment by bebbo** [comment]
uh oh, need fix the optimizer too^^

**Comment by mheyer32** [comment]
My point is, it looks like you're looking at the __interrupt attribute solely (thats what the commit message conveys). 
But what if you use a function that is just using __saveds, but no __interrupt? Wouldn't it fall apart again?

**Comment by bebbo** [comment]
__saveds has only an effect if used with -fbaserel(32). And then a4 is always pinned to ___a4_init.
So reloading a4 with ___a4_init, which already has the value ___a4_init does corrupt nothing.

**Comment by mheyer32** [comment]
"And then a4 is always pinned to ___a4_init." is a false assumption.
The whole purpose of __saveds is to support a function being called from some place not aware that a4 acts as one's basepointer and it must not touch a4.

Think of any OS callback. Your function gets called from deep within the OS. a4  does not point to ___a4_init anymore, but your function wants access to your data, so you need to restore a4. At the same time, the calling function expects you to save and restore _its_ a4 value.

http://cahirwpz.users.sourceforge.net/gcc-amigaos/saveds.html

**Comment by bebbo** [comment]
Oh, forgot those callbacks. Ok

**Comment by mheyer32** [comment]
I can now see that __saveds is properly saving and restoring a4 and the function prologue is putting ___a4_init into a4.

Adoom's  -inputhandler function  works now. Thank you very much!
