### ISSUE TITLE
-msmall-code not working with ADoom

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#28]
Out of interest I tried compiling ADoom with -msmall-code. It compiles, links (albeit with a  few linker warnings ala "INFO: using long jump from amiga_main.o to d_main.o:_D_DoomMain").

But when you try to eventually start the executable, it just crashes :-/

Is -msmall-code expected to 'just work' or do I just have wrong expectations?

**Comment by bebbo** [comment]
It's expected to work and i's a binutils issue: the lists generated via stabs were not patched by the linker.

Just pushed a fix.

**Comment by mheyer32** [comment]
Yep, that fixed it. Awesome!

Closing.

**Comment by bebbo** [comment]
Addendum:

the verbose linker output might help you to find an order of the object files with less inserted long jumps.
