### ISSUE TITLE
[Compiler internal error] error: insn does not satisfy its constraints

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#29]
Looks like https://github.com/bebbo/amigaos-cross-toolchain/issues/34 but I think it's a different error.

git clone https://github.com/alexalkis/a68k

m68k-amigaos-gcc -mcrt=nix13 -fbaserel -m68000 -msmall-code -o foo *.c

> Symtab.c: In function ‘SubArgs’:
> Symtab.c:494:1: error: insn does not satisfy its constraints:
>  }
>  ^
> (insn 388 6 75 (set (reg:SI 9 a1)
>         (plus:SI (reg/v/f:SI 2 d2 [orig:32 s ] [32])
>             (const_int 2 [0x2]))) 141 {*addsi3_internal}
>      (nil))
> Symtab.c:494:1: internal compiler error: in final_scan_insn, at final.c:2923
> 0xc33e59 _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
>         /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:108
> 0xc33eb9 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
>         /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:118
> 0x934046 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
>         /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2923
> 0x93235a final(rtx_insn*, _IO_FILE*, int)
>         /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
> 0x936ea9 rest_of_handle_final
>         /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4455
> 0x9370a8 execute
>         /home/alex/t/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4530
> Please submit a full bug report,
> with preprocessed source if appropriate.
> Please include the complete backtrace with any bug report.
> See <http://gcc.gnu.org/bugs.html> for instructions.

**Comment by alexalkis** [comment]
m68k-amigaos-gcc -noixemul -Os  -mcrt=nix13 -fbaserel -m68000 -msmall-code -o foo *.c

is the actual command that brings the error.  Without -Os no internal error (but a lot of linker errors)

**Comment by bebbo** [comment]
>(insn 388 6 75 (set (reg:SI 9 a1)
(plus:SI (reg/v/f:SI 2 d2 [orig:32 s ] [32])
(const_int 2 [0x2]))) 141 {addsi3_internal}
(nil))

This would result in **lea 2(d2),a1**  which is indeed invalid. And yes, it's a different issue.

**Comment by bebbo** [comment]
```
m68k-amigaos-gcc -noixemul -Os -mcrt=nix13 -fbaserel -m68000 -msmall-code -S Symtab.c
```

**Comment by bebbo** [comment]
I removed the attempt to combin the moved insn with the previous one.

Now this code:
```
	...
	addq.l #2,d2

.L22:
	move.l d2,a1
	move.b (a1)+,d0
	move.l a1,d2
	move.b d0,(a2)+
	jne .L22
	move.l a3,a2
	move.l a6,d1

.L23:
	move.l d1,a1
	move.b (a1)+,d0
	move.l a1,d1
	move.b d0,(a2)+
	jne .L23
	...
```

is correctly converted to:
```
	...
	addq.l #2,d2
	move.l d2,a1
.L22:
	move.b (a1)+,(a2)+
	jne .L22
	move.l a3,a2
	move.l a6,d0
	move.l d0,a1
.L23:
	move.b (a1)+,(a2)+
	jne .L23
	...
```

**Comment by bebbo** [comment]
https://github.com/bebbo/amigaos-cross-toolchain is frozen

Please use  https://github.com/bebbo/amiga-gcc.

1. clone https://github.com/bebbo/amiga-gcc
2. cd amiga-gcc
3. make update
4. make all -j4

you may export PREFIX=/what/u/want to specify your prefix.

**Comment by alexalkis** [comment]
Ok, internal error fixed.  The linker errors are "normal"?

**Comment by bebbo** [comment]
what errors?

**Comment by alexalkis** [comment]
m68k-amigaos-gcc -noixemul -Os -mcrt=nix13 -fbaserel -m68000 -msmall-code -o foo *.c

> INFO: using long jump from /tmp/cckabmEj.o to open.o:_close
> INFO: using long jump from /tmp/cckabmEj.o to free.o:_free
> INFO: using long jump from /tmp/cckabmEj.o to remove.o:_unlink
> INFO: using long jump from /tmp/cckabmEj.o to fprintf.o:_fprintf
> INFO: using long jump from /tmp/cckabmEj.o to printf.o:_printf
> INFO: using long jump from /tmp/cckabmEj.o to malloc.o:_malloc
> INFO: using long jump from /tmp/cckabmEj.o to __mulsi3.o:___mulsi3
> INFO: using long jump from /tmp/cckabmEj.o to fflush.o:_fflush
> INFO: using long jump from /tmp/cckabmEj.o to strcat.o:_strcat
> INFO: using long jump from /tmp/cckabmEj.o to open.o:_lseek
> INFO: using long jump from /tmp/cckabmEj.o to clock.o:_clock
> INFO: using long jump from /tmp/cckabmEj.o to __udivsi3.o:___udivsi3
> INFO: using long jump from /tmp/cckabmEj.o to strcmp.o:_strcmp
> INFO: using long jump from /tmp/ccVzRo2H.o to /tmp/cckabmEj.o:_quit_cleanup
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o(.text+0x70):/home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o: multiple definition of `_exit'
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o(.text+0x70):/home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o: first defined here
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o(.text+0xcc):/home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o: multiple definition of `geta4'
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o(.text+0xcc):/home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o: first defined here
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o(.text+0xcc):/home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o: multiple definition of `__restore_a4'
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o(.text+0xcc):/home/alex/gcc6/m68k-amigaos/libnix/lib/libnix/nbcrt0.o: first defined here
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libb/libnix/libnix.a(malloc.o)(.text+0xf8):malloc.o: multiple definition of `__exitmalloc'
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libb/libnix/libnix.a(malloc.o)(.text+0xf8):malloc.o: first defined here
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libb/libnix/libnix.a(malloc.o)(.text+0xc4):malloc.o: multiple definition of `__initmalloc'
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libb/libnix/libnix.a(malloc.o)(.text+0xc4):malloc.o: first defined here
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libb/libnix/libnix.a(malloc.o)(.text+0x0):malloc.o: multiple definition of `malloc'
> /home/alex/gcc6/m68k-amigaos/libnix/lib/libb/libnix/libnix.a(malloc.o)(.text+0x0):malloc.o: first defined here
> collect2: error: ld returned 1 exit status

**Comment by bebbo** [comment]
You must specify only one of
* `-mcrt=nix13`
* `-mcrt=nix20`
* `-noixemul`
otherwise you have the startup file and libs linked twice.

**Comment by alexalkis** [comment]
Oh, thanks didn't know that.

It compiles with -mcrt=nix13 but if you run it you get nothing.

This gives output
m68k-amigaos-gcc -Os -noixemul -o foo *.c

This does not give any output
m68k-amigaos-gcc -Os -mcrt=nix13 -fbaserel -m68000 -msmall-code -o foo *.c

(Just type foo in an amigashell)

**Comment by bebbo** [comment]
Hm, libnix is not well tested for kickstart 13. Please open a ticket there.

**Comment by alexalkis** [comment]
Thanks, will do.

**Comment by bebbo** [comment]
it's related to -msmall-code. The linker does not adjust the entry points for the INIT_LIST properly.

=> instead of calling __initcommandline, the instrcution befor this function is called which is a jump to quit_cleanup...

**Comment by bebbo** [comment]
pushed a fix to binutils

**Comment by alexalkis** [comment]
Umm, works on a1200. Crashes on a500 (guru 0000 0004)
Attached cause it might be my kickstart 
[foo.zip](https://github.com/bebbo/gcc/files/1853730/foo.zip)
1.3 enviroment again

**Comment by bebbo** [comment]
As I wrote, libnix is not well prepared for kick13...

... e.g using AllocVec... which is kick2.0+

**Comment by alexalkis** [comment]
Hmmm, it uses constructs like that

> #if defined(__KICKSTART__) && (__KICKSTART__<=34)
> void * __alloc_vec(unsigned long sz, unsigned long flags);
> void __free_vec(void *);
> #define AllocVec(a,b) __alloc_vec(a,b)
> #define FreeVec(a) __free_vec(a)
> #endif

**Comment by alexalkis** [comment]
Makefile.in in nix13 direcory has the following line
OPTIONS=-I$(srcdir)/../headers $(CFLAGS) -D__KICK13__

Shouldn't that define something like KICKSTART=33 also?

**Comment by bebbo** [comment]
I once started working on it, it's not finished and it's a libnix issue.

**Comment by alexalkis** [comment]
I tried defining __KICKSTART__=34 in Makefile.in.  It goes into the build/xxx/Makefile and I have planted a syntax error inside the "if defined" thing, but everything builds fine.  So the "if defined" is not true for some reason.
Meh.

**Comment by bebbo** [comment]
There is more todo...
... I stopped my attempt since I figured that I first should build the full libnix lib with NDK13 to find all issues. Then I planned to patch the sys-include headers to hide all library functions which are not visible with kick13.
And last write wrappers for the missing functions and pack it into the libnix13.a.
...

**Comment by alexalkis** [comment]
We established this is libnix. Closing this.
