### ISSUE TITLE
Problem with "e" optimization

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/gcc#34]
Some heisenbugs I've got here:

With 'e' optimization enabled, `playerListInit()`'s loop runs more than it should and game hangs. If I uncomment `bobNewInit` or put `logWrite` around them with loop counter printing, everything works fine. `CC_FLAGS = -std=gnu11 $(INCLUDES) -DAMIGA -noixemul -Wall -Wextra -fomit-frame-pointer -O3`

[gsgame_player.c.txt](https://github.com/bebbo/gcc/files/2166040/gsgame_player.c.txt)
[gsgame_player.with-e.S.txt](https://github.com/bebbo/gcc/files/2166057/gsgame_player.with-e.S.txt)
[gsgame_player.no-e.S.txt](https://github.com/bebbo/gcc/files/2166060/gsgame_player.no-e.S.txt)

**Comment by bebbo** [comment]
Thanks for the files - and I found something. In this code sequence
```
	moveq #0,d0
	move.b d2,d0
	move.l d0,d2
```
the last statement is omitted since the mode (byte vs long) is not treated correctly. After
```
	move.b d2,d0
```
the optimizer considers d0 as an equivalent of d2 (which would be true for move.l) and omits the last statement
```
	move.l d0,d2
```

**Comment by bebbo** [comment]
In the last move.l the optimizer determines correctly that it's a new value:
```
	move.l d0,d2
d0=(const_int:SI 72057598332895212 [0x1000000ffffffec])
```
But it's wrong to set the source d2 as an equivalent of d0 with the new value:
```
d2=(const_int:SI 72057598332895212 [0x1000000ffffffec])
```

**Comment by tehKaiN** [comment]
Here's the second one, of which I forgot to post - `mapJsonReadControlPoints()`:

[mapjson.c.txt](https://github.com/bebbo/gcc/files/2167009/mapjson.c.txt)
[mapjson.no-e.S.txt](https://github.com/bebbo/gcc/files/2167010/mapjson.no-e.S.txt)
[mapjson.with-e.S.txt](https://github.com/bebbo/gcc/files/2167011/mapjson.with-e.S.txt)

If I put a log before malform check, everything works fine:

``` c
	for(UBYTE ubCtrlPt = 0; ubCtrlPt < ubControlPointCount; ++ubCtrlPt) {
		UWORD uwTokPoint = jsonGetElementInArray(pJson, uwTokPts, ubCtrlPt);
    logWrite(
			"Token %hu - type: %d\n", uwTokPoint, pJson->pTokens[uwTokPoint].type
		);
		if(!uwTokPoint || pJson->pTokens[uwTokPoint].type != JSMN_OBJECT) {
			logWrite(
				"ERR: Malformed control point: %hhu (%hu => %d)\n",
				ubCtrlPt, uwTokPoint, pJson->pTokens[uwTokPoint].type
			);
			logBlockEnd("mapJsonReadControlPoints()");
			return;
		}
```

**Comment by bebbo** [comment]
same cause:
```
	moveq #0,d2
	move.w d0,d2
	move.l d2,d0
```

**Comment by bebbo** [comment]
please test

**Comment by bebbo** [comment]
https://github.com/bebbo/gcc/commit/0216ea5b260a2f2f04062437c7d44fd49efce66b
https://github.com/bebbo/gcc/commit/1a3ee8384747891fd31582e0f19715f53bfa39f4

**Comment by tehKaiN** [comment]
Everything works now, thanks!
