### ISSUE TITLE
Float/double wrong math

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#35]
Ok, I've been beaten by messy libraries setup on my part, so first things first.

[le.zip](https://github.com/bebbo/gcc/files/2221580/le.zip)

Sorry for the source code, it's a convert from basic :)

Anyways, on Friday a total lunar eclipse will happen. (On 27/7)
If you run the le_bug you'll get 28/7, if you run the le you'll get 27/7

The funny thing is that when I was adding/removing printfs to find where is goes wrong, it was giving the correct display of 27.  Add/remove some more printfs and then 28 and then 27 again.

Finally, I switched to no optimisations and got it steady on 27. (I was using -O3 till then).

the value of variable b (line 109) was changing (by 1) without touching it.

PS: the code runs fine in linux

**Comment by bebbo** [comment]
Are you sure that your libs were build with the latest gcc version?

Find attached the version I built with `m68k-amigaos-gcc -O3  le.c -o le3`

[le3.zip](https://github.com/bebbo/gcc/files/2224613/le3.zip)

**Comment by alexalkis** [comment]
I had built the toolchain either yesterday or the day before.  But I didn't wipe out (clean/clean the prefix).

I'll start with clean and report back.

**Comment by alexalkis** [comment]
All looks good now! :) Sorry for that.
