### ISSUE TITLE
compiler crash when compiling ScummVM with optimizations on

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#36]
I'm attempting to compile ScummVM for Amiga OS3 ( https://github.com/mntmn/scummvm-amigaos3  ), but it fails when one attempts to compile with -O3 or -Ofast

It must have something to do with the -m68030 compiler switch. Take it out and it compiles just fine.

`matze@ubuntu-VirtualBox:~/scummvm-amigaos3$ make common/rational.o
fatal: No names found, cannot describe anything.
    C++      common/rational.o
Using built-in specs.
COLLECT_GCC=m68k-amigaos-g++
Target: m68k-amigaos
Configured with: /home/matze/amigatoolchain/amiga-gcc/projects/gcc/configure --prefix=/home/matze/amigatoolchain/amiga-gcc-out --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/matze/amigatoolchain/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared : (reconfigured) /home/matze/amigatoolchain/amiga-gcc/projects/gcc/configure --prefix=/home/matze/amigatoolchain/amiga-gcc-out --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-nls --with-headers=/home/matze/amigatoolchain/amiga-gcc/projects/newlib-cygwin/newlib/libc/sys/amigaos/include/ --disable-shared
Thread model: single
gcc version 6.4.1b 20180729-214001 (GCC) 
COLLECT_GCC_OPTIONS='-MMD' '-MF' 'common/.deps/rational.d' '-MQ' 'common/rational.o' '-MP' '-Wall' '-v' '-Wextra' '-Wno-unused-parameter' '-Wno-empty-body' '-fno-access-control' '-Ofast' '-Wuninitialized' '-noixemul' '-mcpu=68030' '-m68881' '-fomit-frame-pointer' '-Wno-long-long' '-Wno-multichar' '-Wno-unknown-pragmas' '-Wno-reorder' '-Wpointer-arith' '-Wcast-qual' '-Wshadow' '-Wnon-virtual-dtor' '-Wwrite-strings' '-fno-exceptions' '-fcheck-new' '-D' 'HAVE_CONFIG_H' '-D' 'RELEASE_BUILD' '-D' 'FORBIDDEN_SYMBOL_ALLOW_ALL' '-D' 'DATA_PATH="/usr/local/share/scummvm"' '-D' 'PLUGIN_DIRECTORY="/usr/local/lib/scummvm"' '-D' 'ENABLE_SCUMM=STATIC_PLUGIN' '-D' 'ENABLE_SCUMM_7_8' '-D' 'ENABLE_AGI=STATIC_PLUGIN' '-D' 'ENABLE_AGOS=STATIC_PLUGIN' '-D' 'ENABLE_DREAMWEB=STATIC_PLUGIN' '-D' 'ENABLE_KYRA=STATIC_PLUGIN' '-D' 'ENABLE_LURE=STATIC_PLUGIN' '-D' 'ENABLE_QUEEN=STATIC_PLUGIN' '-D' 'ENABLE_SCI=STATIC_PLUGIN' '-D' 'ENABLE_SCI32' '-D' 'ENABLE_SKY=STATIC_PLUGIN' '-D' 'ENABLE_SWORD1=STATIC_PLUGIN' '-D' 'ENABLE_TINSEL=STATIC_PLUGIN' '-I' '.' '-I' '.' '-I' './engines' '-c' '-o' 'common/rational.o'
 /home/matze/amigatoolchain/amiga-gcc-out/libexec/gcc/m68k-amigaos/6.4.1b/cc1plus -quiet -v -I . -I . -I ./engines -MMD common/rational.d -MF common/.deps/rational.d -MP -MQ common/rational.o -D__HAVE_68881__ -isystem /home/matze/amigatoolchain/amiga-gcc-out/include -isystem /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/libnix/include -Dlibnix -D__libnix__ -D__libnix -D HAVE_CONFIG_H -D RELEASE_BUILD -D FORBIDDEN_SYMBOL_ALLOW_ALL -D DATA_PATH="/usr/local/share/scummvm" -D PLUGIN_DIRECTORY="/usr/local/lib/scummvm" -D ENABLE_SCUMM=STATIC_PLUGIN -D ENABLE_SCUMM_7_8 -D ENABLE_AGI=STATIC_PLUGIN -D ENABLE_AGOS=STATIC_PLUGIN -D ENABLE_DREAMWEB=STATIC_PLUGIN -D ENABLE_KYRA=STATIC_PLUGIN -D ENABLE_LURE=STATIC_PLUGIN -D ENABLE_QUEEN=STATIC_PLUGIN -D ENABLE_SCI=STATIC_PLUGIN -D ENABLE_SCI32 -D ENABLE_SKY=STATIC_PLUGIN -D ENABLE_SWORD1=STATIC_PLUGIN -D ENABLE_TINSEL=STATIC_PLUGIN common/rational.cpp -quiet -dumpbase rational.cpp -mcpu=68030 -m68881 -auxbase-strip common/rational.o -Ofast -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wuninitialized -Wno-long-long -Wno-multichar -Wno-unknown-pragmas -Wno-reorder -Wpointer-arith -Wcast-qual -Wshadow -Wnon-virtual-dtor -Wwrite-strings -version -fno-access-control -fomit-frame-pointer -fno-exceptions -fcheck-new -o /tmp/ccLq5pA4.s
GNU C++14 (GCC) version 6.4.1b 20180729-214001 (m68k-amigaos)
	compiled by GNU C version 4.9.2, GMP version 6.0.0, MPFR version 3.1.2-p11, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "."
#include "..." search starts here:
#include <...> search starts here:
 .
 ./engines
 /home/matze/amigatoolchain/amiga-gcc-out/include
 /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/libnix/include
 /home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/include/c++
 /home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/include/c++/m68k-amigaos
 /home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/include/c++/backward
 /home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/include
 /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/ndk-include
 /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/sys-include
 /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/include
End of search list.
GNU C++14 (GCC) version 6.4.1b 20180729-214001 (m68k-amigaos)
	compiled by GNU C version 4.9.2, GMP version 6.0.0, MPFR version 3.1.2-p11, MPC version 1.0.3, isl version none
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: b2ddec978943eef22adb0f07904623ff
common/rational.cpp: In member function 'int Common::Rational::toInt() const':
common/rational.cpp:261:1: error: unrecognizable insn:
 }
 ^
(insn 22 11 12 (parallel [
            (set (reg/i:SI 0 d0)
                (div:SI (reg/i:SI 0 d0)
                    (mem:SI (reg/f:SI 8 a0 [orig:34 this ] [34]) [1 this_2(D)->_denom+0 S4 A16])))
            (set (reg:SI 1 d1 [37])
                (mod:SI (reg/i:SI 0 d0)
                    (mem:SI (plus:SI (reg/f:SI 8 a0 [orig:34 this ] [34])
                            (const_int 4 [0x4])) [1 this_2(D)->_denom+0 S4 A16])))
        ]) -1
     (nil))
common/rational.cpp:261:1: internal compiler error: in extract_insn, at recog.c:2293
`

[rational.txt](https://github.com/bebbo/gcc/files/2256141/rational.txt)

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
Works! Closing.
