### ISSUE TITLE
Guru with -fbbb=z

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#37]
get https://www.lua.org/ftp/lua-5.3.5.tar.gz
tar xvf the thing.
cd lua-5.3.5/src
make generic CC=m68k-amigaos-gcc CFLAGS="-O3 -fbbb=abcsefilmprz -fomit-frame-pointer" AR="m68k-amigaos-ar r" RANLIB=m68k-amigaos-ranlib LDFLAGS="-noixemul -s"
if you remove the 'z' it runs ok, with 'z' you get Guru 8000 0005
(A1200 3.1)

I tried updating the toolchain a few mins ago but libnix is breaking the build, so it's about a week's old (the toolchain)

make[3]: *** [extra/allocvec.o] Error 1
make[3]: Leaving directory '/home/alex/t/amiga-gcc/build/libnix/lib/nix13'
/home/alex/t/amiga-gcc/build/libnix/sources/Makefile:38: recipe for target 'nix13' failed

**Comment by bebbo** [comment]
caused by an incorrect conversion:
```
	moveq #0,d0
	add.l d0,20(a4)
```
to
```
	clr.l 20(a4)
```

=> added the missing check that there is no operation (it's a move).

fixed in my development snapshots

**Comment by bebbo** [comment]
fix is in the repo

**Comment by alexalkis** [comment]
Issue persists.  
with 'z' you get Guru 8000 0005

**Comment by bebbo** [comment]
no need to clean everything.
```
make update
make gcc
```
is enough

**Comment by alexalkis** [comment]
I can't believe I forgot to 'make update'.  Sorry.

Issue fixed! Thanks
