### ISSUE TITLE
Amiga specific attributes getting ignored

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#4]
```
void REGARGS (*c2p)(REG(a0, const UBYTE* chunky),
    REG(a1, UBYTE* raster),
    REG(a2, const UBYTE* chunky_end)) = NULL;

amiga_video.c:68:5: warning: `__regparm__' attribute only applies to functions [-Wattributes]
     REG(a2, const UBYTE* chunky_end)) = NULL;


static UWORD CHIP emptypointer[] = {
    0x0000, 0x0000, /* reserved, must be NULL */
    0x0000, 0x0000, /* 1 row of image data */
    0x0000, 0x0000 /* reserved, must be NULL */
};

amiga_video.c:148:1: warning: ‘__chip__’ attribute directive ignored [-Wattributes]
 CHIP static UWORD emptypointer[] = {
 ^~~~


static struct InputEvent* SAVEDS INTERRUPT REGARGS video_inputhandler(REG(a0, struct InputEvent* ie),
                                                                      REG(a1, APTR data));
amiga_video.c:164:71: warning: ‘__saveds__’ attribute directive ignored [-Wattributes]
                                                                       REG(a1, APTR data));
                                                                       ^~~

static void SAVEDS INTERRUPT video_flipscreentask(void)
{
}

amiga_video.c:399:1: warning: ‘__saveds__’ attribute directive ignored [-Wattributes]
 {
 ^


```

**Comment by bebbo** [comment]
__saveds is now supported

**Comment by mheyer32** [comment]
The __saveds warnings are now gone. I don't know if it actually works, though. I still have to figure out how to properly link adoom.

__chip related warnings are still seen. I could work around it by allocating chipram dynamically, but of course compiler support is preferred :-)

Btw, the '__regparm__' related warning I mentioned in the first comment relates to a function pointer.

**Comment by mheyer32** [comment]
I believe, using __saveds on functions no leads to a linker error:
`amiga_video.o(.text+0x112):amiga_video.o: undefined reference to `__init_a4'`

I don't know which library I need to link against that would provide this symbol.

**Comment by bebbo** [comment]
my fault...

the correct name is ```__a4_init```

which is provided yb the baserel startup files nbcrt0.o or nlbcrt0.o

**Comment by bebbo** [comment]
The problem with the chip attribute is: the current aout object format does not support such a segment. So I have to reactivate the amgahunk object format.

the regparm attribute tells the compiler to automatically choose register variables. If all parameters are hard coded register variables, it has no effect.

**Comment by mheyer32** [comment]
Your latest commit did the trick. The linker error went away with it.

**Comment by bebbo** [comment]
great to head. The amigahunk format is starting to work but there are many subsequent issues to fix...
... I'm not giving up yet!

**Comment by bebbo** [comment]
Some more info:

Why it will take very long to implement this.

1. It's easy to put chip variables into a separate section
2. But the aout format does not support such sections
3. The Amiga hunk format has support for these sections
4. But the existing assembler does not work out of the box with amiga hunk.
5. Once Amiga hunk output is generated the linker is the next problem:
  gcc uses stabs for stabs initializers but the Amiga hunk linker does not know that.

so the tasks:
1. make gas work properly to create amiga hunk output.
2. put the stabs into the hunks.
3. make the linker read the stabs info and process it.

1. and 2. is working in most cases.
3. not started

**Comment by bebbo** [comment]
added support for
```
__chip // put the variable into chip memory
__fast // put the variable into fast memory
__far // never use baserel addressing
```
please test

**Comment by mheyer32** [comment]
Will the new attributes work with the standard linker format or is Amiga hunk format required? 
If so, how to enable hunk format for object files?

**Comment by bebbo** [comment]
If you build the toolchain with the version from today (2017-12-21) you'll get a binutils package containing a new m68k-amigaos-as version which creates *.o files in amiga hunk format. Also all other binutils do handle the amiga hunk format.

Q: How to enable?
A: Build the recent tool chain!

**Comment by mheyer32** [comment]
Ok, this means I'll have to switch to hunk for VASM as well. 

Thanks, keep up the good work! We're close to having a really good modern toolchain for the Amiga :-D

**Comment by bebbo** [comment]
you can still link aout objects but those can't contribute to chip/fast/far sections

**Comment by mheyer32** [comment]
To understand correctly, now all symbols should automatically have a 16bit relocation in -fbaserel mode; unless __far is specified? 

I checked out the latest compiler, build the toolchain with -xbuild. 
I am seeing alot of complaints from the linker complaining about symbols coming from the runtime libs... I guess I'll have to do a clean rebuild for the whole toolchain. I'll do some more testing tonight and come back to you.

**Comment by bebbo** [comment]
yes - all data symbols are having are using 16bit(a4) addressing with -fbaserel unless __far, __fast or __chip is specified. (const data may end up in the text segment and thus is not addressed via a4)

And a clean build is recommended.

**Comment by gregthecanuck** [comment]
Just a quick note to say "THANKS!" for all your hard work on gcc 6. Very much appreciated.

**Comment by mheyer32** [comment]
Closing. The issues I saw were related to running out of relocation space.
