### ISSUE TITLE
64bit math

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#48]
`#include <stdio.h>
#include <stdlib.h>

typedef unsigned long long u64;

u64 fib(int n)
{
    if (n==1 || n==2)
       return 1;
    return fib(n-1)+fib(n-2);
}

int main(int argc, char *argv[])
{
  int inp;
  if (argc==2) {
    inp = atol(argv[1]);
  } else {
    inp = 10;
  }
  printf("%lld\n", fib(inp));
  return 0;
}
`

Compile with: m68k-amigaos-gcc -noixemul -O2 -o print64 print64.c
gives wrong result on argument 5 (correct for 1-4)
If you add -lm at the end, doesn't work correctly for any argument.

With -O0 seems to be correct.

**Comment by bebbo** [comment]
uhm - it's working here in any combination

**Comment by bebbo** [comment]
please attach your asm files

**Comment by alexalkis** [comment]
Hmm, I git pulled, make update and works now.
Sorry for that.
