### ISSUE TITLE
resident programs crashes

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#49]
The compiled program just crashes. Did I do anything wrong or is resident code broken?

```
/*
~/opt/m68k-amigaos_06Dec18/bin/m68k-amigaos-gcc test.c -o test -resident -O2 -Wl,-Map=test.map,--trace -noixemul -s
*/

#include <stdio.h>

int main(void)
{
printf("Hello World\n");
return 0;
}
```

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
I tested with your last commit from Dec 14th

My program became generally much smaller compared to gcc from Dec, 6th How did you achieve that?

6.Dez,
60748-msmall-code
54348 -msmall-code -fbaserel

14.Dez
53156 -msmall-code
47320 -msmall-code -fbaserel

But now I get another problem. I compile with -msmall-code -fbaserel -resident and link with -fbaserel -resident.

I get two linker errors
undefined reference to `__restore_a4`

The source lines the linker complains about are
VOID __saveds SamAudioTask_AHI(VOID)
VOID __saveds SamAudioTask(VOID)

The __saveds was necessarry for -fbaserel, otherwise the code crashed when compiled with -fbaserel.

What can I do about that?

**Comment by bebbo** [comment]
> What can I do about that?

`-resident` uses a4 as `-fbaserel`, the code segment is shared and the data segment is copied into some allocated memory. The reference to that allocated memory is kept in a4.

Once a4 is lost or missing - there is no standard way to retrieve it.

You might be able to provide you own `__restore_a4` function using the user ptr in the task structure.

**Comment by githubaf** [comment]
>What can I do about that?
Seems to be my problem then. I just re-read the SAS/C manual for __saveds.
Thanks for your suggestion, will try in that direction.

The issue is solved, the test program can be started, made resident and started, removed from resident programs and so on.

**Comment by mheyer32** [comment]
If you take a look at the various resident startup codes, you'll find
[https://github.com/bebbo/libnix/tree/master/sources/startup](https://github.com/bebbo/libnix/tree/master/sources/startup)

That they have a comment saying 

> | Problem: geta4()
| I really don�t know how to implement it with multiple starts

If you look further, you'll find a code segment that creates a copy of the data segment  and stores the pointer of that copy into a4:
```
		lea	___a4_init-0x7ffe,a5
		movel	d5,d0
		movel	a5,a0
		movel	a4,a1
		jsr	a6@(_LVOCopyMemQuick:W)
		lea	___datadata_relocs,a0
		movel	a0@+,d0
		beq	no_reloc
		movel	a5,d1
		subl	a4,d1
do_reloc:	movel	a0@+,a1
		subl	d1,a4@(a1:l)
		subql	#1,d0
		bne	do_reloc
no_reloc:	lea	a4@(0x7ffe:W),a4

```

The problem is, that this pointer is stored nowhere else, so __restore_a4() cannot be implemented in the standard way, as the pointer to the datasegment copy is not stored anywhere except once placed into a4 upon startup.
You would need to find a way to somehow save the a4 pointer along with the execution context of each instance of your resident program.

Maybe the Task structure's 
`     APTR        tc_UserData;    /* per task data */`

Could be used for that? And then you'd need to write a __restore_a4() function that quickly looks up Exec, calls FindTask(NULL), retrieves tc_UserData and stores that into a4. If you do that, __saveds will work again.

**Comment by mheyer32** [comment]
Oups, thats what Bebbo said already....

**Comment by bebbo** [comment]
:-)

**Comment by githubaf** [comment]
Thank for the suggestions.

> Maybe the Task structure's
> APTR tc_UserData; /* per task data */
>  
> Could be used for that? And then you'd need to write a __restore_a4() function that quickly looks up Exec, calls FindTask(NULL), retrieves tc_UserData and stores that into a4. If you do that, __saveds will work again.

But how could I write to tc_UserData of the new task? I use CreateNewProcTags() and there seem to be no TAG to pass a values or a pointer to tc_UserData. If I just try to copy the parents task A4 to tc_UserData of the new task it is probably already to late because __restore_a4() was already called?

**Comment by bebbo** [comment]
just some thoughts and untested... but it compiles
```
#include <dos/dosextens.h>
#include <dos/dostags.h>
#include <exec/tasks.h>
#include <proto/dos.h>
#include <proto/exec.h>

// put tha a4 reg into my task
void __save_a4() {
  struct Task * task = FindTask(0);
  register APTR * userptr asm("a0") = &task->tc_UserData;
  asm("move.l a4,(a0)");
}

// load a4 from my task	
void __restore_a4() {
  // do not use ExecBase via a4 yet
  struct Library * SysBase = *(struct Library **)4;
  struct Task * task = FindTask(0);
  register APTR * userptr asm("a0") = &task->tc_UserData;
  asm("move.l (a0),a4");
}

// get a4 helper
ULONG __get_a4() {
  asm("move.l a4,d0");
}

__regargs void startProc(int cmdlen, void * cmdline) {
  // do not use ExecBase via a4 yet
  struct Library * SysBase = *(struct Library **)4;
  struct Task * task = FindTask(0);
  task->tc_UserData = (APTR)((struct Process *)task)->pr_CES;
  __restore_a4();
  
  // now fix CES to zero or allocate something or ...
  ((struct Process *)task)->pr_CES = 0;
}

void foo() {
  CreateNewProcTags(
  NP_Entry, (ULONG )startProc, 
  // ...
  // abuse NP_error to pass a4
  NP_Error, __get_a4(), TAG_DONE, 0);
}
```

**Comment by githubaf** [comment]
Thanks for the input! I got it working now :-)
The first thing I forgot was that I cannot use the global variable execbase but need to use address 4 instead.

Two comments:
Using NP_error/pr_CES did not work. pt_CES was always 0. (Tested with OS3.9) According to the Guru-Book  NP_error is not yet implemented... So I used np_Input/pr_CIS instead. All looks a bit illegal but it works.

my new tesk now begins with
```

{
		// do not use ExecBase via a4 yet
		  struct Library * SysBase = *(struct Library **)4;
		  struct Task * task = FindTask(0);
		  task->tc_UserData = (APTR)((struct Process *)task)->pr_CIS;  // the main task put a4 via NP_ERROR into pr_CES
		  __restore_a4();                                              // get A4 from there. Now we can access static and global data via A4 !

		  // now fix CIN to zero or allocate something or ...
		  ((struct Process *)task)->pr_CIS = 0;
	}


```
Then I had issues with your __restore_a4() Function. I changed it to

```
// load a4 from my task
void __restore_a4() {
  // do not use ExecBase via a4 yet
  struct Library * SysBase = *(struct Library **)4;
  struct Task * task = FindTask(0);
  asm("\tmove.l %0,a4 ;\n"
		:                             /* output */
		: "r" (task->tc_UserData)     /* input  */
  	 );
}

```
Thanks again!
