### ISSUE TITLE
-pg and -fbaserel incompatible?

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#50]
I'm getting below error messages, is this to be expected?

/home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/bin/ld: gmon.o: baserelative text relocation to "__stext"
doomsound_midi.library: .text reloc for __stext is out of range: 00000000
/home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/bin/ld: gmon.o: baserelative text relocation to "__stext"
doomsound_midi.library: .text reloc for __stext is out of range: 00000000
/home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/bin/ld: gmon.o: baserelative text relocation to "__stext"
doomsound_midi.library: .text reloc for __stext is out of range: 00000000
/home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.4.1b/../../../../m68k-amigaos/bin/ld: gmon.o: baserelative text relocation to "__etext"
doomsound_midi.library: .text reloc for __etext is out of range: 00000000

**Comment by bebbo** [comment]
the answer is: YES, not compatible.

**Comment by mheyer32** [comment]
Ah, bummer. Care to elaborate why? Thanks!

**Comment by bebbo** [comment]
please try again

**Comment by mheyer32** [comment]
Closing.
