### ISSUE TITLE
-flto leads to internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#55]
I tried compiling+linking githubaf/SAM with the new option -flto with the toolchain from Jan 14th. The linking stage  chrashed.
Tested on Ubuntu 16.04.5 LTS

```
/home/developer/opt/m68k-amigaos_14Jan19/bin/m68k-amigaos-gcc  -o sam reciter.o sam.o debug.o endian.o sdlwrapper.o portaudio_audev.o render.o render000.o render020.o main.o portaudio_ahidev.o  portaudio.o  subtask_support.o amiga_version.o stopwatch.o -g -noixemul -m68000 -Wl,-Map=sam.map,--trace -ldebug  -resident -flto
src/render2.c:38:22: warning: type of 'sampledConsonantFlags' does not match original declaration [-Wlto-type-mismatch]
 extern unsigned char sampledConsonantFlags[256];
                      ^
src/RenderTabs.h:88:15: note: array types have different bounds
 unsigned char sampledConsonantFlags[] =
               ^
src/RenderTabs.h:88:15: note: 'sampledConsonantFlags' was previously declared here
src/amiga/portaudio/portaudio_ahidev.c: In function 'Pa_CloseStream_ahidev':
src/amiga/portaudio/portaudio_ahidev.c:785:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /home/developer/opt/m68k-amigaos_14Jan19/bin/m68k-amigaos-gcc returned 1 exit status
compilation terminated.
collect2: fatal error: lto-wrapper returned 1 exit status
compilation terminated.
Makefile.amiga:52: recipe for target 'sam' failed
make: *** [sam] Error 1

```

**Comment by bebbo** [comment]
please test - I could compile and link SAM with -flto and the size is ~20% smaller. But I did not test it :-)

**Comment by githubaf** [comment]
The linker does no longer crash. OK.
But the sam executable does :-(

Do I have to do anything else except compiling and linking with -flto?
Do I need to compile libnix with -lto as well? Or would it make sense?

If you want to try sam, just enter
sam Hello
No other requirements, standard stack.

**Comment by githubaf** [comment]
Sure. Will do on Monday.

**Comment by bebbo** [comment]
### update
this one is working:
```sam -wav hello.wav Hello```
and it's also working using -flto^^

**Comment by githubaf** [comment]
I compiled the stuff from github with your toolchain from Jan, 15th, playing with the compiler and linker flags. Tested on WinUAE with plain A500 config.

sam Hello

It seems that the only the combinaton resident, smallcode and flto crashes. The other variants (flto alone or combined with either smallcode or resident) seem to work.

What makes me wonder is that -flto combined with smallcode leads to many "INFO: using long jump" wich were not there without -flto.
Is the insertion of the long jumps now done before optimization? (Because optimization is postponed by the flto flag?


Please see the attached Makefiles and executables
[sam_variants.tar.gz](https://github.com/bebbo/gcc/files/2778414/sam_variants.tar.gz)

**Comment by bebbo** [comment]
ok - my Amiga is missing something since no 'ok' version is running without using `-wav`. I'd expect an error message, if something is missing...

the crashing combination has wrong `___datadata_relocs` ...

**Comment by bebbo** [comment]
ok - __datadata_relocs has an alignment of 4 - not 8^^. binutils are updated according to.

> What makes me wonder is that -flto combined with smallcode leads to many "INFO: using long jump" wich were not there without -flto.
Is the insertion of the long jumps now done before optimization? (Because optimization is postponed by the flto flag?

inserting long jumps is still done when linking. Maybe the section order is different using -flto.

please test
