### ISSUE TITLE
Coverage does not work anymore

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#58]
With recent toolchain coverage does not work any longer.

The last toolchain I found working is from January 11th
The next toolchain from 14th of January does not work any more.

I used SAM to produce coverage information.
Compilation produces *.gcno-Files with both toolchains.

Running the program (compiled with 14.th Jan toolchain) does however not produce *.gcda-Files.
Running the program (compiled with 11.th Jan toolchain) produces *.gcda-Files.

The Makefile.amiga is as on github with following lines enabled additionally:

#coverage
CFLAGS += -fprofile-generate=VBox:$(shell pwd | cut -c2-)  # remove first "/" from pwd -> VBox:home/...
CFLAGS += -ftest-coverage
CFLAGS += -fprofile-arcs      #-pg  # Profiler
LFLAGS += -lgcov

**Comment by bebbo** [comment]
since the comment of __gcov_init reads
`Invoked automatically when running an object file's global ctors.`
and CTORS stuff is fixed now, this should work too.

please test

**Comment by githubaf** [comment]
Back from vacation I tested today with your last commit from yesterday.
First tests with SAM and coverage did not work at all, program hangs somewhere at the beginning(?) and did never finisch nor return.

Without coverage enabled SAM works as before.

**Comment by githubaf** [comment]
More test results, still testing SAM with coverage as described above
sam -wav hello.wav Hello, my name is sam. 1 2 3 4 5 6 7 8 9 0

Latest commit from 
04.Feb OK
07.Feb OK
10.Feb BAD. sam prints "Los..." (the first print in the program) and then hangs
12.Feb OK

So "right now" coverage is working...

**Comment by bebbo** [comment]
guess I could need a reliable automated test for this...

**Comment by githubaf** [comment]
I pushed my current files.
Changed OMPILER_INSTALL_DIR  as you suggested to ?=
New Makefile-Target coverage

coverage compiles with coverage, runs a little test via vamos and checks, if reasonable coeverage has been produced.
