### ISSUE TITLE
clib2 crashing in sprintf

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#6]
My attempt to get ADoom running with the gcc6 toolchain now got stuck in a runtime error that I tracked down to apparently sprintf crashing:

Repro:
Compile & execute the following:

`m68k-amigaos-gcc  -mcrt=clib2 -fbaserel -m68030 -m68881 -Os -Wall -fomit-frame-pointer -fomit-frame-pointer -Wimplicit -Wno-strict-prototypes -Wno-int-conversion -o hello-stdio.clib2 hello-stdio.c`

with

```
#include <stdio.h>
#include <string.h>

int VERSION = 110;

int main()
{
    int             p;
    char            file[256];
    char            title[128];


    printf ("success 9!\n");


        sprintf (title,
                 "                         "
                 "The Ultimate DOOM Startup v%i.%i"
                 "                           ",
                 VERSION/100,VERSION%100);

    printf ("success 10!\n");

    printf ("%s\n",title);

  return 0;
}
```

The executable will either get stuck in sprintf and crash eventually or crash pretty much immediately.

**Comment by bebbo** [comment]
not sprintf is crashing, it's __udivsi4 provided by clib2.

So I consider this a clib2 bug.

**Comment by mheyer32** [comment]
So, this means the toolchain will need to get an update? Is there something I can do in meantime?

**Comment by bebbo** [comment]
workaround: include all files which are linked form libgcc into your project.

**Comment by bebbo** [comment]
multilib is now enabled, please test

**Comment by mheyer32** [comment]
Cool!
I tested. I am getting past this function.
Its crashing somewhere else now, farther down the road, but I believe this issue can be closed.

**Comment by mheyer32** [comment]
The latest Jan. 24th changes made sprintf crashing again (pretty badly with a guru meditation).
You can use the same example to verify.

**Comment by mheyer32** [comment]
This commit broke it:

commit 105ee01fca666b47b0efeeaf119bcca79a386c61
Author: bebbo <bebbo@bejy.net>
Date:   Wed Jan 24 18:13:27 2018 +0100

    check def not use to shrink the stack frame

**Comment by mheyer32** [comment]
A wild guess: could fiddling with the stack frame interfere with vargs?

**Comment by mheyer32** [comment]
If you compare the broken vs the working assembly you'll notice that a few functions (<___slab_exit>, <_memmove>:) omit to save a5 on the stack even though they're using it.

[broken.txt](https://github.com/bebbo/gcc/files/1663100/broken.txt)
[working.txt](https://github.com/bebbo/gcc/files/1663101/working.txt)

**Comment by bebbo** [comment]
ok, please test
```
000003a0 <___slab_exit>:
 3a0:   48e7 0036       moveml %a2-%a3/%a5-%a6,%sp@-
 3a4:   4a6c 00f0       tstw %a4@(240)
                        3a6: DREL16     .bss
 3a8:   675c            beqs 406 <___slab_exit+0x66>
 3aa:   47ec 0000       lea %a4@(0),%a3
                        3ac: DREL16     .bss
 3ae:   4bec 00cc       lea %a4@(204),%a5
                        3b0: DREL16     .bss
```

**Comment by mheyer32** [comment]
It's fixed. Thanks! Closing.

It might be a good idea to do automatic regression testing. 
Are you aware of https://github.com/sebastianbergmann/docker-execute-amiga  ?
Could that be used to setup an automatic mechanism that runs the current toolchain through a series of tests?
