### ISSUE TITLE
Compiler is overly cautious with unaligned memory accesses

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#61]
This is not a bug per se but something that could be improved upon.

ScummVM is using constructs like the following to allow reading ints/shorts from unaligned memory addresses (and also to converted from LE to BE or the other way around):

```
	FORCEINLINE uint32 READ_UINT32(const void *ptr) {
		struct Unaligned32 { uint32 val; } __attribute__ ((__packed__, __may_alias__));
		return ((const Unaligned32 *)ptr)->val;
	}
```

The comment above says:

> // Functions for reading/writing native integers.
> // They also transparently handle the need for alignment.
> 
> // Test for GCC >= 4.0. These implementations will automatically use
> // CPU-specific instructions for unaligned data when they are available (eg.
> // MIPS). See also this email thread on scummvm-devel for details:
> // <http://thread.gmane.org/gmane.games.devel.scummvm/8063>
> //
> // Moreover, we activate this code for GCC >= 3.3 but *only* if unaligned access
> // is allowed.

On Amiga this produces a sequence of individual byte reads and bit shifts/rotations, but I believe this is not necessary on 68020 and up, is it? We could instead just read straight from unaligned addresses.
I was able to work around it by disabling the above code section; ScummVM will then use regular reads to do the reads:

```
	FORCEINLINE uint32 READ_UINT32(const void *ptr) {
		return *(const uint32 *)(ptr);
	}
```

**Comment by bebbo** [comment]
```
The MC68020/EC020 architecture supports byte, word, and long-word operand transfers
to any 8-, 16-, or 32-bit data port, regardless of alignment. This feature allows the
programmer to write code that is not bus-width specific. When accessed, the peripheral or
memory subsystem reports its actual port size to the controller, and the MC68020/EC020
then dynamically sizes the data transfer accordingly, using multiple bus cycles when
necessary.
```

you might use an `#ifdef` ...

**Comment by mheyer32** [comment]
Correct, that's what I did.
This is more a general thing: if other code bases use a similar way to access seemingly unaligned data, it might produce suboptimal code on 68020+.

As I said, this is not a bug and does not need immediate fixing, but an observation to keep in mind.  My guess is that the __packed__ attribute causes the compiler to assume potentially unaligned data and thus it starts to emit the individual byte-reads. 

Maybe just label it as enhancement to keep around for a rainy day ;-)

**Comment by bebbo** [comment]
please patch your local gcc source and try this code in gcc/stor-layout.c:525

```
unsigned int
get_mode_alignment (machine_mode mode)
{
#ifdef TARGET_AMIGA
  if (!TUNE_68000 && !TUNE_68010)
    return 8;
#endif
  return MIN (BIGGEST_ALIGNMENT, MAX (1, mode_base_align[mode]*BITS_PER_UNIT));
}
```
don't have time atm

**Comment by bebbo** [comment]
better wait until I have time^^

**Comment by bebbo** [comment]
please test^^ local test was successfull:

**Comment by mheyer32** [comment]
I can see that the individual byte reads are gone, but something's not kosher with it. 
For some reason it messes up palette handling in ScummVM... but only that(?); the game still runs fine - it just looks odd.

Question: will this affect the native alignment requirements for variables, struct members etc? If so, then this is not want you'd want. Natural alignment is still a good thing! Albeit not illegal, unaligned access gets performance penalties, so we do want struct members, variables on the stack etc. aligned.

The only place where we needed improvement was the  __attribute__ ((__packed__)); scenario where the code tells the compiler "this struct's members may not be properly aligned"

**Comment by mheyer32** [comment]
I'm also surprised about the way your patch works :-)
I may be wrong, but from  just looking at the single function (without knowing the broader context)  I would have expected that the solution was to return the smallest alignment possible for the given mode, not the biggest one.

**Comment by bebbo** [comment]
you are right - that change is not the correct one - undoing it.

**Comment by bebbo** [comment]
it's working in both directions and should have less side effects^^
```
unsigned foo(void * ptr) {
        struct Unaligned32 { unsigned val; } __attribute__ ((__packed__, __may_alias__));
                return ((const Unaligned32 *)ptr)->val;
}

unsigned faa(void * ptr, unsigned v) {
        struct Unaligned32 { unsigned val; } __attribute__ ((__packed__, __may_alias__));
                return ((Unaligned32 *)ptr)->val = v;
}
```

**Comment by mheyer32** [comment]
Yep, that seems to have fixed it. The byte reads are gone and ScummVM doesn't look like barf anymore :-)

Closing.
