### ISSUE TITLE
-O3 leads to guru 8000 0004

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#63]
[make.zip](https://github.com/bebbo/gcc/files/2846263/make.zip)

This works (works = just run the exe and get back at cli -- no makefile)
m68k-amigaos-gcc -noixemul -fbaserel -fomit-frame-pointer -s -o make *.c

This does not work
m68k-amigaos-gcc -noixemul -fbaserel -fomit-frame-pointer -O3 -s -o make *.c

gurus 8000 0004

**Comment by bebbo** [comment]
both are working here - please attach both binaries - compiled without `-s`

**Comment by alexalkis** [comment]
[make.zip](https://github.com/bebbo/gcc/files/2846594/make.zip)
make-crashes is the one that crashes :)

**Comment by bebbo** [comment]
same as mine - both are running.
What Makefile are you using?

**Comment by alexalkis** [comment]
no makefile
testing on A1200 under winuae

**Comment by alexalkis** [comment]
hmmm, actually I got a makefile in the directory I am testing...here is the whole directory I test make in

[a68k.zip](https://github.com/bebbo/gcc/files/2846680/a68k.zip)

**Comment by bebbo** [comment]
`char sys_cmnd[32]; ` is to small

Without enough variables on the stack the return address get trashed.

**Comment by alexalkis** [comment]
huh? spot on.
sorry.
