### ISSUE TITLE
Recent changes in the compiler cause internal compiler errors

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#65]
This must have been introduced with the latest one or two compiler changes.
After I ran into compiler crashes with ScummVM, I decided to do a clean build of the toolchain.
But the toolchoin itself already suffers from the compiler crashing :-)

```
/home/matze/amigatoolchain/amiga-gcc/projects/newlib-cygwin/newlib/libc/misc/ffs.c: In function 'ffs':
/home/matze/amigatoolchain/amiga-gcc/projects/newlib-cygwin/newlib/libc/misc/ffs.c:32:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Makefile:366: recipe for target 'lib_a-ffs.o' failed
```
[make newlib.log](https://github.com/bebbo/gcc/files/2848620/make.newlib.log)

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
That seems to have fixed it. Thanks!
