### ISSUE TITLE
Do __asm parameters work in C++ files?

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#66]
I don't seem to be able to use register parameters in files compiled with m68k-amigaos-g++.
I don't know if this is a bug or works-as-intended.

The declaration of the function already fails:

```
extern "C" {
void test( short chunkyx __asm(d0));
}

```
```
backends/platform/amigaos3/amigaos3-graphics-aga.cpp:67:26: error: expected ',' or '...' before '__asm'
 void test( short chunkyx __asm(d0));
```

__regargs DOES work (even for member functions), but doesn't give me enough control in this particular case (I need to use up to 7 data registers).

**Comment by bebbo** [comment]
g++ is using a different parser which does not have that asm reg extension...

**Comment by mheyer32** [comment]
Ok, thats what I thought, thanks.
I guess, I'll have to go through gcc then, i.e. implement a C trampoline function that I can link the C++ code against and which is in turn going to call into the assembly function.

**Comment by bebbo** [comment]
you can also use some assembly to call that function:
```
  {
     register int d6 __asm("d6") = a;
     register int d7 __asm("d7") = b;
     asm("jsr __a_s_m");
  }
```

**Comment by mheyer32** [comment]
I see, following the macros.h example.

Any chance to get direct parser support? ;-)

Closing.

**Comment by bebbo** [comment]
aye, as in macros.h - so don't forget to specify the clobbers d0/d1/a0/a1/fp0/fp1 unless one of these is a return value, then add it as return value and use it.

**Comment by mheyer32** [comment]
That seems to do it:
```
  2a98ec:	4242           	clr.w d2
  2a98ee:	4243           	clr.w d3
  2a98f0:	4284           	clr.l d4
  2a98f2:	4285           	clr.l d5
  2a98f4:	4287           	clr.l d7
  2a98f6:	4240           	clr.w d0
  2a98f8:	4241           	clr.w d1
  2a98fa:	4eb9 0000 0000 	jsr 0 <_stext>
```

Interestingly the actual function is implemented in assembly and then linked into the project (I am honestly surprised that this 'just worked' as the rest of the project is linked with LTO).
But for some reason, the two assembly .o's seem to cause objdump to restart at address 0.
This is why the above code seems to jump to 0

Is it possible to have multiple .text hunks in one executable and still get the relocation 'right'?

**Comment by bebbo** [comment]
objdump is not too smart - also use `-r` to see the relocs

**Comment by bebbo** [comment]
this is working in branch devel1:
```
int foo(register int * x asm("d7")) {
  return *x + 1;
}

int faa(int a __attribute__((__asmreg__(9)))) {
  return a + a;
}

int fee(int c asm("d4"), int d __attribute__((__asmreg__(5)))) {
  return foo(&c) + faa(d);
}
```
and creates
```
        .text
        .align  2
        .globl  __Z3fooU6asmregILi7EEPi
__Z3fooU6asmregILi7EEPi:
.LFB0:
        move.l d7,a0
        move.l (a0),d0
        addq.l #1,d0
        rts
.LFE0:
        .align  2
        .globl  __Z3faaU6asmregILi9EEi
__Z3faaU6asmregILi9EEi:
.LFB1:
        move.l a1,d0
        add.l d0,d0
        rts
.LFE1:
        .align  2
        .globl  __Z3feeU6asmregILi4EEiS_
__Z3feeU6asmregILi4EEiS_:
.LFB2:
        link.w a5,#-4
.LCFI0:
        move.l d7,-(sp)
        move.l d2,-(sp)
        move.l a5,a0
        move.l d4,-(a0)
        move.l a0,d7
        jsr __Z3fooU6asmregILi7EEPi
        move.l d5,a1
        move.l d0,d2
        jsr __Z3faaU6asmregILi9EEi
        add.l d2,d0
        move.l (sp)+,d2
        move.l (sp)+,d7
        unlk a5
        rts
.LFE2:
```

**Comment by bebbo** [comment]
please test

**Comment by bebbo** [comment]
Does anyone want to test this before I close the ticket?

**Comment by mheyer32** [comment]
I intended to give it try, but just didn't get to it yet. Sorry!

**Comment by mheyer32** [comment]
So, it looks like one can create functions with __asm(x) parameters, but when I try to create a function pointer, gcc barfs on me:

`typedef int (*Comparator)(const void * lhs __asm(a0), const void *  rhs __asm(a1));`

```
./common/array.h:401:51: error: expected string-literal before 'a0'
  typedef int (*Comparator)(const void * lhs __asm(a0), const void *  rhs __asm(a1));
                                                   ^~
./common/array.h:401:51: error: expected ')' before 'a0'
./common/array.h:401:51: error: invalid register specified 
./common/array.h:401:51: error: `asmreg' attribute: value -49 not in [0 - 23]
./common/array.h:401:51: error: expected ',' or '...' before 'a0'
./common/array.h:401:56: error: expected unqualified-id before 'const'
  typedef int (*Comparator)(const void * lhs __asm(a0), const void *  rhs __asm(a1));

```

**Comment by bebbo** [comment]
ehm, uhm, öhm...

.. then syntax requires quotes:

```
typedef int (*Comparator)(const void * lhs __asm("a0"), const void * rhs __asm("a1"));
```

**Comment by mheyer32** [comment]
*Facepalm* 

Alright. Confirmed. Things are working. Closing.
