### ISSUE TITLE
GCC is not honouring EA cost when shuffling instructions.

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#68]
In the case where we move, then yes, the pipeline can forward the results from the first to second instruction and not cause a stall. This is not the case with EA computation.
```
        bfextu d0{#0:#4},d4
        move.w (a0,d4.l*4),d4
```
The problem is d4 and when EA gets computed in the pipeline, the above sequence will cause a two cycle stall while the move waits for d4. This is pointed out in 10.2 (Point 3) in the 68060 manual.
![image](https://user-images.githubusercontent.com/13053976/52793852-e843df80-302b-11e9-8efa-abb593018c78.png)

_Originally posted by @nonarkitten in https://github.com/bebbo/gcc/issues/67#issuecomment-463651430_

**Comment by nonarkitten** [comment]
Done.

**Comment by nonarkitten** [comment]
Somehow github got confused...

**Comment by nonarkitten** [comment]
Fun fact, found a way to enforce assignment order. Define this and then place it between the operations you need to keep in-order. This must get optimized into oblivion at some point but will do so AFTER the re-order stage.

```
#define DO_NOT_REORDER(VAR) \
    __asm__ volatile ("" : "+m" (VAR));
```

**Comment by bebbo** [comment]
first progress:
```
_draw:
        link.w a5,#0
        movem.l a2/d5/d4/d3/d2,-(sp)
        move.l 8(a5),a1
        move.l 16(a5),d0
        lsl.l #6,d0
        move.l d0,a0
        addq.l #2,a0
        move.l 12(a5),a2
        add.l __palette,a0
        clr.l d1
.L12:
        move.l (a2)+,d0
        jeq .L3
        bfextu d0{#4:#4},d3
        bfextu d0{#8:#4},d2
        bfextu d0{#0:#4},d4
        bfextu d0{#12:#4},d5
        move.w (a0,d4.l*4),d4
        jlt .L4
       ...
```

**Comment by bebbo** [comment]
please test

**Comment by bebbo** [comment]
works for me

**Comment by nonarkitten** [comment]
I wasn't able to find an example that put a one-cycle instruction between them, so I'll assume its fixed.
