### ISSUE TITLE
Small bugs with Regparm?

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#69]
If \_\_attribute\_\_((regparm(n))) uses an 'n' that is more than the actual number of registers used in the prototype, regparm is not used at all and reverts to stack but using -mregparm=4 will always work.

And -mregparm without a number gives a compiler error (m68k-amigaos-gcc: error: unrecognized command line option '-mregparm'; did you mean '-mregparm='? Compiler returned: 1) -- should default to 2 when not provided.

**Comment by bebbo** [comment]
A wrong regparm count yields an error:
```
error: `regparm' attribute: value 8 not in [0 - 4]
```

Please post your example, if not.

**Comment by nonarkitten** [comment]
[-mregparm](https://franke.ms/cex/z/24aQNL) error (no default).

[\_\_attribute\_\_((regparm(4)))](https://franke.ms/cex/z/rpVFn1) error (higher regparm than actual args reverts to stack call).

**Comment by bebbo** [comment]
```
int foo(int a, int b, int c, int d, int e, int f, int g, int h) {
  return a + b + c + d + e + f + g + h;
}

__attribute__((regparm(3))) int faa(int a, int b, int c, int d, int e, int f, int g, int h) {
  return a + b + c + d + e + f + g + h;
}
```

`m68k-amigaos-gcc -S -Os parms.c -mregparm=1`
```
_foo:
        link.w a5,#0
        add.l a0,d0
        add.l 8(a5),d0
        add.l 12(a5),d0
        add.l 16(a5),d0
        add.l 20(a5),d0
        add.l 24(a5),d0
        add.l 28(a5),d0
        unlk a5
        rts
        .align  2
        .globl  _faa
_faa:
        link.w a5,#0
        add.l d1,d0
        add.l d2,d0
        add.l a0,d0
        add.l a1,d0
        add.l a2,d0
        add.l 8(a5),d0
        add.l 12(a5),d0
        unlk a5
        rts
```

`m68k-amigaos-gcc -S -Os parms.c -mregparm=4`
```
_foo:
        add.l d1,d0
        add.l d2,d0
        add.l d3,d0
        add.l a0,d0
        add.l a1,d0
        add.l a2,d0
        add.l a3,d0
        rts
        .align  2
        .globl  _faa
_faa:
        link.w a5,#0
        add.l d1,d0
        add.l d2,d0
        add.l a0,d0
        add.l a1,d0
        add.l a2,d0
        add.l 8(a5),d0
        add.l 12(a5),d0
        unlk a5
        rts
```
that's ok, isn't it?

**Comment by bebbo** [comment]
please test

**Comment by nonarkitten** [comment]
I meant if regparm is higher than the actual number of parameters it fails, not the other way around. So if you pass one register and set regparm=4 then it reverts to stack. Not if you have twelve parameters and change regparm -- yes that works. As my example showed:

```
int __attribute__((regparm(4))) add(int a, int b) {
    return a + b;
}
```

Generates this:
```
_add:
        move.l 4(sp),d0
        add.l 8(sp),d0
        rts
```

When it should be:
```
_add:
        add.l d1,d0
        rts
```

**Comment by bebbo** [comment]
why don't you want to test the fix?

**Comment by bebbo** [comment]
works for me

**Comment by nonarkitten** [comment]
Yes it's fixed. Although there's a spurious nop after the rts?
