### ISSUE TITLE
-O2 generates incorrect code

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#7]
When turning on optimization -O2 some incorrect code is generated. In the provided source files 3 functions must be excluded fom comiplation with -O2

WaveCallback()
Wavegen()
PlaySilence()

All three functions contain code that accesses a global pointer,
for instance PlaySilence()
*out_ptr++ = value;
*out_ptr++ = value >> 8;

It seems that some values are lost. (The generated wave-File in my examlpe contains less samples than expected and sound high pitched and to fast (Mickey Mouse voise)

The compiled file works niceley when compiled with Krystof's gcc 2.95.3. 

[wavegen_O2_O0.zip](https://github.com/bebbo/gcc/files/1621642/wavegen_O2_O0.zip)

compile with
/home/developer/opt/m68k-amigaos_gcc6/bin/m68k-amigaos-gcc -g -O2 -c -m68000 -Wall wavegen_O2_O0_preproc.cpp -Wa,-adhln

and

 
/home/developer/opt/m68k-amigaos_gcc6/bin/m68k-amigaos-gcc -g -O2 -c -m68000 -Wall wavegen_O2_preproc.cpp -Wa,-adhln

**Comment by bebbo** [comment]
The opt_elim_dead_assign() function is missing a register invalidation if the register is holding a memory value and a new value is assigned to that memory location.  Thus a memory read is removed and missing.

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
Thanks for the update.
Things seem to have become worse, however. Now the program fails even when compiled completely with -O0

I need some days to investigate. 

Can I link objects from gcc6 together with with gcc.2.95.3 to find offending source-files?

I will probably try a mixture of the older GCC6 and your current one to find the offending file(s).

**Comment by bebbo** [comment]
Wierd that now -O0 is no longer working. Maybe the register allocation order (where I tried to tweak...) affects more than I thought...
... I restored the previous register allocation order

**Comment by bebbo** [comment]
push - please test

**Comment by bebbo** [comment]
And yes, you can link the different object files together.

**Comment by githubaf** [comment]
I managed to rebuild/install your older compilers to compare.

toolchain from 29.December b53eadfdcbe581a27d560072157ddf762e84e4d0
Bug as described at top this issue reproduced. Compiled code basically worked but sound is to fast (missing samples) noise in pauses instead of silence, no prompt after program. Compiling three functions as described with -O0 solved to problen.

toolchain from 11.Jan 1a910101eb956db09fbd9addefcb4fd506a86123
Code seems to be more broken. I get "cannot allocate memory" on the Amiga, even when compiled the whole project with -O0.
I get a working program when I link the -O0-compiled objects with the toolchain from 29.Dec, i.e. there is bad code generated for the libraries? or libnix?

toolchain from 13.Jan 409109688d134cc0733d036ceb36f22bca1c8d59
Code seems to be better than version form 11Jan.
When my complete project is compiled with -O0 I get a working executable. Compiled everything with -O2 results in a non-working executable. I will try find out problematic functions...

**Comment by githubaf** [comment]
Found one of the incorrectly compiled functions when using -O2
Unfortunatelly its quite long.

When compiled with -O0 its ok, when compiled with -O2 the voice sounds monotone/robotic.

Function SetWordStress() 
[dictionary_preproc.zip](https://github.com/bebbo/gcc/files/1634808/dictionary_preproc.zip)

**Comment by bebbo** [comment]
does it run with `-O2 -fbbb=-` ?

**Comment by githubaf** [comment]
No, -fbbb=- does not help. (In fact it makes it even worse)

I compiled everything with -O0 with gcc from 13.Jan
-> program works

deleted dictionary.o
changed CXX-Flags to use -O2
make again
-> monoton voice as described already above.

deleted dictionary.o
changed CXX-Flags to use -O2 -fbbb=-
make again

-> no voice at all

**Comment by githubaf** [comment]
Some success to report:
I did more tests, this time with the latest toolchain-commit from 16.Jan

compiled the whole project with -O0
--> works

compiled the whole project with -O2
--> does not work. Just some low-volume noise

compiled the whole project with -O2 -fbbb=-
--> Works!

What does -fbbb=- mean btw?

**Comment by bebbo** [comment]
`m68k-amigaos-gcc --help=target` shows you the options for `-fbbb=`

It controls my additional optimizations, and some may cause bugs, but the code gets smaller and faster with my optimizations. By default all are enabled: `-fbbb=+`

To get some output which optimizations are used, use '-fbbb=+v`

The diff between `-fbbb=-` and `-fbbb=+` is way easier to search then between -O0 and -O2.

You may also try only specific optimitzations, my guess is that `-fbbb=abcfimprs` will still run and the `e` option is causing the remaining issues.

**Comment by githubaf** [comment]
Confirmed.  The "e" causes the problem.
latest toolchain-commit from 16.Jan

compiling the project with -O2 -fbbb=abcfimprs  -> Work as expected
compiling the project with -O2 -fbbb=abcfimprse  -> does not work correctly

**Comment by bebbo** [comment]
I found some bogus optimization:
```
	move.l 12(a5),a0
.L916:
	tst.b (a0)+
	jne .L916
	move.l 12(a5),d0
	sub.l a0,d0
```
=>
```
	move.l 12(a5),a0
.L916:
	tst.b (a0)+
	jne .L916
	move.l a0,d0 ; ups - a0 was modified and the optimizer did not notice...
	sub.l a0,d0
```

**Comment by bebbo** [comment]
please test the recent push

**Comment by githubaf** [comment]
I cannot compile he last Toolchain-commit a2353f964b8c681d15c184eab7894d509191d16b                 
(Tried several times)

Compilation passes with the last but one commit a0e75400509d2e02d6fd8564f17dcc1da56e316a

DEBUG: copy ".build-m68k/sources/cgx-4.2/cybergraphics_lib.sfd" to "../opt/m68k-amigaos_18Jan/m68k-amigaos/lib/sfd/cybergraphics_lib.sfd"
INFO: sfdc: "cybergraphics_lib.sfd" -> "/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/include/proto/cybergraphics.h"
DEBUG: execute "sfdc --quiet --target=m68k-amigaos --mode=proto --output=/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/include/proto/cybergraphics.h cybergraphics_lib.sfd"
INFO: sfdc: "cybergraphics_lib.sfd" -> "/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/include/inline/cybergraphics.h"
DEBUG: execute "sfdc --quiet --target=m68k-amigaos --mode=macros --output=/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/include/inline/cybergraphics.h cybergraphics_lib.sfd"
INFO: sfdc: "cybergraphics_lib.sfd" -> "/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/include/lvo/cybergraphics.i"
DEBUG: execute "sfdc --quiet --target=m68k-amigaos --mode=lvo --output=/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/include/lvo/cybergraphics.i cybergraphics_lib.sfd"
INFO: stubs: "cybergraphics_lib.sfd" -> "cybergraphics.c"
DEBUG: execute "sfdc --quiet --target=m68k-amigaos --mode=autoopen --output=cybergraphics.c cybergraphics_lib.sfd"
DEBUG: execute "perl -pi -e s/: \"d0\",/:/g cybergraphics.c"
DEBUG: execute "perl -pi -e s/__inline//g cybergraphics.c"
INFO: stubs: "cybergraphics.o" -> "/home/developer/opt/m68k-amigaos_18Jan/m68k-amigaos/libnix/lib/libnix/libstubs.a"
DEBUG: execute "m68k-amigaos-gcc -Wall -Os -fomit-frame-pointer -noixemul -c -o cybergraphics.o cybergraphics.c"
Traceback (most recent call last):
  File "./toolchain-m68k", line 902, in <module>
    globals()[action].__call__(*args.args)
  File "./toolchain-m68k", line 803, in install_sdk
    process_sdk(pkg, name, files)
  File "/home/developer/amigaos-cross-toolchain_18Jan/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/home/developer/amigaos-cross-toolchain_18Jan/common.py", line 359, in wrapper
    fn(*args, **kwargs)
  File "./toolchain-m68k", line 736, in process_sdk
    add_stubs(c_file)
  File "./toolchain-m68k", line 676, in add_stubs
    execute('m68k-amigaos-gcc', '-Wall', '-Os', '-fomit-frame-pointer', *cflags)
  File "/home/developer/amigaos-cross-toolchain_18Jan/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/home/developer/amigaos-cross-toolchain_18Jan/common.py", line 217, in execute
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by githubaf** [comment]
Building toolchaing works again.
Tested with latest toolchain-commit from 21Jan

**Comment by githubaf** [comment]
But still the optimization "e" problem.

latest toolchain-commit from 21.Jan

compiling the project with -O2 -fbbb=abcfimprs -> Works as expected
compiling the project with -O2 -fbbb=abcfimprse -> does not work correctly

**Comment by bebbo** [comment]
do you have a hint which file(s) is(are) affected?

**Comment by githubaf** [comment]
I am investigating...

**Comment by githubaf** [comment]
OK,
the cpp-file I complained last time about compiles fine now.

I found wavegen.cpp causing problems now now when compiled with -O2 -fbbb=abcfimprse. Without the "e" it works.
Here is the preprocessed source. I will try to find the offending function(s).

/home/developer/opt/m68k-amigaos_21Jan/bin/m68k-amigaos-gcc  -g -O2 -fbbb=abcfimprse  -m68000  -Wall -pedantic -c -fno-exceptions  wavegen_O2preproc.cpp

[wavegen_O2preproc.zip](https://github.com/bebbo/gcc/files/1656510/wavegen_O2preproc.zip)

**Comment by githubaf** [comment]
Tried again with latest toolchain commit from Jan, 24th

wavegen.cpp (see previous attachements)
Still two functions in wavegen.cpp must be compiled with -O0

int Wavegen()
static int PlaySilence(int length, int resume)

Espeacially PlaySilence() is very short so that might be be good point to look into.

All other files of espeak compile fine!

**Comment by githubaf** [comment]
Tried again with latest toolchain commit from Jan, 24th

wavegen.cpp (see previous attachements)
Still two functions in wavegen.cpp must be compiled with -O0

int Wavegen()
static int PlaySilence(int length, int resume)

Espeacially PlaySilence() is very short so that might be be good point to look into.

All other files of espeak compile fine!

**Comment by githubaf** [comment]
Please ignore last comment, I installed toolchain from 24. but used toolchain from 21.

**Comment by bebbo** [comment]
well, you have wait for the next push, since the current version has a serious bug: not saving a4/a5 on the stack if needed.

**Comment by githubaf** [comment]
Yes, ok. I was just writing a report that now many failes are broken ;-)

**Comment by bebbo** [comment]
just in time then. It bugged me that there are still superfluous register saves, and the changed code was even shorter and easier but I did not remove enough code, and since the behaviour was changed the masking of a5/a4 (if used) backfired :-)

Pushed this change first, now building and testing

**Comment by bebbo** [comment]
it's ok again - see #6

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
I have currently problems installing the toolchain...

DEBUG: enter directory ".build-m68k/tmp/tmpDIc3q_"
INFO: extract files from ".build-m68k/archives/ira.lha"
Traceback (most recent call last):
  File "./toolchain-m68k", line 900, in <module>
    globals()[action].__call__(*args.args)
  File "./toolchain-m68k", line 307, in xbuild
    _build(False)
  File "./toolchain-m68k", line 612, in _build
    unpack('ira', top_dir='.', work_dir='{build}')
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/common.py", line 359, in wrapper
    fn(*args, **kwargs)
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/common.py", line 421, in unpack
    unarc(src)
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/common.py", line 273, in unarc
    arc = lhafile.LhaFile(name)
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/.build-m68k/host/lib/python2.7/site-packages/lhafile/lhafile.py", line 172, in __init__
    self._GetContents(callback=callback,args=args)
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/.build-m68k/host/lib/python2.7/site-packages/lhafile/lhafile.py", line 181, in _GetContents
    info = self._RealGetContent()
  File "/home/osboxes/amigaos-cross-toolchain_29Jan/.build-m68k/host/lib/python2.7/site-packages/lhafile/lhafile.py", line 209, in _RealGetContent
    raise BadLhafile("this file level is out of support range %d" % os_level)
lhafile.lhafile.BadLhafile: this file level is out of support range 32

**Comment by githubaf** [comment]
Managed installation today.
Compiled program just crashes immediately, however.

The crash is cause by your "f" optimization.
OPTLEVEL=-O2 -fbbb=abcimprseVf   Crashes with SoftareFailure 8000000B
OPTLEVEL=-O2 -fbbb=abcimprseV    WORKS!

**Comment by githubaf** [comment]
Tested again with latest version from 31. Jan.
No Guru now but program still fails when compiled with your "f" option. 

OPTLEVEL=-O2 -fbbb=abcimprseVf no Software Failure this time now but still does not work
OPTLEVEL=-O2 -fbbb=abcimprseV WORKS!

**Comment by bebbo** [comment]
you tested a bit to early - now it's fixed. a5 frame is no longer dropped if stack variables are referenced.

**Comment by githubaf** [comment]
YES, now -O2  works!
Great.
Thank you.

**Comment by bebbo** [comment]
Thank you for testing and patience.
