### ISSUE TITLE
Natural alignment of struct members broken?

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#71]
For below example you'd expect 'pixels' to be placed at offset 8, leaving 2 bytes of padding.
But instead, 'pixels' is at offset 6. 

Or am I having the wrong expectations here?

```
#include <stdio.h>
#include <stddef.h>

typedef unsigned short uint16;

/**
 * An arbitrary graphics surface, which can be the target (or source) of blit
 * operations, font rendering, etc.
 */
struct Surface {
	/*
	 * IMPORTANT implementation specific detail:
	 *
	 * ARM code relies on the layout of the first 3 of these fields. Do not
	 * change them.
	 */

	/**
	 * The width of the surface.
	 */
	uint16 w;

	/**
	 * The height of the surface.
	 */
	uint16 h;

	/**
	 * The number of bytes a pixel line has.
	 *
	 * Note that this might not equal w * bytesPerPixel.
	 */
	uint16 pitch;

//protected:
	/**
	 * The surface's pixel data.
	 */
	void *pixels;

public:
	/**
	 * The pixel format of the surface.
	 */
	int format;

	/**
	 * Construct a simple Surface object.
	 */
	// Surface() : w(0), h(0), pitch(0), pixels(0), format() {
	// }
};


int main(int argc , char **argv)
{
	printf("surface size %d, offset pixels %d, offset format %d\n", sizeof(Surface), offsetof(Surface, pixels), offsetof(Surface, format));

}
```

**Comment by bebbo** [comment]
uhm, I expect 6.
why should it be 8?

**Comment by bebbo** [comment]
the alignment is 2 bytes as in all other gcc versions for the Amiga or 68k-elf.

**Comment by mheyer32** [comment]
Oh, ok, I was expecting alignment of 4 for 32bit ints/pointers - I'm just used to seeing that on x86 :-)

Is there any performance penalty on 68k+ for unaligned 32bit accesses?

**Comment by bebbo** [comment]
starting with 68040 there is (without cache hit) an additional bus cycle if 32 bit memory is used. reading from odd addresses gets you 3 additional bus cycles.

**Comment by mheyer32** [comment]
Is there a way to instruct the compiler to use 4 byte alignment for 32bit variables?

I'd like to play around with this, but it would be impossible to do it by manually going in an trying to align all struct members in ScummVM.

**Comment by bebbo** [comment]
I am not aware of such a switch - sorry. And you could build your own version of m68k-amigaos-gcc :-)

**Comment by hlide** [comment]
use __attribute__((align=4)) before pixels.
