### ISSUE TITLE
-fno-inline interacts badly with -fbbb

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#73]
In order to debug on the -fshort-enums issue, I wanted to get a better picture of how individual functions look like in assembly, so the goal was to prevent inlining, while still keeping all other optimizations intact. Thus the use of -fno-inline.

Unfortunately, this made debugging things _worse_ as ScummVM now started asserting left and right or was having other issues :-)

This is a low-priority bug as -fno-inline is probably never going to be used 'in real life'. But still, there is something broken in how it interacts with -fbbb=

**Comment by bebbo** [comment]
my optimizer does not know about `-fno-inline` or anyother switch but
 - selected cpu
 - optimize for size or speed

so no idea what might be wrong...

**Comment by mheyer32** [comment]
I tracked it down to -fbbb=i

`-noixemul -m68030 -fno-inline -fno-rtti -fno-exceptions -fstack-reuse=all -fstrict-aliasing -fomit-frame-pointer -fbbb=-  : ScummVM starts up as usual`

`-noixemul -m68030 -fno-inline -fno-rtti -fno-exceptions -fstack-reuse=all -fstrict-aliasing -fomit-frame-pointer -fbbb=i : ScummVM will assert short after start, before the main menu`

ScummVM is configured as follows:

` ./configure --host=m68k-amigaos --disable-all-engines --enable-engine=sci,tinsel --disable-mt32emu --enable-debug --enable-optimizations --disable-hq-scalers  --disable-translation --enable-c++11  --disable-updates  --with-amiga-prefix=<choose your path here>`  

I went into configure and added '-fno-inline' into
` _machine_flags="-noixemul -m68030 -fno-inline" `

build as usual

make amigaos3dist

**Comment by mheyer32** [comment]
https://github.com/mheyer32/scummvm-amigaos3/blob/master/graphics/fonts/bdf.cpp#L120

This is the assert that is blowing up

**Comment by bebbo** [comment]
How do you test your program?

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
That fixed it! Thanks!

Is this something that could have affected other scenarios, too? Any idea why it only showed up with -fno-inline?

**Comment by bebbo** [comment]
> Is this something that could have affected other scenarios, too? Any idea why it only showed up with -fno-inline?

Yeah, that could have happened anywhere.
