### ISSUE TITLE
"shuffle insn order somehow and somewhere" introduced subtle bug(s)

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#74]
c468da7fdf22099cf739b15fb63abec6661e3f6d

Introduced some bad side effects that causes ScummVM to crash, assert etc.

( a4ac6859e30f2a6791a063ee26090a9c660f92de  did not fix it)

I attached a diff of the asm generated for ScummVM with gcc compiled right before and after the change
( << being the old code   >> being the new code)

But this is 9 megs of what mostly looks like benign reorderings, I haven't found the smoking gun yet.

[diff.txt](https://github.com/bebbo/gcc/files/2892638/diff.txt)

[scumm_assembly.zip](https://github.com/bebbo/gcc/files/2892667/scumm_assembly.zip)

**Comment by mheyer32** [comment]
One idea: if we can't find obviously broken code in the diff... is it possible that the reordering of instructions disregarded jumptargets? I.e.  if I  have

A  jump to C
...
B  do X
C  do Y

and B and C get reordered, we might execute the wrong sequence.

(disclaimer: I don't really have an idea how jumps are represented in gcc, so above may be nonsense)

**Comment by bebbo** [comment]
I'm checking a lot. But obviously I missed something...
... guess I have to make scummvm run on WinUAE. First hurdle:

```
if (proc->pr_StackSize < 100000)
```
=>
```
if ((char*)task->tc_SPUpper - (char*)task->tc_SPLower) < 100000)
```

Now I'm building all with `-fbbb=abcefilmprsz` then change it to `-fbbb=abcefilmnprsz` and erase objects in some folder, make and see - until it fails. 

Must be something stupid - as usual :-)

**Comment by bebbo** [comment]
found an affected file: `engines/sci/engine/vm.o`

**Comment by bebbo** [comment]
code before
```
	move.l 94(a3),a1
	move.l a2,4(a0)
	move.l a1,(a0)
	move.l a0,4(a1)
	move.l 4(a0),a1
	move.l 94(a3),d0
	addq.l #8,d0
	move.l a0,(a1) # this is (94(a3))
```
code after
```
	move.l a2,4(a0)
	move.l 94(a3),a1
	move.l a1,(a0)
	move.l a0,4(a1)
	move.l 4(a0),a1
	move.l a0,(a1) # this is (94(a3))
	move.l 94(a3),d0
	addq.l #8,d0
```

=> ouch

**Comment by bebbo** [comment]
it's running again

**Comment by mheyer32** [comment]
Wow that looks like the literal needle in the haystack! Testing now.

Btw, whats wrong with:
```
 if (proc->pr_StackSize < 100000) {

}

```
?

**Comment by mheyer32** [comment]
Fix confirmed.
