### ISSUE TITLE
scanf/printf  is/are broken

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#76]
Likely scanf is the offender as ScummVM seems not to be able to parse the ini file correctly,

This was introduced with commit 396a8e85029ecfd158a3ef0f1af492cb3a958bae

Maybe I can dig a bit deeper tomorrow.

**Comment by bebbo** [comment]
You found something very valuable, you found a gem: Sebum!

It happens that this code:
```
.L185:
	move.l a6,d2
.L1:
```
gets converted to
```
.L185:
	move.l a6,a6
.L1:
```
and thus the statement is dropped:
```
.L185:
.L1:
```
that's all ok. But it run into the bug that collecting the registers to rename stopped at `.L1` since the previous insn `.L185` does not use the searched register (label's don't use registers at all).
Thus a false rename of a register occurs which is used elsewhere...

**Comment by mheyer32** [comment]
Ha, why am I always the lucky one to find the gems? :-D

**Comment by mheyer32** [comment]
(I'm still in the process of rebuilding the toolchain and Aminet is not helping)

**Comment by bebbo** [comment]
> 
> 
> Ha, why am I always the lucky one to find the gems? :-D

You are the only user...

**Comment by bebbo** [comment]
> 
> 
> (I'm still in the process of rebuilding the toolchain and Aminet is not helping)

it's ok to copy the download folder from other build attempts

**Comment by mheyer32** [comment]
Time's out for today. More testing tomorrow night. Hopefully Aminet is back up by then - I didn't keep a copy of my download directory. Are there working mirrors?

**Comment by bebbo** [comment]
> http://de.aminet.net/aminet/

**Comment by mheyer32** [comment]
Woohoo! vsnprintf() seems to work again. 
Now I need to find out why ScummVM jumps to 0x00000000 during the intro of DiscWorld... it didn't do that before. 
I'll file a new issue once I know more.

Btw, could we make the aminet mirror adjustable via an env variable? I helped myself with a small sed script for now, but it would be cool to have a switch in case the main mirror is down again (which seems to happen rather often).
