### ISSUE TITLE
Extra move.l with bit fields?

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#82]
Seems like 6.5 performs a move.l before the bfextu instead of simply performing the bfextu directly from memory. I'm not at all sure which is actually faster though -- when registers are tight, I would presume doing it in one instruction, but maybe on 68060, it's faster to split? This move.l, however, appears on all 68020 and up architectures.

https://franke.ms/cex/z/EcVjgG

**Comment by nonarkitten** [comment]
Halfway there, -O3 will make the moves disappear, but not -Os (which is ironic).

**Comment by bebbo** [comment]
guess you watched cached results on https://franke.ms/cex/
I restarted cex to clear the cache.

**Comment by nonarkitten** [comment]
Fixed!
