### ISSUE TITLE
Some optimizations

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#84]
https://franke.ms/cex/z/WxOCHS
```
op=*pc++; goto *jump_table[op >> 6];
```
Becomes...
```
.L1:
        move.l a6,a0
        addq.l #2,a6
        move.w (a0),d0
        move.w d0,d3
        bfextu d3{#16:#10},d0
        move.l -2032(a5,d0.l*4),a0
        jmp (a0)
```
A lot wrong with a bit of code. It probably should be:
```
        movew a6@+,d3
        bfextu d3{#16:#10},d0
        jmp [a2@(d0:l:4)]
```
Note that -O3 in 2.95.3 gives the above with split jump (move to a0, jmp (a0)), and again, -Os produces larger code than -O3. Hmmm.

In general, especially with -Os, fusing the pattern "move to a0, do something with (a0)" should just use the 68020 and up double-indirect modes. This would really help crunch code size too.

**Comment by bebbo** [comment]
gcc 6 does not like global asm register variables..
... with
```
int run_m68k(int cycles,
  register uint16_t *pc asm("a6"),
  register uint16_t op asm("d3")
) {
```
it looks different.

> In general, especially with -Os, fusing the pattern "move to a0, do something with (a0)" should just use the 68020 and up double-indirect modes. This would really help crunch code size too.

I have to check if the processor definition `m68k.md` knows about these insns, and if these could be utilized somehow

**Comment by bebbo** [comment]
> gcc 6 does not like global asm register variables..

since op is a global variable, gcc-6 want's to update it - always.

**Comment by bebbo** [comment]
what about:
```
        bfextu (a0,){#0:#10},d0
        addq.l #2,a0
        jmp [(_jump_table.1194,d0.l*4])
```
?

**Comment by nonarkitten** [comment]
> gcc 6 does not like global asm register variables..
> ... with
> 
> ```
> int run_m68k(int cycles,
>   register uint16_t *pc asm("a6"),
>   register uint16_t op asm("d3")
> ) {
> ```
> it looks different.
> 
> ```
> .L1:
>         bfextu (a0){#0:#10},d0
>         move.l -2032(a5,d0.l*4),a1
>         addq.l #2,a0
>         jmp (a1)
> ```
This would definitely be a bug then. Using locally scoped variables is not always possible. The over-tenacious reading/writing from the global variable would be more like volatile behaviour, no? I mean, this isn't the case under 2.95.

**Comment by nonarkitten** [comment]
> what about:
> 
> ```
>         bfextu (a0){#0:#10},d0
>         addq.l #2,a0
>         jmp ([_jump_table.1194,d0.l*4])
> ```
> ?
Interesting... could this then be:
```
        bfextu (a0)+{#0:#10},d0
        jmp ([_jump_table.1194,d0.l*4])
```

**Comment by nonarkitten** [comment]
> > what about:
> > ```
> >         bfextu (a0){#0:#10},d0
> >         addq.l #2,a0
> >         jmp ([_jump_table.1194,d0.l*4])
> > ```
> > ?
> > Interesting... could this then be:
> 
> ```
>         bfextu (a0)+{#0:#10},d0
>         jmp ([_jump_table.1194,d0.l*4])
> ```
Hmmm, no, never mind, bfextu would imply a "long" operation, so a0 would jump by 4. So yeah, if it can do this, then that would be fine.

**Comment by bebbo** [comment]
> This would definitely be a bug then. Using locally scoped variables is not always possible. The over-tenacious reading/writing from the global variable would be more like volatile behaviour, no? I mean, this isn't the case under 2.95.

It's not a bug - it's playing safe :-)

**Comment by bebbo** [comment]
and
```
bfextu (a0)+{#0:#10},d0
```
is not a valid insn!

**Comment by nonarkitten** [comment]
> and
> 
> ```
> bfextu (a0)+{#0:#10},d0
> ```
> is not a valid insn!
Right. Wasn't thinking straight.

**Comment by bebbo** [comment]
and with the global `d3` that register **must be updated**
with parameter it would work without updating `d3`

**Comment by bebbo** [comment]
current state:
```
_run_m68k:
        link.w a5,#-2032
        pea 2032.w
        pea .LC1
        pea (-2032,a5)
        jsr _memcpy
        move.w (a6)+,d3
        bfextu d3{#16:#10},d0
        add.w #12,sp
        jmp ([-2032,a5,d0.l*4])
.L86:
.L1:
        move.w (a6)+,d3
        bfextu d3{#16:#10},d0
        jmp ([-2032,a5,d0.l*4])
```

**Comment by bebbo** [comment]
please test

**Comment by nonarkitten** [comment]
Impressive :) Looks good!
