### ISSUE TITLE
Building NBlood

### ISSUE THREAD

**Issue by BSzili** [bebbo/gcc#89]
I tried to build NBlood, but I'm getting internal compiler errors like this:

> source/blood/src/view.cpp: In function 'void viewResizeView(int)':
source/blood/src/view.cpp:1567:1: internal compiler error: Segmentation fault
 }
 ^
source/blood/src/view.cpp:1567:1: internal compiler error: Bus error
mmap: No such device

My fork is available here:
https://github.com/BSzili/NBlood/tree/amiga

**Comment by bebbo** [comment]
please test

**Comment by BSzili** [comment]
Great, now it builds!
