### ISSUE TITLE
pragma GCC push_options & pragma GCC pop_options do not work anymore (13.Jan)

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#9]
I am using push_options and pop_options to set the optimization level of single functions in order to find functions which get wrongly compiled in case of -O2.
That worked fine in GCC from 29.Dec.
( I found three functions in one source file which needed -O0)
Push and pop seem no longer to work in toolchain from 13.Jan
 

call gcc with -O2

// source.cpp
#pragma GCC push_options
#pragma GCC optimize ("-O0")
#pragma GCC pop_options

// all following code seems to be compiled with -O0, although "pop_options" should have restored the -O2 setting from the commandline

**Comment by bebbo** [comment]
```
#pragma GCC push_options
#pragma GCC optimize ("-O0")
int foo(void) {
   int i = 1234;
   i = i + 1;
   return i;
}
#pragma GCC pop_options
int faa(void) {
   int i = 1234;
   i = i + 1;
   return i;
}
```
using `m68k-amigaos-gcc -O3 pp.c -S` yields:
```
_foo:
        link.w a5,#-4
        move.l #1234,-4(a5)
        addq.l #1,-4(a5)
        move.l -4(a5),d0
        unlk a5
        rts
        .align  2
        .globl  _faa
_faa:
        move.l #1235,d0
        rts
```

So it's working as expected, no?

**Comment by githubaf** [comment]
OK, but I am still confused...
But why are the *.s-Files so different? 
The 3 pragma-Lines at the beginning of the files make the file working correctly even when compiled with -O2 (!) but IMHO they should have no effect?

/home/developer/opt/m68k-amigaos_13Jan/bin/m68k-amigaos-gcc -fpermissive -g -O2 -m68000 -Wall -pedantic -fno-exceptions dictionary_ohne_pragma.cpp -S


[dictionary_pragma.zip](https://github.com/bebbo/gcc/files/1635144/dictionary_pragma.zip)

**Comment by bebbo** [comment]
It looks like adding such an pragma causes
1. flush all generated asm code 
  here mostly constants
  **plus** inline functions, -O0 does no inlining.
2. since all inline functions are created, those functions are used.

But rest seems ok on a first glance.

**Comment by githubaf** [comment]
OK, but as I wrote:
The 3 pragma-Lines at the beginning of the files make the file working correctly even when compiled with -O2.

That means something goes wrong - with inlining?

**Comment by bebbo** [comment]
There is no difference to the normal gcc behaviour.
