### ISSUE TITLE
Broken inlines for cia

### ISSUE THREAD

**Issue by alexalkis** [bebbo/gcc#90]
[cia.zip](https://github.com/bebbo/gcc/files/3070582/cia.zip)

It's not a gcc issue, but...If you run make it compiles (using clib/*) if you make clean and then make CFLAGS=-DINLINE you get the following:

```
In file included from /opt/amiga/gcc6/m68k-amigaos/ndk-include/proto/cia.h:13:0,
                 from Cia_interval.c:20:
Cia_interval.c: In function 'TryTimer':
Cia_interval.c:416:9: error: expected expression before 'struct'
   if (!(AddICRVector(ft->ciabase,CIAICRB_TA,&ft->timerint)))
         ^
Cia_interval.c:422:9: error: expected expression before 'struct'
   if (!(AddICRVector(ft->ciabase,CIAICRB_TB,&ft->timerint)))
         ^
<builtin>: recipe for target 'Cia_interval.o' failed
```

Also, is there a way to make a function save all registers? Say if it gets called as an interrupt handler?

I've tried __interrupt attribute but that ends the function with RTE.
As it is the program works, but if you m68k-amigaos-objdump -D ciai | less and check ExampleInterrupt it uses registers that it doesn't save.

Is it random that it works? Does the caller saves all registers prior?

**Comment by alexalkis** [comment]
scratch the last remark

> All interrupt processing code, both handlers and servers, is invoked as assembly code subroutines. Normal assembly code register conventions dictate that the D0, D1, A0 and A1 registers be free for scratch use. In the case of an interrupt handler, some of these registers also contain data that may be useful to the handler code. See the section on handlers below.

**Comment by bebbo** [comment]
the macros are having wrong names. Use `LP3UB` instead of `LP3NB` and so on.

No idea if sfdc or the inline/macros.h is wrong... but they do not match in this case

**Comment by alexalkis** [comment]
Hmm, cia has two "bases"
```
/* get pointers to both resource bases */

ciaabase = OpenResource(CIAANAME);
ciabbase = OpenResource(CIABNAME);
```

Maybe sfdc can't handle the case.

I've noticed that if I run sfdc on NDK_3.9's supplied sfd it runs, but if I use the cia.fd to produce the sfd
then I get
```
sfdc --mode macros cia.sfd 
Processing SFD file 'cia.sfd'.
Unable to find or guess base name.
Please add "==libname module_name" to SFD file.
Died at /opt/amiga/gcc6/bin/sfdc line 684.
```

**Comment by bebbo** [comment]
the generated names simply do not match those provided in macros.h

=> I pushed an update to macros.h


>Hmm, cia has two "bases"

That's why the first parameter specifies the base

**Comment by alexalkis** [comment]
Although I see the change in github on fd2pragma, running 'make update' doesn't pull anything on the toolchain. (dependency issue?)

**Comment by bebbo** [comment]
... the Makefile is not perfect :-)

use `make clean-ndk` then `make ndk`

**Comment by alexalkis** [comment]
will do that.
But inside toolchain projects/fd2pragma
git config --get remote.origin.url
https://github.com/adtools/fd2pragma

**Comment by bebbo** [comment]
uh oh :-)

`make update-repos`

**Comment by alexalkis** [comment]
make update-repos breaks on 
```
/bin/bash: line 0: cd: projects/libsdl12: No such file or directory
fatal: No such remote 'origin'
```
Inside projects the folder is libSDL12

After that I can't git pull the toolchain at all
```
git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

```

**Comment by alexalkis** [comment]
Issue fixed. Sample compiles/links with inlines now. Thanks!
