### ISSUE TITLE
Optimizer question on relative addressing

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#93]
The compiler seems to always avoid .w on the data registers in data register-relative addressing modes, even if it knows that the offset cannot exceed 16bit. It'll always take care to either extent or mask the data register for .l usage.

.w is supposed to be a few cycles faster and will allow the compiler to forgo sign-extending or masking the data register first.

```
   32906:	ext.l d1
   32908:	adda.l d0,a0
   3290a:	clr.l d0
   3290c:	move.b (0,a0,d1.l),d0
   32910:	move.b (0,a4,d0.l),(a2)+
```

rearranging the source a bit and using ushort for the variables produces similar results:

```
   32904:	add.w d1,d0
   32906:	andi.l #65535,d0   <<< unnecessary if
   3290c:	move.b (0,a2,d0.l),d0   <<< we used d0.w here
   32910:	andi.l #255,d0
   32916:	move.b (0,a3,d0.l),(a0)+
```

this code was produced for a sequence like this:

 ```
  lighttable_t const* const light = ds_colormap;
    byte const* const source = ds_source;
    const fixed_t dx = ds_xstep;
    const fixed_t dy = ds_ystep;

    do {
        /* Current texture index in u,v.*/
        short y = yfrac >> 14;
        short x = xfrac >> 16;
        short block = ((x & 60) + ((y & (60<<2)) << 2)) << 2;
        short inblock = (x & 3) + ((y & (3<<2)));

        /* Lookup pixel from flat texture tile,*/
        /*  re-index using light/colormap.*/
        *dest++ = light[source[block + inblock]];

        /* Next step in u,v.*/
        xfrac += dx;
        yfrac += dy;

    } while (count--);
```

**Comment by bebbo** [comment]
I guess gcc simply does not know about word size index addressing.

**Comment by mheyer32** [comment]
One more observation: if I play for a little bit in  https://franke.ms/cex/z/P-Ey_V

I make a similar observation as nonarkitten in issue #94  -O1 seems to allow the compiler to use .w in  some cases.

**Comment by bebbo** [comment]
it's related to the compilers conversion from short to int.

With -O2 the offset is considered unsigned and thus zero extended to long, since word mode can't be used.
With -O1 it's considered signed and word mode is thus ok.

**Comment by bebbo** [comment]
try `-fno-tree-vrp`

**Comment by bebbo** [comment]
> The compiler seems to always avoid .w on the data registers in data register-relative addressing modes, 
> ...
> .w is supposed to be a few cycles faster and will allow the compiler to forgo sign-extending or masking the data register first.

Any evidence? The TLDR manuals do not provide such kind of information

**Comment by bebbo** [comment]
```
   32904:	add.w d1,d0
   32906:	andi.l #65535,d0   <<< unnecessary if
   3290c:	move.b (0,a2,d0.l),d0   <<< we used d0.w here
```
on assembly level, the replacement with
```
   32904:	add.w d1,d0
   3290c:	move.b (0,a2,d0.w),d0
```
is not always correct and thus invalid. Since d0.w is considered signed, all valus > 0x8000 will yield different results.

**Comment by bebbo** [comment]
and this
```
short a = ...;
short b = ...;
int x = a + b;
```
is equal to
```
short a = ...;
short b = ...;
int x = (int)a + (int)b;
```
at least that's what gcc does.

**Comment by bebbo** [comment]
I updated my optimizer a bit:
before the `and.l #0xffff,d0` the value mask is `0xffff1fff` => it might be posisble to eliminate the and insn and force the use of `.w`...

**Comment by bebbo** [comment]
please test

**Comment by bebbo** [comment]
the and is dupefluous even with `d0.l` :-)

**Comment by alpine9000** [comment]
I tested this on my latest work in progress game and it gives a very small but measurable performance increase (game still seems to work)

**Comment by bebbo** [comment]
> I tested this on my latest work in progress game and it gives a very small but measurable performance increase (game still seems to work)

nice :-)

**Comment by mheyer32** [comment]
Thanks for looking into this! :-)

WRT instruction timing, I was looking at https://www.nxp.com/docs/en/reference-manual/MC68030UM.pdf
11-27;  but I'm not sure if I interpreted it correctly.

Do your most recent optimizations remove the need to use `-fno-tree-vrp` ?

**Comment by bebbo** [comment]
> 
> 
> Thanks for looking into this! :-)
> 
> WRT instruction timing, I was looking at https://www.nxp.com/docs/en/reference-manual/MC68030UM.pdf
> 11-27; but I'm not sure if I interpreted it correctly.

it reads: `Scaling and size of Xn do not affect timing.`

> Do your most recent optimizations remove the need to use `-fno-tree-vrp` ?

yes, it does

**Comment by mheyer32** [comment]
Cool! Thanks again ^^.
Closing.
