### ISSUE TITLE
Pointless effort around bitfields

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#94]
[Reference](https://franke.ms/cex/z/1mLyHc)

The line
```
acc += decstep[ sample.part.a ];
```
In 2.95 compiles to:
```
bfextu d1{#0:#4},d0
addw a2@(d0:l:2),d2
```
Whereas in 6.5 it's:
```
moveq #15,d5
bfextu d2{#0:#4},d7
and.l d7,d5
add.w (a2,d5.l*2),d1
```
Obviously, the **moveq** and **and.l** are pointless. I feel like we already fixed this...

**Comment by bebbo** [comment]
guess the current optimizer catches only this case:
```
moveq #15,d7
bfextu d2{#0:#4},d5
and.l d7,d5
add.w (a2,d5.l*2),d1
```

**Comment by nonarkitten** [comment]
Very oddly, it does NOT happen on -O1.

**Comment by bebbo** [comment]
it's related to an "expensive optimization" - these aren't enabled with -O1

**Comment by bebbo** [comment]
ups - named a wrong issue in c899655

please test

**Comment by nonarkitten** [comment]
Seems to work. Thanks.
