### ISSUE TITLE
-fbaserel and -fbaserel32 broken

### ISSUE THREAD

**Issue by nonarkitten** [bebbo/gcc#96]
https://franke.ms/cex/z/OYrw0g

Generates compiler error. Directly accessing the variable generates valid code, but performs on optimization on it (treating it like a volatile?).

https://franke.ms/cex/z/Jc6PGV

**Comment by bebbo** [comment]
guess this is a duplicate of #92 and it's already fixed.

https://franke.ms/cex will update to `gcc version 6.5.0b 190515175410 (GCC)` eventually.

**Comment by bebbo** [comment]
ah - this happens only if `-g` is used

**Comment by bebbo** [comment]
please test

**Comment by nonarkitten** [comment]
Works
