### ISSUE TITLE
Getting the GCC test suite to run

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#97]
This is a question not  an issue per se.
I tried getting the GCC test suite to run. And it did - but returned a lot of failures which don't seem to be all real.

The way I went about is
 
```
sudo apt-get install dejagnu
cd ./build-Linux/gcc
make check-gcc-c  PREFIX=/home/matze/amigatoolchain/amiga-gcc-out/  RUNTESTFLAGS=--target_board=m68hc11-sim
```

I was hoping that the m68hc11-sim thingy would be enough to at least test the generated m68k code.

This is the result I got out of it:
```
		=== gcc Summary ===

# of expected passes		43673
# of unexpected failures	19353
# of expected failures		97
# of unresolved testcases	15644
# of unsupported tests		2226
```

The question would be:  do you have any experience with this test suite? Would it be helpful to get it working?

**Comment by bebbo** [comment]
> The question would be: do you have any experience with this test suite? Would it be helpful to get it working?

hey, that's two questions.^^

1. I have very little experience with it.
2. Maybe:

What ist the result of runinng the deja-gnu tests using stock m68k-elf? 
Is it possible to use vamos instead of the m68hc11-sim?
To reduce the failure count all pic and GOT stuff should be ignored...

I won't fix thousands of gcc errors....
... I'm better in adding bugs!

**Comment by mheyer32** [comment]
Actually, it seems someone else already tackled this:
https://frontier.innolan.net/github/amigaos-cross-toolchain6/src/branch/master/dejagnu

**Comment by bebbo** [comment]
using that board seems to use vamos somhow - but - there are tons of errors like

`FAIL: gcc.c-torture/execute/builtins/strlen.c    -O1  execution test`

compiling, linking and running this (and all other I tested) do report no error.

=> useless effort

**Comment by bebbo** [comment]
```
make check-gcc-c RUNTESTFLAGS='--target_board=amigaos  SIM=vamos'
...
                === gcc Summary ===

# of expected passes            13322
# of unexpected failures        880
# of expected failures          19
# of unresolved testcases       543
# of unsupported tests          276
```

**Comment by mheyer32** [comment]
Seems like you got somewhere. I briefly tried the vamos setup last night (I didn't know what it was before), but didn't get very far... the logs showed that the linker wouldn't find libnix.a , ncrt0.o etc...

Was there any specific thing you had to do to get that up & running?

**Comment by bebbo** [comment]
> Was there any specific thing you had to do to get that up & running?

once you've installed `amigaos.exp` you enter the the `gcc` build folder and create once a symbolic link to the `libnix` folder. Then run the tests.

```
pushd build-Linux/gcc
ln -s /opt/amiga/m68k-amigaos/libnix m68k-amigaos/libnix

# all
make check-gcc-c RUNTESTFLAGS='--target_board=amigaos SIM=vamos'

# some...
make check-gcc-c RUNTESTFLAGS='--target_board=amigaos execute.exp=* SIM=vamos'
```
note that you **must not use -j** since vamos can't be run parallel by default. Maybe this can be handled with some kind of  vamos configuration. (filesystem mapping issues)

All tests using functions not present in libnix will fail (e.g. long long functions). Also all tests using unsupported options.

**Comment by mheyer32** [comment]
Nice! I'll give it a run tonight.
My hope was that having such test suite would help identifying bugs more easily.

**Comment by bebbo** [comment]
> 
> 
> Nice! I'll give it a run tonight.
> My hope was that having such test suite would help identifying bugs more easily.

I doubt that one of the subtle bugs is discovered by these uncomplex tests. But who knows?

**Comment by mheyer32** [comment]
Speaking of... the recent optimizations WRT word-offset-addressing triggered a bug in ScummVM, but I was able to mitigate it by switching from uint16 to int16 for a specific type in there ("Selector" in the SCI engine).
I have not yet had the time to dig deeper and find the exact root cause. Once I know more, I'll open an issue.

**Comment by bebbo** [comment]
> 
> 
> Speaking of... the recent optimizations WRT word-offset-addressing triggered a bug in ScummVM, but I was able to mitigate it by switching from uint16 to int16 for a specific type in there ("Selector" in the SCI engine).
> I have not yet had the time to dig deeper and find the exact root cause. Once I know more, I'll open an issue.

I'm not aware of any guilt :-)

**Comment by mheyer32** [comment]
I ran more tests over night:
```
		=== gcc Summary ===

# of expected passes		74190
# of unexpected failures	4754
# of expected failures		98
# of unresolved testcases	3070
# of unsupported tests		2289

```

Not too shabby actually :-)

**Comment by bebbo** [comment]
it helps finding bugs in vamos^^

https://github.com/bebbo/amitools

**Comment by bebbo** [comment]
> note that you **must not use -j** since vamos can't be run parallel by default. Maybe this can be handled with some kind of vamos configuration. (filesystem mapping issues)

map `ram:` in your .vamosrc to use `-j`:
```
[volumes]
ram=/tmp
```

**Comment by mheyer32** [comment]
Cool! Did you somehow find a way to suppress the Undefined Behavior Analyzer tests? They all fail to link because of missing symbols. Not sure how much value we'd get from them anyways...

**Comment by bebbo** [comment]
update:
```
make check-gcc-c RUNTESTFLAGS='--target_board=amigaos  SIM=vamos'

                === gcc Summary ===

# of expected passes            18993
# of unexpected failures        25
# of unresolved testcases       1396
# of unsupported tests          60
/home/bebbo/amiga/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190523234138 (GCC)
```

**Comment by bebbo** [comment]
```
                === gcc Summary ===

# of expected passes            77767
# of unexpected failures        1204
# of expected failures          98
# of unresolved testcases       3033
# of unsupported tests          2281
/home/bebbo/amiga/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190523234138 (GCC)
```

now all invalid tests need to be filtered out...

**Comment by mheyer32** [comment]
Superb progress here!
I didn't expect you to pick up the tab, but I won't object either ;-)
Were any of the recent compiler/libnix commits driven by this effort?

**Comment by bebbo** [comment]
> Were any of the recent compiler/libnix commits driven by this effort?

yes

1. gcc/libnix: re-enabled builtins, added `-fno-builtin` to libnix
2. gcc: fixed an issue and undid another bogus change (bitfield overflow related)
3. vamos: fixed utility.library

**Comment by bebbo** [comment]
make check-gcc-c RUNTESTFLAGS='--target_board=amigaos execute.exp=* SIM=vamos'
```
                === gcc Summary ===

# of expected passes            14813
# of unexpected failures        7
# of unresolved testcases       1
# of unsupported tests          49
/home/stefan/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190603181000 (GCC) 
```

**Comment by mheyer32** [comment]
Veni Vidi Vici!

Thanks for the hard work!

**Comment by bebbo** [comment]
veni vidi απεβην, αει amisi απεθην

**Comment by bebbo** [comment]
make check-gcc-c RUNTESTFLAGS='--target_board=amigaos execute.exp=* SIM=vamos'
```
                === gcc Summary ===

# of expected passes            14820
# of unsupported tests          49
/home/stefan/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190607130956 (GCC) 
```

**Comment by bebbo** [comment]
make check-gcc-c RUNTESTFLAGS='--target_board=**amigaos-baserel** execute.exp=* SIM=vamos'
```
                === gcc Summary ===

# of expected passes            14819
# of unexpected failures        1
# of unsupported tests          49
/home/stefan/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190607130956 (GCC) 
```

**Comment by bebbo** [comment]
make check-gcc-c RUNTESTFLAGS='--target_board=**amigaos-020** execute.exp=* SIM=vamos'
```
                === gcc Summary ===

# of expected passes            14819
# of unexpected failures        2
# of unsupported tests          51
/home/stefan/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190607130956 (GCC) 
```

**Comment by bebbo** [comment]
make check-gcc-c RUNTESTFLAGS='--target_board=**amigaos-020-baserel** execute.exp=* SIM=vamos'
```
                === gcc Summary ===

# of expected passes            14819
# of unexpected failures        2
# of unsupported tests          51
/home/stefan/amiga-gcc/build-Linux/gcc/gcc/xgcc  version 6.5.0b 190607130956 (GCC) 
```

**Comment by bebbo** [comment]
please test.

https://github.com/bebbo/amiga-gcc provides now the 5 base boards which have to be installed manually. Then you can use `make check board=<baseboard>` to run the tests for a board.

**Comment by mheyer32** [comment]
I do see a problem in DirectoryOpus5:
I believe something about the way the stack variable addresses are tracked is broken.
If the saving of registers and allocating stackspace for locals was reversed, I believe it would work.

```
BOOL LIBFUNC L_IsDiskDevice(REG(a0, struct MsgPort *port))
{
   1d558:	4fef ffd8      	lea -40(sp),sp             >>>>>>>> reserve enough for an array of 40 byte 'info'
   1d55c:	48e7 3f22      	movem.l d2-d7/a2/a6,-(sp)      >>>>>>> push registers on stack, mucking with sp
	D_S(struct InfoData,info)
   1d560:	43ef 0024      	lea 36(sp),a1        >>>>> this was supposed to get the start address of 'info'
                                                                   >>>> but is likely overlapping with the saved registers now, not accounting for the previous 'movem.l ...'
   1d564:	2009           	move.l a1,d0
   1d566:	72fc           	moveq #-4,d1
   1d568:	c081           	and.l d1,d0
   1d56a:	2440           	movea.l d0,a2

	// Valid port?
	if (!port) return 0;
   1d56c:	2208           	move.l a0,d1
   1d56e:	6724           	beq.s 1d594 <L_IsDiskDevice+0x3c>

	// Send ACTION_DISKINFO packet to handler
	if (DoPkt(port,ACTION_DISK_INFO,MKBADDR(info),0,0,0,0))
   1d570:	2600           	move.l d0,d3
   1d572:	e483           	asr.l #2,d3
   1d574:	4284           	clr.l d4
   1d576:	4285           	clr.l d5
   1d578:	4286           	clr.l d6
   1d57a:	4287           	clr.l d7
   1d57c:	2208           	move.l a0,d1
   1d57e:	7419           	moveq #25,d2
   1d580:	2c79 0000 000c 	movea.l c <_stext+0xc>,a6
   1d586:	4eae ff10      	jsr -240(a6)
   1d58a:	4a80           	tst.l d0
   1d58c:	6706           	beq.s 1d594 <L_IsDiskDevice+0x3c>
	{
		// Check for valid DOS type
		if (info->id_DiskType!=0) return 1;
   1d58e:	4aaa 0018      	tst.l 24(a2)
   1d592:	660c           	bne.s 1d5a0 <L_IsDiskDevice+0x48>
	}

	return 0;
   1d594:	4240           	clr.w d0
}
   1d596:	4cdf 44fc      	movem.l (sp)+,d2-d7/a2/a6
   1d59a:	4fef 0028      	lea 40(sp),sp
   1d59e:	4e75           	rts
		if (info->id_DiskType!=0) return 1;
   1d5a0:	7001           	moveq #1,d0
}
   1d5a2:	4cdf 44fc      	movem.l (sp)+,d2-d7/a2/a6
   1d5a6:	4fef 0028      	lea 40(sp),sp
   1d5aa:	4e75           	rts
```


This is the original code:

```
/* Long word alignement (mainly used to get
 * FIB or DISK_INFO as auto variables)
 */
#define D_S(type,name) char a_##name[sizeof(type)+3]; \
					   type *name = (type *)((LONG)(a_##name+3) & ~3);

BOOL LIBFUNC L_IsDiskDevice(REG(a0, struct MsgPort *port))
{
	D(bug("\n"));

	D_S(struct InfoData,info)

	D(bug("\n"));

	// Valid port?
	if (!port)
		return 0;

	D(bug("\n"));

	// Send ACTION_DISKINFO packet to handler
	if (DoPkt(port,ACTION_DISK_INFO,MKBADDR(info),0,0,0,0))
	{
		D(bug("\n"));
		// Check for valid DOS type
		if (info->id_DiskType!=0) {
			D(bug("\n"));
			return 1;
		}
	}

	D(bug("\n"));
	return 0;
}
```

**Comment by bebbo** [comment]
what's there left to do?

**Comment by mheyer32** [comment]
Hi Bebbo,

Nothing left - I wqas hoping to run the test suite myself, but just didn't get to it. You took the inintial request far beyond what I was hoping for :-) If I had one more wish, it would be to include instruction on how to install and run the test suite.

I had some trouble with DOpus not registering double clicks on icons anymore. Your most recent compiler changes fixed those again. There's still some mystery bugs left in DOpus and ScummVM, but I haven't had a chance to look into those recently.

I'll close this one. Again, great work, thank you!

**Comment by bebbo** [comment]
- install dejagnu
 - copy the baseboards into dejagnu's baseboards
 - make check [board=<boardname>]
