### ISSUE TITLE
DoomAttack causing internal compiler error

### ISSUE THREAD

**Issue by mheyer32** [bebbo/gcc#99]
Latest toolchain yields:

```
m68k-amigaos-gcc -noixemul -msmall-code -g -ggdb -Werror -Wimplicit -Wstrict-prototypes -D__BIG_ENDIAN__ -DNORMALUNIX -DAMIGA -D__NO_NET_API -include "doomdef.h" -I./plugins/Include -I./ -DNDEBUG -Ofast -ffast-math -fomit-frame-pointer -m68030 -c p_switch.c -o /home/matze/DoomAttack/gnudoom/build//030/p_switch.o
p_spec.c: In function 'getSide':
p_spec.c:185:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 16 41 36 2 (set (reg/f:SI 8 a0 [orig:56 _7->lines ] [56])
        (mem/f:SI (plus:SI (plus:SI (plus:SI (reg:SI 9 a1)
                        (reg/v:SI 1 d1 [orig:45 currentSector ] [45]))
                    (reg:SI 0 d0 [54]))
                (const_int 82 [0x52])) [20 _7->lines+0 S4 A16])) p_spec.c:184 39 {*movsi_m68k2}
     (nil))
p_spec.c:185:1: internal compiler error: in extract_constrain_insn, at recog.c:2196
```

**Comment by mheyer32** [comment]
DirectoryOpus has a similar problem:

```
main.c: In function 'startup_open_libraries':
main.c:434:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 244 335 336 24 (set (reg:SI 8 a0)
        (plus:SI (plus:SI (reg:SI 8 a0)
                (reg/v:SI 0 d0 [orig:31 seed ] [31]))
            (reg:SI 1 d1 [103]))) main.c:433 466 {*lea}
     (nil))
main.c:434:1: internal compiler error: in extract_constrain_insn, at recog.c:2196
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: m68k-amigaos-gcc returned 1 exit status
compilation terminated.
collect2: fatal error: lto-wrapper returned 1 exit status
compilation terminated.
```

**Comment by bebbo** [comment]
There is small chance that the work for #97 - which broke this - has now fixed it again.

please retest

**Comment by mheyer32** [comment]
DoomAttack compiles and works again - it even runs SIGIL now.
ADoom compiles & works - incidentally, the new executable is much smaller (below 400kb for the first time!)

DirectoryOpus5 compiles, runs and the produced libraries are a bit smaller.

ScummVM compiles, but there's a bug in that prevents SCI games from running. With the recent patches that bug has now changed its nature. Instead of the ingame debugger reporting invalid selector IDs, it'll now just sit in an infinite loop somewhere. I'll have to debug this further before I can file a bug.

**Comment by bebbo** [comment]
> 
> 
> DoomAttack compiles and works again - it even runs SIGIL now.
> ADoom compiles & works - incidentally, the new executable is much smaller (below 400kb for the first time!)
> 
> DirectoryOpus5 compiles, runs and the produced libraries are a bit smaller.

the indirect addressing is saving space^^ yeah!
